충남대 BE_이택 5주차 과제 step1
kakao-tech-campus-2nd-step2/spring-gift-order pull request #104
Opened 2024-07-23 06:40 UTC by LeeTaek2T

2024-07-24 12:06 UTC, ksy90101 requested changes
리뷰가 조금 늦었네요!!
고생많으셨습니다~
전반적으로 나눠서 잘 해주셨네요~

2024-07-24 12:06 UTC, ksy90101 commented on src/main/java/gift/DTO/KakaoMember.java
> +  private String code;
clientId, code가 어떤게 저장되나요?

2024-07-24 12:06 UTC, ksy90101 commented on src/main/java/gift/Service/KakaoMemberService.java
> +    var url = "https://kauth.kakao.com/oauth/token";
이건 상수가 맞지 않을까요?

2024-07-24 12:06 UTC, ksy90101 commented on src/main/java/gift/Service/KakaoMemberService.java
> +    }
> 오류 처리
[레퍼런스](https://developers.kakao.com/docs/latest/ko/rest-api/reference)와 [문제 해결](https://developers.kakao.com/docs/latest/ko/kakaologin/trouble-shooting)을 참고하여 발생할 수 있는 다양한 오류를 처리한다.
예를 들어, 아래의 경우 카카오톡 메시지 전송에 동의하지 않았으므로 과제 진행 요구 사항의 안내에 따라 설정한다.

이부분에 대해서 좀더 고민 해보셨을까요?

2024-07-25 06:23 UTC, LeeTaek2T commented on src/main/java/gift/DTO/KakaoMember.java
> +  private String code;
clientId에는 api키, code에는 인가코드가 저장되게 하려고 하였습니다. 
다시 생각해보니 api키는 따로 상수로 지정하면 될 것 같고, 인가코드를 저장하는 것 대신 토큰을 저장하게 하는게 맞는 것 같습니다. 코드 다시 수정하겠습니다.

2024-07-25 07:49 UTC, LeeTaek2T commented on src/main/java/gift/Service/KakaoMemberService.java
> +    var url = "https://kauth.kakao.com/oauth/token";
네! 그런 것 같습니다. 수정하겠습니다

2024-07-25 08:46 UTC, LeeTaek2T commented on src/main/java/gift/Service/KakaoMemberService.java
> +    }
해당 부분을 신경을 못썼었습니다..
해당 레퍼런스들을 참고하여 사용자가 무슨 문제인지 알도록 예외처리를 하였습니다!

2024-07-25 12:38 UTC, ksy90101 requested changes
간단한 피드백을 남겼으니 확인해주세요~

2024-07-25 12:38 UTC, ksy90101 commented on build.gradle
> +    implementation 'io.github.cdimascio:dotenv-java:2.2.0'
이게 추가된 이유가 있나요?

2024-07-25 12:38 UTC, ksy90101 commented on src/main/java/gift/DTO/KakaoJwtToken.java
> +public class KakaoJwtToken {
여기의 있는 값들을 모두다 각각 저장하는 이유가 있나요?

2024-07-25 12:38 UTC, ksy90101 commented on src/main/java/gift/DTO/Option.java
> +  public void subtract(int amount) throws IllegalAccessException {
throws를 할 필요가 있나요?

unchecked Exception과 checkedException을 한번 찾아보시면 좋을거 같아요.

2024-07-25 12:38 UTC, ksy90101 commented on src/main/java/gift/Service/KakaoMemberService.java
> +;
이건 잘못들어간거 같네요.

2024-07-25 12:38 UTC, ksy90101 commented on src/main/java/gift/Service/KakaoMemberService.java
> +  public KakaoJwtToken getToken(String autuhorizationKey) {
API를 호출하는 부분을 따로 컴포넌트로 하면 어떨까요?

2024-07-25 12:38 UTC, ksy90101 commented on src/main/java/gift/Service/KakaoMemberService.java
> +    String clientId = API_KEY;
변수로 받아야 할 이유가 있나요?

2024-07-25 17:26 UTC, LeeTaek2T commented on src/main/java/gift/Service/KakaoMemberService.java
> +;
네! 수정하겠습니다

2024-07-25 17:28 UTC, LeeTaek2T commented on build.gradle
> +    implementation 'io.github.cdimascio:dotenv-java:2.2.0'
api키를 숨기기 위해 .env파일을 gitignore에 넣었는데 env파일에 있는 변수를 사용하기 위해 추가하였습니다

2024-07-25 17:29 UTC, LeeTaek2T commented on src/main/java/gift/DTO/KakaoJwtToken.java
> +public class KakaoJwtToken {
accessToken만 저장하는게 아닌 모두 저장하는 이유는 나중에 refreshToken도 이용해볼려고 미리 저장을 하였습니다.

2024-07-25 18:03 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Option.java
> +  public void subtract(int amount) throws IllegalAccessException {
음...제약조건으로 최소 사이즈를 1로 하였으니 기존의 수량보다 더 많은 양은 차감하려고 해도 제대로 이행이 안될 것 같습니다. throw는 굳이 할 필요가 없을 것 같습니다
반영하겠습니다!!

2024-07-26 05:04 UTC, LeeTaek2T commented on src/main/java/gift/Service/KakaoMemberService.java
> +    String clientId = API_KEY;
아뇨! 없습니다
수정하겠습니다!

2024-07-26 07:06 UTC, LeeTaek2T commented on src/main/java/gift/Service/KakaoMemberService.java
> +  public KakaoJwtToken getToken(String autuhorizationKey) {
네! 알겠습니다!

2024-07-26 13:50 UTC, ksy90101 approved these changes
고생많으셨어요~

2024-07-26 13:50 UTC, ksy90101 commented on src/main/java/gift/DTO/KakaoJwtToken.java
> +public class KakaoJwtToken {
원래는 refreshtoken만 저장해두고 accessToken은 계속 재발생하는 방법으로 이용합니다.

2024-07-26 13:50 UTC, ksy90101 commented on src/main/java/gift/DTO/KakaoJwtToken.java
> +public class KakaoJwtToken {
사용하는 데이터만 저장하는걸 추천드려요.

2024-07-26 13:50 UTC, ksy90101 commented on src/main/java/gift/KakaoLoginApi.java
> +      return kakaoJwtToken;
DTO를 이용해 처리하는게 좋았을거 같네요.
저기 body를 이용하면 가능할거 같기도 해요.

2024-07-26 13:50 UTC, ksy90101 commented on src/main/java/gift/Service/KakaoMemberService.java
> +    body.add("code", autuhorizationKey);
body도 api component에서 생성하는게 더 어울리는거 같아요.

2024-07-26 13:50 UTC, merged

2024-07-27 06:25 UTC, LeeTaek2T commented on src/main/java/gift/DTO/KakaoJwtToken.java
> +public class KakaoJwtToken {
네! 이후에 수정해보겠습니다!

2024-07-27 06:33 UTC, LeeTaek2T commented on src/main/java/gift/Service/KakaoMemberService.java
> +    body.add("code", autuhorizationKey);
네! 알겠습니다

2024-07-27 09:10 UTC, LeeTaek2T commented on src/main/java/gift/KakaoLoginApi.java
> +      return kakaoJwtToken;
만들어 놓고 이용을 안했었네요...ㅠㅠ
반영하겠습니다!