전남대 BE_박준형 5주차 과제(step1)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #110
Opened 2024-07-23 08:45 UTC by cliant

### 코드를 작성하면서 어려웠던 점

- api 요청 시간을 제한하기 위해 HttpComponentsHttpRequestFactory를 사용하였으나 예외가 지속되어 우선 주석 처리 해놓았습니다. 이 원인을 찾는데 어려움을 겪고있습니다.

### 코드 리뷰시 중점적으로 봐주셨으면 하는 부분

- api를 처음 사용하다보니 조금 더 생각해볼만한 부분 ( ex 현재 예외처리 방식, 응답 처리)이나 제가 생각하지 못한 부분들에 대해짚어주셨으면 합니다.

2024-07-25 04:54 UTC, dc-choi requested changes
구현상의 문제는 없어보입니다.

다만, 하단에 말씀드린거처럼 API Key가 그대로 노출되면 안됩니다.

자세한 내용은 하단 코멘트에 적어드렸습니다.

2024-07-25 04:54 UTC, dc-choi commented on src/main/resources/application-private.properties
> +kakao.api_key = 7ffbf75b2ad1d12e0fed29fae5b2cbac
api-key가 직접적으로 유출되는 것은 보안상의 위험이 있습니다. 해당 부분 삭제해주시고 재 발급 해주세요.

그리고 유출시키지 않는 방향으로 다시 올려주세요.

2024-07-25 04:54 UTC, dc-choi commented on src/main/java/gift/service/KakaoApiService.java
> +        ResponseEntity<String> response = client.post()
외부와 통신이 실패하는 경우 어떻게 되나요?

외부와 통신을 한다는 것은 기본적으로 실패의 여지가 있습니다. 이 부분에 대한 예외처리가 필요해보입니다.

kakao api 명세를 확인하시고 그에 맞게 예외처리를 해주세요.

2024-07-25 05:22 UTC, cliant commented on src/main/resources/application-private.properties
> +kakao.api_key = 7ffbf75b2ad1d12e0fed29fae5b2cbac
넵 .gitignore을 추가하여 숨겼습니다!

2024-07-25 06:33 UTC, cliant commented on src/main/java/gift/service/KakaoApiService.java
> +        ResponseEntity<String> response = client.post()
넵 응답 코드별로 예외 처리를 하도록 구현하였습니다!

2024-07-26 05:20 UTC, dc-choi approved these changes
피드백해주신대로 너무 잘 해주셨습니다! 수고하셨습니다!

다음 step2 과제도 파이팅입니다!

2024-07-26 05:20 UTC, merged