경북대 BE_배준호 5주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #113
Opened 2024-07-23 09:09 UTC by BaeJunH0

카카오 계정 로그인을 통해 인가 코드 발급
-> 해당 인가 코드를 이용하여 토큰 발급
-> 토큰을 이용하여 유저 정보 가져옴 ( Long 타입 kakao id )
-> 해당 id를 이용하여 유저 엔티티 객체 생성 및 저장 ( userId = id, email은 id@email.com, password는 랜덤한 값 )
-> 해당 유저 엔티티 객체 정보를 이용하여 기존 방식과 동일하게 jwt 토큰 발급
-> 클라이언트에게 해당 토큰 전달 및 이후에 헤더에 토큰 값을 넣어 사용자 인증

위와 같은 로직을 구현하였습니다, 피드백 부탁드려요!

2024-07-23 15:55 UTC, lsm7179 requested changes
준호님 과제하느라 고생하셨습니다.
간단한 피드백 남겼는데 반영해보시고 재요청주세요.
궁금하거나 어려운거 있으시면 언제든 DM주세요~!

2024-07-23 15:55 UTC, lsm7179 commented on src/main/java/gift/DTO/KakaoProperties.java
> +@ConfigurationProperties(prefix="kakao")
`@ConfigurationProperties`을 사용해주셨군요.👍 
`@Value`와 어떤 장단점이 있는지 알고계시면 좋을거 같네요.
https://mangkyu.tistory.com/207

2024-07-23 15:55 UTC, lsm7179 commented on src/main/java/gift/DTO/Token.java
> +    }
`setToken` 사용하지 않는 거같아요~
그리고 set는 지양해주세요.

2024-07-23 15:55 UTC, lsm7179 commented on src/main/java/gift/controller/KakaoLoginController.java
> +        url += "client_id=" + kakaoProperties.getClientId();
kakaoservice일때만 사용하는 url인거같은데 `kakaoservice`에서 받아보아요.
그리고 `https://kauth.kakao.com/oauth/authorize` 이부분도 프로퍼티로 만들어주세요.

2024-07-23 15:55 UTC, lsm7179 commented on src/main/java/gift/security/KakaoTokenProvider.java
> +        var url = "https://kauth.kakao.com/oauth/token";
해당 url은 프로퍼티로 만들어주세요.

2024-07-23 15:55 UTC, lsm7179 commented on src/main/java/gift/security/KakaoTokenProvider.java
> +        body.add("code", code);
private 메소드로 분리해보면 어떨까요?

2024-07-23 15:55 UTC, lsm7179 commented on src/main/java/gift/service/KakaoUserService.java
> +    }
`kakaoTokenProvider`의 역할로 보여지네요.

2024-07-23 15:55 UTC, lsm7179 commented on src/main/resources/application.properties
> +kakao.redirectUrl=http://localhost:8080
해당 id와 url은 노출하면 안됩니다. 
카카오에서 인가코드 삭제해주시고 다시 만들어 주세요.
```
앱 키, 인가 코드가 절대 유출되지 않도록 한다.
특히 시크릿 키는 GitHub나 클라이언트 코드 등 외부에서 볼 수 있는 곳에 추가하지 않는다.
```

2024-07-23 15:55 UTC, lsm7179 commented on src/main/java/gift/controller/KakaoLoginController.java
> +    }
카카오 호출 성공 실패에 대한 테스트코드가 필요할거같네요.
힌트: mockRestServer를 이용해보세요.
https://www.baeldung.com/restclienttest-in-spring-boot

2024-07-23 16:17 UTC, BaeJunH0 commented on src/main/java/gift/DTO/Token.java
> +    }
넵 알겠습니다

2024-07-23 16:32 UTC, BaeJunH0 commented on src/main/java/gift/controller/KakaoLoginController.java
> +        url += "client_id=" + kakaoProperties.getClientId();
반영 했습니다!

2024-07-23 16:34 UTC, BaeJunH0 commented on src/main/java/gift/security/KakaoTokenProvider.java
> +        var url = "https://kauth.kakao.com/oauth/token";
반영 했습니다!

2024-07-23 16:36 UTC, BaeJunH0 commented on src/main/java/gift/security/KakaoTokenProvider.java
> +        body.add("code", code);
반영했습니다

2024-07-23 16:40 UTC, BaeJunH0 commented on src/main/java/gift/service/KakaoUserService.java
> +    }
반영했습니다

2024-07-23 16:47 UTC, BaeJunH0 commented on src/main/resources/application.properties
> +kakao.redirectUrl=http://localhost:8080
반영했습니다

2024-07-24 02:58 UTC, lsm7179 approved these changes
준호님 과제 수고하셨습니다.
피드백 드린건 다음단계에서 꼭 반영해주세요.

2024-07-24 02:58 UTC, merged