경북대 BE_김동현 5주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #122
Opened 2024-07-23 11:45 UTC by donghyuun

2024-07-24 13:29 UTC, MangKyu requested changes
안녕하세요 동현님! 이번 5주차 과제는 드디어 네트워크 연동 부분이군요ㅎㅎ
처음 네트워크 연동을 하게 되면 새로운 개념도 많이 등장하고, 부가적인 도구도 활용해야 하면서 어려운 부분이 많습니다! 어려운 부분 생기면 편하게 질문주시고, 이번에도 화이팅해보시죠 🔥🔥🔥
머지 컨플릭을 최소화하기 위해 3~4주차 전에는 가급적 승인하고 이후에 변경 요청을 해드리고 있었는데요, 지금 변경을 잡고 가지 않으면 이후에 어려움이 더 많을 것 같아서 변경하고 넘어가면 좋을 것 같습니다! 수정하고 넘어가시죠ㅎㅎ
추가적으로 질문주신 부분에 대해서도 답변드리겠습니다!

### 소셜 로그인 이력 관리
소셜 로그인의 경우도 자체 테이블에 관리가 필요합니다! 이를 통해 우리 서비스의 이용자 규모나 가입 일자 등의 고객 정보들을 추가적으로 접근할 수 있습니다ㅎㅎ

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/domain/cartItem/CartItemRestController.java
> -import org.springframework.data.domain.Page;
미사용 import 정리 💯

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/domain/cartItem/CartItemService.java
> +    public List<CartItemDTO> getProductsInCartByUserIdAndPageAndSort(Long userId, int page,
여기는 자동 정렬 때문에 오히려 깨진 것 같네요ㅎㅎ 천천히 확인해주세요!

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/domain/option/JpaOptionRepository.java
> +    @Query("SELECT o FROM Option o WHERE o.id = :id")
요건 굳이 `@Query` 안쓰셔도 될 것 같아요~!
메서드 네이밍으로 잠금을 표현하려는 의도 좋네요!
```suggestion
    Optional<Option> findByIdForUpdate(@Param("id") Long id)
```

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/domain/option/JpaOptionRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
Lock 애노테이션을 활용한 부분 👍

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/domain/option/dto/OptionRequestDTO.java
> +    @Max(value = 999_999_999L, message = "옵션 수량은 최대 1억개 미만입니다.")
크 정리하시는 부분 너무 좋습니다!

2024-07-24 13:29 UTC, MangKyu commented on src/main/resources/application.properties
> +spring.config.import=application-key.properties
저는 별도로 key를 위한 프로퍼티를 분리하지는 않긴 합니다!
참고로 실무에서는 시크릿 관리를 위한 별개의 저장소가 사용됩니당ㅎㅎ 그냥 참고차 알고계시면 좋을 것 같아섯 공유드려요!

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/global/exception/ErrorCode.java
> +    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
우리가 코드를 다른 개발자들과 같이 쓰다보니까, 제 개인적으로는 400 -> 500 순차적으로 정렬되는게 관리가 용이했던 것 같습니다ㅎㅎ

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/domain/user/dto/kakao/KaKaoToken.java
> +public record KaKaoToken(
record 클래스 활용 👍

2024-07-24 13:29 UTC, MangKyu commented on src/test/java/gift/Product/ProductTest.java
> +public class ProductTest {
Product는 우리의 비즈니스를 담당하는 클래스이며 스프링 컨테이너(`@DataJpaTest` 기반의 테스트)가 굳이 필요없을 것 같아요! 단순히 POJO (단순한 Product 클래스 생성)형태의 테스트로 작성하면 더욱 좋을 것 같네요!

스프링 컨테이너를 활용하면 전체적인 테스트의 성능에 영향을 줄 수 있으므로, 가능하다면 단위 테스트로 작성하는 것이 좋을 것 같습니다ㅎㅎ

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/domain/user/User.java
> +    private UserRole role;
그냥 궁금하여 질문드립니당ㅎㅎ 갑자기 Role을 도입하시게 된 이유가 무엇인가요~?

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/domain/user/UserController.java
> +    @Value("${kakao.client.id}")
해당 값들은 하나의 단어를 의미하여 일반적으로 다음과 같이 표현합니다!
```suggestion
    @Value("${kakao.client-id}")
    private String clientId; // 카카오 개발자 콘솔에서 발급받은 클라이언트 ID
    @Value("${kakao.redirect-url}")
    private String redirectUri; // 카카오 로그인 후 리다이렉트될 URI
```

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/domain/user/UserController.java
> +        String url = String.format("%s?client_id=%s&redirect_uri=%s&response_type=%s",
다음과 같이 작성하는 방법도 있습니다ㅎㅎ
```java
String url = UriComponentsBuilder.fromHttpUrl(KAKAO_AUTH_URL)
                .queryParam("client_id", clientId)
                .queryParam("redirect_uri", redirectUri)
                .queryParam("response_type", RESPONSE_TYPE)
                .build()
                .toUriString();
```

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/domain/user/UserRestController.java
> +    @GetMapping("/kakaoLogin")
RESTful한 API 규칙에서는 다음과 같이 작성하는 것을 [권장](https://blog.restcase.com/5-basic-rest-api-design-guidelines/)합니다! 대소문자를 활용할 경우 혼란이 가중되어서요ㅎㅎ
```suggestion
    @GetMapping("/kakao-login")
```

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/domain/user/UserRestController.java
> +        if (authorizedCode != null) {
요거 근데 일반적으로 카카오 로그인 시도 시에 code가 null이면 안될 것 같은데, 이렇게 처리하신 이유가 있을까요~?

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/domain/user/KaKaoUserService.java
> +        RestTemplate restTemplate = new RestTemplate();
RestTemplate 객체를 매 요청마다 생성하는 것은 성능 및 리소스 관리 측면에서 비효율적이라서, 빈으로 등록 후 사용할 것을 권장합니다! 참고로 스프링은 [RestTemplateBuilder](https://www.baeldung.com/spring-rest-template-builder)를 미리 bean으로 등록해두어서, 해당 빈을 주입받고 설정을 통해 ResTemplate 빈을 생성하는 구조로 작성하길 권장합니다!

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/domain/user/KaKaoUserService.java
> +        var body = new LinkedMultiValueMap<String, String>();
LinkedMultiValueMap은 스프링이 구현한 자료구조인데요, 기존의 Map 자료구조와 무엇이 다를지 한번 학습해보시면 좋을 것 같습니다:)

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/domain/user/KaKaoUserService.java
> +                ObjectMapper objectMapper = new ObjectMapper();
ObjectMapper 역시 스프링이 등록해둔 bean이 있어서, 의존관계 주입을 받아서 사용하면 됩니다!
참고로 ObjectMapper는 정말 무거운 객체라 매번 만들고 GC되고 하는 것이 상당히 비효율적입니다ㅎㅎ

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/domain/user/KaKaoUserService.java
> +                JsonNode rootNode = objectMapper.readTree(response.getBody());
반환되는 타입을 String -> ObjectMapper로 변환하는 것이 아니라 `KaKaoToken` 타입으로 하면 어떨까요~?

2024-07-24 13:29 UTC, MangKyu commented on src/main/java/gift/domain/user/KaKaoUserService.java
> +        headers.add("Content-Type", "application/x-www-form-urlencoded;charset=utf-8");
```suggestion
        headers.add("Content-Type", MediaType.APPLICATION_FORM_URLENCODED_VALUE);
```

2024-07-25 05:31 UTC, donghyuun commented on src/main/java/gift/domain/cartItem/CartItemService.java
> +    public List<CartItemDTO> getProductsInCartByUserIdAndPageAndSort(Long userId, int page,
넵 수정했습니다!

2024-07-25 05:32 UTC, donghyuun commented on src/main/java/gift/domain/option/JpaOptionRepository.java
> +    @Query("SELECT o FROM Option o WHERE o.id = :id")
앗 왜 저렇게 했었을까요.. 수정했습니다!

2024-07-25 05:33 UTC, donghyuun commented on src/main/resources/application.properties
> +spring.config.import=application-key.properties
넵 ㅎㅎ 공유 감사합니다!

2024-07-25 05:36 UTC, donghyuun commented on src/main/java/gift/global/exception/ErrorCode.java
> +    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
오오 꿀팁인 것 같습니다! 감사합니다!

2024-07-25 05:41 UTC, donghyuun commented on src/test/java/gift/Product/ProductTest.java
> +public class ProductTest {
넵 스프링 컨테이너를 사용하지 않도록 수정하였습니다! 감사합니다 :)

2024-07-25 05:42 UTC, donghyuun commented on src/main/java/gift/domain/user/User.java
> +    private UserRole role;
관리자와 일반 유저를 구분하는 것이 좋다고 생각되어 일단 역할을 도입했는데, 이 부분을 신경 쓸 여유가 없는 것 같습니다..ㅎㅎ

2024-07-25 05:44 UTC, donghyuun commented on src/main/java/gift/domain/user/UserController.java
> +    @Value("${kakao.client.id}")
이 부분이 저도 미묘하게 신경쓰였습니다. . 으로 구분하시는 분도 계시고 - 로 구분하시는 분도 계셨는데
덕분에 올바른 표기법에 대해 알게 되었습니다. 감사합니다!

2024-07-25 05:47 UTC, donghyuun commented on src/main/java/gift/domain/user/UserController.java
> +        String url = String.format("%s?client_id=%s&redirect_uri=%s&response_type=%s",
헉 스프링이 이런 것까지 지원하는군요 꿀팁 감사합니다!!

2024-07-25 05:49 UTC, donghyuun commented on src/main/java/gift/domain/user/UserRestController.java
> +    @GetMapping("/kakaoLogin")
앞으로 많이 사용될 것 같습니다. 꿀팁 정말 감사합니다!!

2024-07-25 06:00 UTC, donghyuun commented on src/main/java/gift/domain/user/UserRestController.java
> +        if (authorizedCode != null) {
![image](https://github.com/user-attachments/assets/8f10fa03-c49a-4618-bc4c-c41dde30d4d6)
사용자는 카카오 로그인 동의/취소 모두 동일 url 로 리다이렉트하게 되는데,
사용자가 카카오 로그인을 중간에 취소할 시 code 값이 들어오지 않고, error 값이 들어오게 됩니다.
그래서 code 가 null 이 아닌지 확인하는 과정을 추가했습니다!

2024-07-25 06:05 UTC, donghyuun commented on src/main/java/gift/domain/user/KaKaoUserService.java
> +        RestTemplate restTemplate = new RestTemplate();
넵 생성자 주입으로 Builder 주입 후, build() 로 사용하는 방식으로 수정했습니다!

2024-07-25 06:07 UTC, donghyuun commented on src/main/java/gift/domain/user/KaKaoUserService.java
> +                ObjectMapper objectMapper = new ObjectMapper();
스프링이 무슨 Bean 을 등록했는지 알고 있는게 중요한 것 같습니다.. ㅎㅎ, 말씀 감사합니다 수정했습니다!

2024-07-25 06:07 UTC, donghyuun commented on src/main/java/gift/domain/user/KaKaoUserService.java
> +        var body = new LinkedMultiValueMap<String, String>();
넵 알겠습니다!

2024-07-25 06:16 UTC, donghyuun commented on src/main/java/gift/domain/user/KaKaoUserService.java
> +                JsonNode rootNode = objectMapper.readTree(response.getBody());
![image](https://github.com/user-attachments/assets/32a59b13-47a4-40ed-8ea8-73ba52d26b96)
현재 반환되는 값에서 엑세스&리프레시 토큰만을 추출하고 있습니다.
말씀하시는 부분은 위 전체 값을 KaKaoToken 으로 받아올 수 있도록 KaKaoToken 의 필드를 수정하는게 낫다는 말씀이신건가요?!

2024-07-25 06:17 UTC, donghyuun commented on src/main/java/gift/domain/user/KaKaoUserService.java
> +        headers.add("Content-Type", "application/x-www-form-urlencoded;charset=utf-8");
꿀팁 감사합니다 :)

2024-07-25 11:27 UTC, donghyuun commented
**수정 사항**
- 카카오 로그인 관련 컨트롤러, 서비스 파일 분리
- 메서드 추출하여 메서드 부피 간소화
- @ConfigurationProperties 를 통한 개인 정보 사용
- 기타 리팩토링

기존에 UserController,Service 에서 수행했던 카카오 로그인 로직을 KaKaoController, Service 로 빼서 구현했습니다. 이렇게 하니 안복잡하고 좋은 것 같습니다.

그 외에, 기존 메서드 작성 방식이 줄바꿈도 많고, 부피도 컸는데 세부 기능들을 메서드 추출해서 작성하니 가독성이 높아진 것 같습니다. 그리고 줄바꿈도 줄여봤는데 훨씬 나은 것 같습니다ㅎㅎ

카카오 로그인에서 가장 헷갈렸던 게, 기존 일반 로그인의 경우는 로그인을 요청하는 API 가 있어서, 해당 요청에 대해 응답으로 JWT 를 반환하면 됐었는데,

카카오 로그인의 경우는 카카오 로그인 성공 시 지정한 URL 로 리다이렉트 하게 되는데, 이곳에서 JWT 를 생성해도 이걸 어떻게 클라이언트로 보내야 하는지 몰랐습니다. 

아래 코드가 카카오 로그인 성공 시 이동하게 된 URL 에 매핑되는 컨트롤러인데, 클라이언트의 요청이 아니라 자체 리다이렉트라 JWT 를 반환하는 방법이 다시 "/" 로 리다이렉션하는 방법밖에 없었습니다.
```
GetMapping("/kakaoLogin")
    public ResponseEntity<SimpleResultResponseDto> kakaoLogin(
        @RequestParam(value = "code", required = false) String authorizedCode, // 없으면 null
        @RequestParam(value = "error", required = false) String error // 없으면 null
    ) {
        if (authorizedCode != null) {
            KaKaoToken kaKaoToken = kaKaoUserService.getKaKaoToken(authorizedCode);

            User findUser = kaKaoUserService.findUserByKaKaoAccessToken(kaKaoToken.accessToken());

            String jwt = JwtProvider.generateToken(findUser);
            System.out.println("jwt = " + jwt);

            ResponseCookie jwtCookie = ResponseCookie.from("jwt", jwt)
                .httpOnly(true)
                .path("/")
                .build();

            return ResponseEntity.status(HttpStatus.FOUND)
                .header(HttpHeaders.SET_COOKIE, jwtCookie.toString())
                .header(HttpHeaders.LOCATION, "/")
                .build();

        }
        return ResponseEntity.status(HttpStatus.FOUND)
            .header(HttpHeaders.LOCATION, "/")
            .build();
    }
```

그래서 찾아봤는데, 카카오 로그인 성공 후 리다이렉트 되는 주소를 로그인 페이지로 두고, 아래 로그인 페이지 내 window.load 메서드를 통해 authorizedCode 를 추출하고, 서버로 이걸 통해 jwt 를 발급 받는게 나을 것 같다고 생각했습니다.
```  
<script>
  window.onload = function () {
    const urlParams = new URLSearchParams(window.location.search);
    const code = urlParams.get('code');
    if (code) {
      // 서버로 인가 코드 전송
      axios.post('/api/users/oauth/kakao/callback', {
        code: code
      })
      .then(function (response) {
        // JWT 토큰을 로컬 스토리지에 저장
        localStorage.setItem('jwt', response.data);
        // 메인 페이지로 리다이렉트
        window.location.href = '/';
      })
      .catch(function (error) {
        console.error('Error:', error);
        alert('카카오 로그인 처리에 실패했습니다.');
      });
    }
  };
</script>
```

그래서 기존에 홈화면으로 jwt 와 함께 리다이렉트 했던 것을 RESTFUL 하게 바꿀 수 있었습니다!

2024-07-25 17:35 UTC, donghyuun commented on src/main/java/gift/domain/option/JpaOptionRepository.java
> +    @Query("SELECT o FROM Option o WHERE o.id = :id")
잠금이 필요한 경우에 한해 사용되는 findByIdForUpdate 쿼리메서드가 findById 기능을 자동 지원하지 않아 @Query 를 사용하여 쿼리를 작성했는데 @Query 를 쓰지 않으면 저 부분을 어떻게 해야 할까요..?!

2024-07-26 13:44 UTC, MangKyu approved these changes
1주차 주차 과제 고생 많으셨습니다! 리뷰 남겨드린 부분들 전반적으로 잘 반영해주신 것 같고, 과제 잘 진행하고 계신 것 같습니다! 다음주차 과제도 화이팅해보시죠ㅎㅎ 🔥🔥🔥

2024-07-26 13:44 UTC, MangKyu commented on src/main/java/gift/Application.java
> +@ConfigurationPropertiesScan
ConfigurationProperties의 활용 👍

2024-07-26 13:44 UTC, MangKyu commented on src/main/java/gift/domain/cartItem/CartItemService.java
> -import gift.global.exception.BusinessException;
import 정리 👍

2024-07-26 13:44 UTC, MangKyu commented on src/main/java/gift/domain/option/JpaOptionRepository.java
> +    @Query("SELECT o FROM Option o WHERE o.id = :id")
요렇게 사용하면 되지 않을까요!?
```java
@Lock(LockModeType.PESSIMISTIC_WRITE)
Optional<Option> findById(@Param("id") Long id);
```

2024-07-26 13:44 UTC, MangKyu commented on src/main/java/gift/domain/user/kakao/KaKaoController.java
> +        return new RedirectView(kaKaoService.buildLoginPageUrl());
RedirectView 활용 👍

2024-07-26 13:44 UTC, MangKyu commented on src/test/java/gift/Product/ProductTest.java
> +@Transactional
요 두 애노테이션도 뺄 수 있을 것 같네요ㅎㅎ
```suggestion


```

2024-07-26 13:44 UTC, MangKyu commented on src/main/java/gift/domain/user/kakao/KaKaoService.java
> +        this.restTemplate = restTemplateBuilder.build();
현재 코드로는 timeout(readtimeout, sockettimeout, connectiontimeout 등)이 설정되지 않은 것으로 보이는데요~ 이를 설정하지 않으면 어떤 문제가 생길지 보시고 설정하면 좋을 것 같습니다ㅎㅎ [관련 링크](https://mangkyu.tistory.com/256) 남겨드릴께요!

2024-07-26 13:44 UTC, MangKyu commented on src/main/java/gift/domain/user/kakao/KaKaoService.java
> +        if (response.getStatusCode() == HttpStatus.OK) {
이렇게하면 조금 코드 읽기가 쉬워지겠네요!
```java
if (response.getStatusCode() == HttpStatus.OK) {
    return parseTokenResponse(response);
} 

throw new BusinessException(ErrorCode.FORBIDDEN, "사용자 권한이 없습니다.");
```

2024-07-26 13:45 UTC, merged

2024-07-26 17:29 UTC, MangKyu commented on src/main/java/gift/domain/user/KaKaoUserService.java
> +                JsonNode rootNode = objectMapper.readTree(response.getBody());
앗 아뇨! 만약 그렇다면 필요한 부분만 받도록 클래스를 선언하면 되지 않을까 해서 드린 코멘트였습니다ㅎㅎ