부산대 BE_박수빈 5주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #124
Opened 2024-07-23 11:48 UTC by kuma4188

카카오 로그인 API만 따로 파일을 만들어서 구현하게 되면 크게 어렵지 않았던것 같습니다.
하지만 이때까지 제가 작성한 코드에 탑재를 하려고 하니 어려웠던것 같습니다.
과제 요구 사항에서 사용자에 대한 권한을 부여해도 되는지 안되는지에 대한 언급이 없어서 ,
사용자의 nickname만 받아서 사용하도록 코드를 만들어봤습니다.
또 카카오톡 메시지 보내기 api를 허용하라고 해서 정상 로그인 하면 카카오톡 메시지를 보내도록 코드를 작성해 보았습니다.

2024-07-23 15:42 UTC, deactivated-user requested changes
step1 고생하셨습니다!
리뷰 코멘트 확인 부탁드려요

2024-07-23 15:42 UTC, deactivated-user commented on src/main/resources/application.yml
> +  client-id: 0c05fb1058c786778f09bb4d2bc0151c
여기 key가 그대로 노출되고 있어요..!
api key 정보는 이렇게 깃허브에 올라가면 안됩니다. 삭제 후 재발급해주세요!
(특히나 유료 api key가 깃허브에 유출될 경우 해커에 의해 과금 폭탄을 맞을 수 있습니다.)
재발급하신 key 정보를 별도의 파일로 관리하고, 해당 파일을 gitignore에 포함시키는 방식으로 구현하시면 될 것 같습니다.

2024-07-23 15:42 UTC, deactivated-user commented on src/main/java/gift/controller/web/KakaoLoginController.java
> +        RestTemplate restTemplate = new RestTemplate();
카카오 API 호출 부분을 별도의 서비스 클래스(KakaoApiService)로 분리하는 것이 좋습니다.

2024-07-23 15:42 UTC, deactivated-user commented on src/main/java/gift/controller/web/KakaoLoginController.java
> +            System.out.println("Message sent successfully");
System.out.println()을 사용하고 있는데, 로깅 프레임워크(예: SLF4J)를 사용하는 것이 좋습니다!

2024-07-23 15:42 UTC, deactivated-user commented on src/main/java/gift/controller/web/KakaoLoginController.java
> +        ResponseEntity<Map> userInfoResponse = restTemplate.exchange("https://kapi.kakao.com/v2/user/me", HttpMethod.GET, userInfoRequest, Map.class);
API URL, 파라미터 이름 등을 상수로 정의해볼까요? 
상수를 사용하면 코드의 가독성과 유지보수성이 좋아집니다.

2024-07-23 15:42 UTC, deactivated-user commented on src/main/java/gift/controller/web/KakaoLoginController.java
> +        RestTemplate restTemplate = new RestTemplate();
RestTemplate을 빈으로 등록하면 좋을 것 같습니다!
외부 api는 보통 여러 개를 연동하는데 빈으로 등록해두면 애플리케이션 전체에서 동일한 설정으로 api 클라이언트를 만들 수 있고 중복 코드도 줄일 수 있습니다.

```java
@Configuration
public class RestTemplateConfig {

    @Bean
    public RestTemplate restTemplate(RestTemplateBuilder builder) {
        return builder
            .setConnectTimeout(Duration.ofSeconds(...))
            .setReadTimeout(Duration.ofSeconds(...))
            .build();
    }
}
```
- Connection timeout vs Read timeout: https://alden-kang.tistory.com/20 참고
```java
@Service
public class ExternalApiService {
    private final RestTemplate restTemplate;
    private final KakaoProperties kakaoProperties;
    private final String baseUrl = "https://kauth.kakao.com/oauth";

    public ExternalApiService(RestTemplate restTemplate, KakaoProperties kakaoProperties) {
        this.restTemplate = restTemplate;
        this.kakaoProperties = kakaoProperties;
    }
...
```

2024-07-23 15:42 UTC, yoo-jaein commented on src/main/java/gift/controller/web/KakaoLoginController.java
> +        RestTemplate restTemplate = new RestTemplate();
현재 클라이언트에 타임아웃 설정이 명시적으로 되어있지 않네요.
타임아웃을 설정하지 않으면 서버 응답이 없을 때 애플리케이션이 무한히 기다려야 합니다.
그렇게 되면 앱 리소스(스레드, 메모리..)를 계속 점유하게 되어서 시스템 성능 저하가 발생합니다.

2024-07-23 15:42 UTC, deactivated-user commented on src/main/java/gift/controller/web/KakaoLoginController.java
> +        ResponseEntity<Map> response = restTemplate.postForEntity("https://kauth.kakao.com/oauth/token", request, Map.class);
Map보다 구체적인 DTO를 반환하는 것이 더 좋을 것 같습니다!

2024-07-23 15:42 UTC, deactivated-user commented on src/main/java/gift/controller/web/KakaoLoginController.java
> +            "https://kauth.kakao.com/oauth/authorize?client_id=%s&redirect_uri=%s&response_type=code&scope=profile_nickname,talk_message",
UriComponentsBuilder를 사용해서 url을 구성하면 더 안전하게 코드를 작성할 수 있습니다!
- https://2carrot84.github.io/development/uri-component-builder/ 참고

```java
String fullUrl = UriComponentsBuilder.fromHttpUrl(baseUrl)
    .path( .... )
```

2024-07-23 15:42 UTC, yoo-jaein commented on src/main/java/gift/controller/web/KakaoLoginController.java
> +        HttpEntity<MultiValueMap<String, String>> request = new HttpEntity<>(params, headers);
requestBody를 생성하는 부분을 별도의 private 메서드로 추출하면 코드가 가벼워질 것 같아요!

2024-07-23 15:42 UTC, yoo-jaein commented on src/main/java/gift/controller/web/KakaoLoginController.java
> +        RestTemplate restTemplate = new RestTemplate();
카카오 api 클라이언트에 대한 테스트 코드도 있으면 좋을 것 같아요.

2024-07-23 15:42 UTC, yoo-jaein commented on src/main/java/gift/controller/web/KakaoLoginController.java
> +    @Value("${kakao.client-id}")
👍

2024-07-23 15:42 UTC, yoo-jaein commented on src/main/java/gift/controller/web/KakaoLoginController.java
> +        Map<String, Object> userInfo = userInfoResponse.getBody();
가능하면 Map을 사용하지 말아 주세요!

2024-07-24 11:21 UTC, kuma4188 commented
수정사항>
1. API-KEY.propertise 만들고 gitignore에서 키 관리 
2.  controller , service , serviceImpl로 구분
3. 로깅 프레임워크 사용
4. 상수 정의
5.  RestTemplate을 빈으로 등록
6. 타임아웃 설정
7. UriComponentsBuilder 사용


실무에서 사용하는 잘 만들어진 API를 제가 만든 허술한 코드에 탑재하려고 하니
수정할게 많네요....ㅎㅎ 
코드리뷰 감사합니다!

2024-07-24 12:58 UTC, yoo-jaein approved these changes
리뷰 반영된 것 확인했습니다!
조금씩 로직이 탄탄해지고 있네요~

추가 코멘트는 읽어보시고 다음 단계에 반영해주세요!
머지하겠습니다 :)

2024-07-24 12:58 UTC, yoo-jaein commented on src/main/resources/application.yml
> +    import: ./API-KEY.properties
👍

2024-07-24 12:58 UTC, yoo-jaein commented on src/main/java/gift/dto/Response/AccessTokenResponse.java
> +    private String access_token;
Jackson 라이브러리를 사용하면 Json 응답의 필드명과 자바 클래스 필드명을 다르게 설정할 수 있습니다!
```java
    @JsonProperty("access_token")
    private String accessToken;
```
- https://dev-jwblog.tistory.com/120 참고

2024-07-24 12:58 UTC, yoo-jaein commented on src/main/java/gift/controller/web/KakaoLoginController.java
> +    @GetMapping("/")
("/") 은 생략 가능합니다

2024-07-24 12:58 UTC, yoo-jaein commented on src/main/java/gift/controller/web/KakaoLoginController.java
> +    public void redirectToKakao(HttpServletResponse response) throws IOException {
IOException를 try-catch 블록으로 처리하고 적절한 에러 응답을 보내는 것이 좋을 것 같아요

2024-07-24 12:58 UTC, yoo-jaein commented on src/main/java/gift/controller/web/KakaoLoginController.java
> +    public void redirectToKakao(HttpServletResponse response) throws IOException {
try-catch에서 로깅을 추가하면 디버깅이 편해질 것 같아요!

2024-07-24 12:58 UTC, yoo-jaein commented on src/main/java/gift/service/KakaoLoginServiceImpl.java
> +
메서드마다 restTemplate()을 호출하는 대신
```java
private final RestTemplate restTemplate;
```
restTemplate을 필드로 주입받아서 재사용하면 효율적일 것 같습니다

2024-07-24 12:58 UTC, yoo-jaein commented on src/main/java/gift/service/KakaoLoginServiceImpl.java
> +            logger.error("Failed to get access token: {}", response.getStatusCode());
로깅 👍

2024-07-24 12:58 UTC, yoo-jaein commented on src/main/java/gift/service/KakaoLoginServiceImpl.java
> +        params.add("template_object", String.format("{\"object_type\":\"text\",\"text\":\"%s님이 Spring-gift-order에 로그인했습니다.\",\"link\":{\"web_url\":\"http://localhost:8080\",\"mobile_web_url\":\"http:
json 문자열을 직접 생성하는 대신 객체를 사용하고 Jackson 라이브러리로 직렬화하는 것이 안전합니다! 👀
- https://tychejin.tistory.com/134 참고

2024-07-24 12:58 UTC, yoo-jaein commented on src/main/java/gift/controller/web/KakaoLoginController.java
> +            if (nickname != null) {
if 블록을 별도 메서드로 추출하면 가독성이 향상될 것 같습니다!

2024-07-24 12:58 UTC, yoo-jaein commented on src/main/java/gift/controller/web/KakaoLoginController.java
> +    @Autowired
가급적 생성자 주입을 사용해주세요!

2024-07-24 12:58 UTC, merged