경북대 BE_박한솔 5주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #127
Opened 2024-07-23 13:04 UTC by pjhcsols

템플릿으로 카카오 서버에 code 요청 기능 클라이언트 화면 구현

로그인 요청 처리 및 액세스 토큰 요청:
클라이언트에서 카카오 로그인 요청을 받으면, 카카오 로그인 API에 인가 코드(authorization code)를 발급하는 기능 구현
인가 코드를 서버에 전송하면 (/login) WAS 서버에서 엑세스 토큰을 카카오 서버에 요청해서 받아옴
code로 서버에 /login 요청

사용자 정보 조회 및 엑세스 토큰 발급

액세스 토큰을 사용한 사용자 정보 조회:
받은 액세스 토큰을 이용해 카카오 사용자 정보를 조회합니다. 이를 위해 카카오의 사용자 정보 조회 API를 호출합니다.
이 단계에서는 액세스 토큰을 HTTP 헤더에 포함시켜 API 요청을 보내고, 카카오 서버로부터 사용자의 정보(예: 닉네임, 이메일 등)를 반환받습니다.
카카오 개인 정보를 받을수있다면 추후에 작성 예정인 카카오 정보를 받아와서 사용자 정보가 있다면 로그인 없다면 회원가입을 진행시킵니다.

사용자 정보 및 액세스 토큰 반환:
최종적으로 클라이언트에게 액세스 토큰과 함께 사용자 정보를 반환하는 API 엔드포인트를 구현합니다.
클라이언트는 이 정보를 이용해 사용자 세션을 생성하거나, 필요에 따라 사용자 정보를 저장하고 활용할 수 있습니다.

2024-07-23 16:10 UTC, lsm7179 requested changes
한솔님 과제 수고하셨습니다.
몇몇 코멘트 남겼는데 반영 후 재요청주세요😁
궁금하거나 어려운거 있으시면 언제든 DM주세요~!

2024-07-23 16:10 UTC, lsm7179 commented on src/main/java/gift/controller/kakao/AdminKakaoController.java
> +@EnableConfigurationProperties(KakaoProperties.class)
해당 어노테이션이 `controller`계층에 있는건 적절하지 않는거 같네요.
그리고 별도 config 패키지가 있다면 거기에 적용하거나 application에 해주시는게 어떨까요?
https://mangkyu.tistory.com/191 이걸 적용해도 좋을거 같네요.

2024-07-23 16:10 UTC, lsm7179 commented on src/main/java/gift/controller/kakao/KakaoController.java
> +    private KakaoProperties kakaoProperties;
생성자 주입을 사용해보아요.

2024-07-23 16:10 UTC, lsm7179 commented on src/test/java/gift/kakao/RestClientTest.java
> +}
`KakaoProperties` 이미 main에 클래스가 있는데 또 만들필요가 있나요?

2024-07-23 16:10 UTC, lsm7179 commented on src/test/java/gift/kakao/RestClientTest.java
> +    private KakaoProperties kakaoProperties;
실무에서 cd/ci를 적용하면 네트워크 방화벽 허용이 안되어 테스트가 안될 수 있습니다.

어떻게 분리해서 테스트 해볼수있을까요?
mockRestServer를 이용해보아요.
https://www.baeldung.com/restclienttest-in-spring-boot

성공,실패 테스트가 필요해보이네요.

2024-07-23 16:10 UTC, lsm7179 commented on src/main/resources/application.properties
> +kakao.client-id=
https://velog.io/@crow/Spring-boot-%EC%99%B8%EB%B6%80-%ED%99%98%EA%B2%BD%EB%B3%80%EC%88%98-%EC%A3%BC%EC%9E%85

이렇게 적용해보아요.

2024-07-23 16:10 UTC, lsm7179 commented on src/main/java/gift/controller/kakao/KakaoController.java
> +    }
`Controller`계층에서 이렇게 비즈니스로직을 사용해도 될까요?😨
적절한 계층을 나누고 provider 또는 component를 만들어주세요.

2024-07-24 00:23 UTC, pjhcsols commented on src/main/java/gift/controller/kakao/AdminKakaoController.java
> +@EnableConfigurationProperties(KakaoProperties.class)
@EnableConfigurationProperties의 증가를 막기 위해 @ConfigurationPropertiesScan 어노테이션은 패키지를 기반으로 @ConfigurationProperties가 등록된 클래스들을 찾아 값들을 주입하고 빈으로 등록하게 하였습니다!!

2024-07-24 00:24 UTC, pjhcsols commented on src/test/java/gift/kakao/RestClientTest.java
> +}
테스팅을 먼저하여 제작하게 되었습니다. 해당 기능 제거하겠습니다 !!

2024-07-24 00:27 UTC, pjhcsols commented on src/main/java/gift/controller/kakao/KakaoController.java
> +    private KakaoProperties kakaoProperties;
해당 기능 변경하였습니다

2024-07-24 02:04 UTC, pjhcsols commented on src/test/java/gift/kakao/RestClientTest.java
> +    private KakaoProperties kakaoProperties;
실제 네트워크 요청 없이도 RESTful API 호출을 모의하여 테스트하게 변경하였습니다!!

2024-07-26 01:15 UTC, pjhcsols commented on src/main/resources/application.properties
> +kakao.client-id=
변경하였습니다!!

2024-07-26 01:22 UTC, pjhcsols commented on src/main/java/gift/controller/kakao/KakaoController.java
> +    }
kakao 비즈니스 로직과 컨트롤러 계층 분리 하였습니다!!

2024-07-26 09:17 UTC, lsm7179 approved these changes
한솔님 과제 수고하셨습니다.
피드백 남겼는데 다음단계에서 같이 반영해주세요.
화이팅입니다~!

2024-07-26 09:17 UTC, lsm7179 commented on src/main/java/gift/controller/kakao/KakaoController.java
> +
불필요한 주석은 삭제해주세요😁

2024-07-26 09:17 UTC, lsm7179 commented on src/main/java/gift/service/kakao/KakaoService.java
> +        String tokenUrl = "https://kauth.kakao.com/oauth/token";
Properties에 있어도 될거 같네요~

2024-07-26 09:17 UTC, lsm7179 commented on src/main/java/gift/service/kakao/KakaoService.java
> +        body.add("code", authorizationCode);
private 메소드로 도출해보세요.

2024-07-26 09:17 UTC, lsm7179 commented on src/main/java/gift/service/kakao/KakaoService.java
> +public class KakaoService {
userService 와 kakaoService 역할이 혼재되어 있는거 같아요.
역할에 맞게 나누는게 필요해보입니다.

2024-07-26 09:17 UTC, lsm7179 commented on src/main/java/gift/service/user/UserService.java
> +     */
불필요한 주석은 삭제해주세요😨

2024-07-26 09:17 UTC, lsm7179 commented on src/main/java/gift/service/kakao/KakaoService.java
> +            return userInfo;
이부분은 userService가 책임져도 될거 같네요.

2024-07-26 09:17 UTC, lsm7179 commented on src/main/java/gift/service/user/UserService.java
> +        } else {
orElseGet을 사용해보아요~
https://stir.tistory.com/140

2024-07-26 09:17 UTC, lsm7179 commented on src/test/java/gift/kakao/RestClientTest.java
> +public class RestClientTest {
👍

2024-07-26 09:17 UTC, merged

2024-07-28 05:09 UTC, pjhcsols commented on src/main/java/gift/controller/kakao/KakaoController.java
> +
넵!! 확인하였습니다.

2024-07-28 05:32 UTC, pjhcsols commented on src/main/java/gift/service/kakao/KakaoService.java
> +        String tokenUrl = "https://kauth.kakao.com/oauth/token";
Properties를 통해 url을 전부 정리하였습니다.

2024-07-28 05:46 UTC, pjhcsols commented on src/main/java/gift/service/kakao/KakaoService.java
> +        body.add("code", authorizationCode);
private 메소드로 createTokenRequestBody를 도출하였습니다.

2024-07-28 05:59 UTC, pjhcsols commented on src/main/java/gift/service/kakao/KakaoService.java
> +public class KakaoService {
KakaoService는 Kakao API와의 통신, 로그인, 주문 생성 및 메시지 발송을 담당.
UserService는 사용자 정보의 생성 및 관리, JWT 토큰 생성 및 검증을 담당. 하도록 변경하였습니다

2024-07-28 06:12 UTC, pjhcsols commented on src/main/java/gift/service/user/UserService.java
> +     */
넵 추후 step3에서 정리하겠습니다.

2024-07-28 06:13 UTC, pjhcsols commented on src/main/java/gift/service/kakao/KakaoService.java
> +            return userInfo;
userService가 책임지게 리팩토링 하였습니다.userService.generateJwtToken

2024-07-28 06:24 UTC, pjhcsols commented on src/main/java/gift/service/user/UserService.java
> +        } else {
orElseGet을 사용하여 이메일로 사용자를 찾거나 새로운 사용자를 생성하도록 리팩토링하였습니다. orElseGet을 사용하면 주어진 값이 없을 때에만 새로운 사용자 생성을 위한 코드가 실행되어 불필요한 메서드 호출을 피할 수 있게 하였습니다.