경북대 BE_심규민 5주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #132
Opened 2024-07-23 15:17 UTC by sim-mer

### 궁금한 점
- 현재는 프론트가 존재하지 않기에 브라우저에서 https://kauth.kakao.com/oauth/authorize로 요청하고 로그인 화면을 얻어 그에 대한 로그인 성공으로 얻은 코드를 가져오는데 프론트가 생기고 로그인 요청이 프론트에서 들어온다면 현재 백엔드 서버에서 https://kauth.kakao.com/oauth/authorize로 요청하나요?  그렇다면 그에 대한 로그인 화면은 프론트로 어떻게 전달하는지 궁금합니다!
- 현재 코드에서 RestClient를 각 OAuthApiClient의 구현체마다 create()로 생성해서 사용하는데 전체 구현체가 모두 같은 RestClient 인스턴스를 사용하는게 더 좋은지 궁금합니다!

2024-07-24 14:59 UTC, leaf-upper requested changes
OAuth에서 Code를 받아서 AccessToken을 받는 부분은 진행되었지만, 
코멘트 드린 Flow대로 한번 로그인 구현에 도전해보면 좋을것 같아요~!
👍

2024-07-24 14:59 UTC, leaf-upper commented on src/main/java/gift/oauth/business/dto/KakaoParam.java
> +        this.grantType = env.getProperty("spring.oauth.kakao.grant_type");
이 3가지 값은 프로퍼티 바인딩할 클래스를 만들어서 사용해보는건 어떨까요?

2024-07-24 14:59 UTC, leaf-upper commented on src/main/java/gift/oauth/business/client/OAuthApiClient.java
> +public interface OAuthApiClient {
👍 OAuth Protocol을 지원해주는곳이 많으니 이렇게 인터페이스로 빼주는건 좋은것 같아요~

2024-07-24 14:59 UTC, leaf-upper commented on src/main/java/gift/oauth/business/client/KakaoApiClient.java
> +        this.restClient = RestClient.create();
**현재 코드에서 RestClient를 각 OAuthApiClient의 구현체마다 create()로 생성해서 사용하는데 전체 구현체가 모두 같은 RestClient 인스턴스를 사용하는게 더 좋은지 궁금합니다!**

저는 개인적으로 ApiClient마다 RestClient를 별도로 생성해서 사용하는걸 선호하는데요~ 
RestClient마다 Connection Pool 및 Socket Connection Timeout, Read Timeout 등등 값을 설정해서 사용할 수 있어요.

여기에서도 비슷하게 Kakao Auth Server로 API 요청을 했을때 Connection Timeout 및 Read Timeout을 설정해보는건 어떨까요?

2024-07-24 14:59 UTC, leaf-upper commented on src/main/java/gift/oauth/business/client/KakaoApiClient.java
> +        System.out.println(result);
stdout 표준 입출력보다는, Logging Framework를 사용해서 로그를 남겨주시면 더 좋을것 같아요~

2024-07-24 14:59 UTC, leaf-upper commented on src/main/java/gift/oauth/presentation/restcontroller/OauthController.java
> +    public void kakao(@RequestParam String code) {
메서드 이름은 동사로 시작하면 좋을것 같아요~

2024-07-24 14:59 UTC, leaf-upper commented on src/main/resources/application.yml
> +      redirect_uri: ${kakao_redirect_uri}
kakao client id는 보안정보이니, 환경변수 등에서 바인딩 받는건 좋은것 같아요~
redirect uri 또한 이렇게 바인딩 받을 필요가 있을까요?

2024-07-24 14:59 UTC, leaf-upper commented on src/main/java/gift/oauth/presentation/restcontroller/OauthController.java
> +public class OauthController {
**현재는 프론트가 존재하지 않기에 브라우저에서 [https://kauth.kakao.com/oauth/authorize로](https://kauth.kakao.com/oauth/authorize%EB%A1%9C) 요청하고 로그인 화면을 얻어 그에 대한 로그인 성공으로 얻은 코드를 가져오는데 프론트가 생기고 로그인 요청이 프론트에서 들어온다면 현재 백엔드 서버에서 [https://kauth.kakao.com/oauth/authorize로](https://kauth.kakao.com/oauth/authorize%EB%A1%9C) 요청하나요? 그렇다면 그에 대한 로그인 화면은 프론트로 어떻게 전달하는지 궁금합니다!**

이 질문과 이어지는데요~
사용자가 로그인을 요청할경우 kauth.kakao.com으로 302 redirect 응답을 주시면 될것 같아요. Flow는 아래와 같은데요,
1. 사용자가 애플리케이션 서버로 로그인 페이지 요청
2. 애플리케이션 서버에서 kauth 페이지로 사용자를 302 redirect
3. 사용자는 해당 페이지에서 로그인하고, 카카오에서는 로그인이 성공하면 해당 사용자를 다시 애플리케이션으로 redirect (이때 code를 줌.)
4. 애플리케이션 서버에서는 이 code를 기반으로 다시 access token 요청, 사용자 정보 요청 등등 진행
위 Flow대로 진행하면 될것 같아요~

2024-07-25 09:15 UTC, sim-mer commented on src/main/java/gift/oauth/business/dto/KakaoParam.java
> +        this.grantType = env.getProperty("spring.oauth.kakao.grant_type");
만들었습니다!

2024-07-25 09:16 UTC, sim-mer commented on src/main/java/gift/oauth/business/client/OAuthApiClient.java
> +public interface OAuthApiClient {
감사합니다!

2024-07-25 09:16 UTC, sim-mer commented on src/main/java/gift/oauth/business/client/KakaoApiClient.java
> +        this.restClient = RestClient.create();
시간과 Connection Pool은 설정했으나 적절한 시간과 개수를 설정하는 방법이나 팁이 궁금합니다!

2024-07-25 09:16 UTC, sim-mer commented on src/main/java/gift/oauth/business/client/KakaoApiClient.java
> +        System.out.println(result);
넵 반영했습니다!

2024-07-25 09:17 UTC, sim-mer commented on src/main/java/gift/oauth/presentation/restcontroller/OauthController.java
> +    public void kakao(@RequestParam String code) {
넵 수정했습니다!

2024-07-25 09:17 UTC, sim-mer commented on src/main/resources/application.yml
> +      redirect_uri: ${kakao_redirect_uri}
굳이 애플리케이션 서버의 주소를 외부에 공개할 필요가 없다고 생각해서 이렇게 설정했습니다!

2024-07-25 09:18 UTC, sim-mer commented on src/main/java/gift/oauth/presentation/restcontroller/OauthController.java
> +public class OauthController {
최종적으로 회원가입 or 로그인 처리 후 애플리케이션 서버에서 사용하는 Jwt 토큰을 반환하도록 변경했습니다!

2024-07-25 09:22 UTC, sim-mer commented on src/main/java/gift/oauth/presentation/restcontroller/OauthController.java
> +    public ResponseEntity<JwtToken> getKakaoCode(@RequestParam String code) {
여기서 리다이렉트 된 url로 코드를 받아와 Jwt토큰을 리턴하면 왜 카카오 서버로 Jwt토큰이 전달 되는게 아니라 사용자에게 전달되는지 궁금합니다!

2024-07-26 05:51 UTC, sim-mer commented
시간 관계상 2단계도 여기 PR에서 진행하겠습니다!

2024-07-26 08:04 UTC, leaf-upper commented on src/main/java/gift/oauth/business/client/KakaoApiClient.java
> +        this.restClient = RestClient.create();
이건 정말 API 별로 설정이 달라질 수 있을것 같고, 어떤 정해진 방법이나 팁이 있지는 않은데요~ 
저 같은 경우 처음에는 값을 보수적으로 잡았다가 이후 애플리케이션을 모니터링해서 적절한값을 찾아나가고 있습니다~

2024-07-26 08:05 UTC, leaf-upper commented on src/main/java/gift/oauth/presentation/restcontroller/OauthController.java
> +    public ResponseEntity<JwtToken> getKakaoCode(@RequestParam String code) {
카카오서버가 사용자를 리다이렉트해서 규민님 애플리케이션 서버로 요청을 보낸것이기에, 사용자에게 JWT 토큰이 넘어갈것 같아요~

2024-07-26 08:22 UTC, leaf-upper approved these changes
👍 고생하셨습니다~ 몇가지 코멘트 드린부분은 생각해보시고 3단계 진행할때 반영해주시면 좋을것 같아요 
2단계까지 API를 연동해보셨는데 많이 어려우셨을것 같네요. 정말 고생많으셨습니다 👍

2024-07-26 08:22 UTC, leaf-upper commented on src/main/java/gift/global/util/EncryptionUtils.java
> +public class EncryptionUtils {
Utils 클래스는 
1. final 키워드를 붙여서 상속이 불가능하게 끔 해주시면 좋을것 같아요
2. 생성이 불가능하게 생성자도 private으로 선언해주시면 좋을것 같아요~

2024-07-26 08:22 UTC, leaf-upper commented on src/main/java/gift/oauth/business/client/KakaoApiClient.java
> +    private ClientHttpRequestFactory getClientHttpRequestFactory() {
ClientHttpRequestFactory를 생성자에서 주입받을수있지않을까요?

2024-07-26 08:22 UTC, leaf-upper commented on src/main/java/gift/oauth/business/dto/OauthInfo.java
> +public class OauthInfo {
OAuth와 Oauth가 혼재되어 사용되는것 같아요. 어떤방식이든 한가지로 통일해주시면 좋을것 같아요~

2024-07-26 08:22 UTC, leaf-upper commented on src/main/java/gift/global/util/StringUtils.java
> +public class StringUtils {
여기도 위에서 말씀드린것처럼 작업해주시면 좋을것 같아요~

2024-07-26 08:22 UTC, leaf-upper commented on src/main/java/gift/oauth/business/client/KakaoApiClient.java
> +public class KakaoApiClient implements OAuthApiClient {
OAuth 인증 API와 메세징 API는 서로 분리해주시면 좋을것 같아요.

2024-07-26 08:22 UTC, leaf-upper commented on src/main/java/gift/product/business/service/OrderService.java
> +    private final ProductRepository productRepository;
ProductRepositor대신 ProductService에 메서드를 위임해서 사용해보는건 어떨까요?

2024-07-26 08:22 UTC, leaf-upper commented on src/main/java/gift/product/persistence/entity/Order.java
> +    private Product product;
이 코멘트는 생각만 해보면 좋을거 같아요.
- 주문은 **"특정 시간대의"** 주문 이기 때문에, 상품의 데이터도 **"주문 당시의 상품"** 이어야해요. 현재 코드에서는  상품데이터가 변경되면, 연관된 주문데이터가 변경된것과 같아요.
- 그렇기 때문에 "주문상품"과 "상품"이 가지는 의미가 약간 다를 수 있어요. 주문 상품은 "주문 당시의 상품 데이터" 여야하고, 상품은 "현재 시간의 상품"이어야 해요.

2024-07-26 08:22 UTC, merged

2024-07-27 01:29 UTC, sim-mer commented on src/main/java/gift/global/util/EncryptionUtils.java
> +public class EncryptionUtils {
EncryptionUtils는 원래 삭제하려했는데 실수로 안했네요 삭제하겠습니다!

2024-07-27 01:29 UTC, sim-mer commented on src/main/java/gift/global/util/StringUtils.java
> +public class StringUtils {
넵 알겠습니다!

2024-07-27 02:16 UTC, sim-mer commented on src/main/java/gift/oauth/business/client/KakaoApiClient.java
> +    private ClientHttpRequestFactory getClientHttpRequestFactory() {
넵 RestClient 설정클래스를 따로 만들고 빈으로 주입받도록 하였습니다!

2024-07-27 02:16 UTC, sim-mer commented on src/main/java/gift/oauth/business/dto/OauthInfo.java
> +public class OauthInfo {
통일했습니다!

2024-07-27 02:16 UTC, sim-mer commented on src/main/java/gift/oauth/business/client/KakaoApiClient.java
> +public class KakaoApiClient implements OAuthApiClient {
분리했습니다!

2024-07-27 02:18 UTC, sim-mer commented on src/main/java/gift/product/business/service/OrderService.java
> +    private final ProductRepository productRepository;
ProductService, MemberService에 위임했습니다!

2024-07-27 02:20 UTC, sim-mer commented on src/main/java/gift/product/persistence/entity/Order.java
> +    private Product product;
넵 알겠습니다!