경북대 BE_신형진 5주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #136
Opened 2024-07-23 16:12 UTC by hjinshin

## 리뷰 받고 싶은 부분
* 소셜 로그인을 할 때 사용자 sub에 `@Kakao` 를 붙여서 이메일에 넣어주었습니다. 그리고 이를 일반 로그인과 구분하기 위해 loginType 필드를 추가하여 구분해주었습니다. 이렇게 소셜 로그인을 구현해도 괜찮을까요?. 혹시 다른 좋은 방법이 있다면 변경해보겠습니다!

2024-07-24 15:14 UTC, leaf-upper requested changes
안녕하세요 형진님~
1단계 구현 고생많으셨습니다
몇가지 코멘트와 질문을 드렸는데요~ 한번 보시고 궁금하신점 있으시면 질문 부탁드릴게요~  
고생하셨습니다.👍 👍

2024-07-24 15:14 UTC, leaf-upper commented on src/main/java/gift/util/KakaoApiUtil.java
> +public class KakaoApiUtil {
Util 이라는 이름은 static 메서드를 모아놓은 유틸리티 클래스로 이해될수도 있을것 같아요.
KakaoAuthService 이런 네이밍은 어떠실까요?

2024-07-24 15:14 UTC, leaf-upper commented on src/main/java/gift/controller/admin/AdminLoginController.java
> +        model.addAttribute("kakaoUrl", properties.loginUrl() + properties.clientId());
login 페이지에서 kakaoUrl (아마도 KAuth 페이지 인것 같아요)을 넘겨주고 있는것 같아요~
이런 방식보다는 아래 Flow대로 OAuth를 구현해보는건 어떨까요?

1. 사용자가 애플리케이션 서버로 로그인 페이지 요청
2. 애플리케이션 서버에서 kauth 페이지로 사용자를 302 redirect
3. 사용자는 해당 페이지에서 로그인하고, 카카오에서는 로그인이 성공하면 해당 사용자를 다시 애플리케이션으로 redirect (이때 code를 줌.)
4. 애플리케이션 서버에서는 이 code를 기반으로 다시 access token 요청, 사용자 정보 요청 등등 진행

2024-07-24 15:14 UTC, leaf-upper commented on src/main/java/gift/controller/admin/AdminLoginController.java
> +    public String kakaoLogin(@RequestParam("code") String code, HttpServletResponse response) {
카카오 서버에서 사용자를 Code값과 함께 리다이렉트 해줄텐데요 이때 대응하는 API가 필요해요~

2024-07-24 15:14 UTC, leaf-upper commented on src/main/java/gift/controller/restcontroller/OAuthRestController.java
> +    public ResponseEntity<TokenResponse> kakaoToken(@RequestParam("code") @NotNull String code) {
OAuth Protocol 동선에대해서 잠깐 설명해주실 수 있을까요?

2024-07-24 15:14 UTC, leaf-upper commented on src/main/java/gift/controller/admin/AdminLoginController.java
> +    public String kakaoLogin(@RequestParam("code") String code, HttpServletResponse response) {
redirectUri가 외부에서 바인딩받고 계셔서 어떤 API에 대응되는지 잘모르겠네요 ㅎㅎ.. 설명부탁드립니다!

2024-07-24 15:24 UTC, hjinshin commented on src/main/java/gift/util/KakaoApiUtil.java
> +public class KakaoApiUtil {
그렇게 되면 OAuthService가 KakaoAuthService를 의존하게 되는데 괜찮은가요?
사실 util로 나눈 이유가 api 요청을 따로 분리하고 싶어서였는데 그냥 service에서 해도 괜찮다면 OAuthService에서 할까요?

2024-07-24 15:30 UTC, hjinshin commented on src/main/java/gift/controller/admin/AdminLoginController.java
> +    public String kakaoLogin(@RequestParam("code") String code, HttpServletResponse response) {
제가 설명이 부족했네요!

저는 관리자 페이지에서 로그인을 요청할 때와 rest api에서 로그인을 요청할 때 두가지로 나누어 주었습니다. 
관리자 페이지에서 로그인을 요청할 때는 kakao.admin-redirect-url=http://localhost:8080/kakao/login 으로 리다이렉트 시켜주었습니다.

2024-07-24 15:40 UTC, hjinshin commented on src/main/java/gift/controller/admin/AdminLoginController.java
> +        model.addAttribute("kakaoUrl", properties.loginUrl() + properties.clientId());
말씀해주신 방식으로 바꿔서 구현하였습니다!

2024-07-24 15:44 UTC, hjinshin commented on src/main/java/gift/controller/restcontroller/OAuthRestController.java
> +    public ResponseEntity<TokenResponse> kakaoToken(@RequestParam("code") @NotNull String code) {
관리자 페이지에서 로그인 요청할 때와 rest api로 로그인을 요청할 때를 나누어 redirect해도록 구현하였습니다. 

만약 클라이언트에서 redirect를 http://localhost:8080/api/v1/oauth/kakao/token으로 하여 로그인하면 ("/kakao/token")으로 api 토큰을 요청하도록 구현하였습니다.

2024-07-25 18:52 UTC, hjinshin commented
추가로 토큰을 관리하는 서비스와 레포지토리를 만들었습니다. 토큰은 레디스 캐시에 저장합니다.

레디스에 접근하는 클래스를 KakaoTokenRepository,
그리고 다른 서비스에서 토큰에 접근하기 위해서는 KakaoTokenService를 통해 접근하도록 구현하였습니다.

이렇게 구현한 이유는 토큰에 대한 레포지토리에 바로 접근하면 여러 서비스들에서 중복된 코드가 자주 발생하여서 이를 방지하기 위해 서비스 계층과 토큰레포지토리 계층 사이에 중간 계층을 구현하였습니다.

사실 service라는 이름이 계속 겹쳐서 고민을 했지만 서비스가 서비스를 의존해도 괜찮다고 하셔서 KakaoTokenService라고 네이밍하였습니다.
해당 서비스는 다른 서비스를 참조하지 않도록 구현하여서 순환참조가 일어나지 않도록 노력하였습니다.

피드백해주신 부분 이외에 다른 부분을 추가하여서 코드가 혼잡스럽지만 한번 읽어주시면 감사드리겠습니다.

2024-07-25 18:55 UTC, hjinshin commented on src/main/java/gift/controller/restcontroller/OAuthRestController.java
> +    public ResponseEntity<TokenResponse> kakaoToken(@RequestParam("code") @NotNull String code) {
추가로 AOP 내에 Transactional 을 구현한 부분은 다음번에 고쳐보도록 하겠습니다!

2024-07-26 08:23 UTC, leaf-upper commented on src/main/java/gift/util/KakaoApiUtil.java
> +public class KakaoApiUtil {
네~ 현재는 Kakao OAuth만 연동하기 때문에 OAuthService에서 직접 연동해도 좋을것 같아요. 이후에 추가적인 OAuth를 연동해야한다면 그때가서 코드를 추상화해도 늦지 않을것 같습니다.

2024-07-26 08:35 UTC, leaf-upper approved these changes
👍 고생하셨습니다~
몇가지 코멘트 남겨드렸는데 확인해주시면 좋을것 같고 1단계는 충분히 잘 구현해주신것 같아요
고생하셨습니다~ 👍

2024-07-26 08:35 UTC, leaf-upper commented on src/main/java/gift/controller/OAuthController.java
> +    public ResponseEntity<Void> kakaoLogin() {
RestController가 아닌, Controller 코드기 때문에 ResponseEntity 보다는 View를 이용해서 응답하면 좋을것 같아요~

2024-07-26 08:35 UTC, leaf-upper commented on src/main/java/gift/repository/KakaoTokenRepository.java
> +public class KakaoTokenRepository {
Redis에 Token을 저장하게 된 이유가 궁금합니다~!

2024-07-26 08:35 UTC, leaf-upper commented on src/main/java/gift/config/RedissonConfig.java
>      public RedissonClient redissonClient(@Value("${redis.host}") String host,
```java
@Bean
public RedisConnectionFactory redissonConnectionFactory(RedissonClient redisson) {
  return new RedissonConnectionFactory(redisson);
}
```
redisson-spring-boot-starter는 Redisson 측에서 만든 AutoConfiguration 의존성인데요~ 사용해도 좋지만 
저는 개인적으로 스프링부트 이외의 AuConfiguration은 사용하지 않습니다.

Redisson을 사용하더라도 data-redis에 통합해서 사용할 수 있어요 생성하신 RedissonClient를 통해서 Redis와의 Connection을 만들고 이를 기반으로 Repository 작성도 가능하지 않을까 싶어요~

2024-07-26 08:35 UTC, merged

2024-07-26 09:15 UTC, hjinshin commented on src/main/java/gift/repository/KakaoTokenRepository.java
> +public class KakaoTokenRepository {
Token을 저장할 방법을 총 3개지 생각해보았습니다. 

1. 인메모리 저장소
2. 데이터베이스
3. 레디스

만약 인메모리 저장소에 Token을 저장한다면 Token이 늘어날 때마다 메모리에 부담이 갈 것이라고 생각하였습니다. 
그렇다고 데이터베이스에 저장하자니 매번 토큰을 요청할 때마다 DB에 IO를 하는 비용이 아깝게 느껴졌습니다.
마침 분산 락을 위해 레디스 환경도 구축해 놓았어서 레디스로 토큰을 관리하는게 좋을 것 같아보여서 레디스에 Token을 저장하게 되었습니다.

혹시 잘못된 부분 있으면 말씀해주세요!