부산대 BE_박혜연 5주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #137
Opened 2024-07-23 16:24 UTC by hyyyh0x

저번 주차에서 피드백 주신 내용 반영하였고,
`
orphanRemoval = true, cascade = CascadeType.ALL
`
사용하는 것으로 변경하였습니다.
이번 주차도 잘 부탁드립니다!

2024-07-23 17:56 UTC, yoo-jaein requested changes
step1 고생하셨습니다.
4주차 피드백도 꼼꼼하게 챙겨주셔서 좋았습니다.
코드가 점점 더 깔끔해지고 있어요..!

리뷰 코멘트 확인 부탁드려요 :)

2024-07-23 17:56 UTC, yoo-jaein commented on .gitignore
> +application-private.properties
👍

2024-07-23 17:56 UTC, yoo-jaein commented on src/main/java/gift/administrator/category/CategoryApiController.java
> +    public ResponseEntity<?> addCategory(@Valid @RequestBody CategoryDTO categoryDTO) {
와일드카드 <?> 보단 명확한 리턴 타입을 지정해주세요!

2024-07-23 17:56 UTC, yoo-jaein commented on src/main/java/gift/administrator/option/OptionApiController.java
>          return ResponseEntity.status(HttpStatus.OK).build();
실제 리턴 타입과 메서드 리턴 타입이 다른 것 같네요..!

2024-07-23 17:56 UTC, yoo-jaein commented on src/main/java/gift/administrator/category/CategoryApiController.java
>      public ResponseEntity<CategoryDTO> deleteCategory(@PathVariable("id") Long id)
여기도 메서드 리턴 타입과 실제 리턴 타입이 다른 것 같아요

2024-07-23 17:56 UTC, yoo-jaein commented on src/main/java/gift/config/RestClientConfig.java
> +    public RestClient.Builder restClientBuilder() {
👍

2024-07-23 17:56 UTC, yoo-jaein commented on src/main/java/gift/config/RestClientConfig.java
> +        factory.setReadTimeout(10000);
타임아웃 설정 👍

2024-07-23 17:56 UTC, yoo-jaein commented on src/main/java/gift/error/ErrorResponse.java
> +public class ErrorResponse {
에러 응답 👍

2024-07-23 17:56 UTC, yoo-jaein commented on src/main/java/gift/users/kakao/KakaoAuthService.java
> +        return kakaoProperties.authUrl() + "?response_type=code&client_id="
UriComponentsBuilder를 사용해서 url을 구성하면 더 안전하게 코드를 작성할 수 있습니다!
- https://2carrot84.github.io/development/uri-component-builder/ 참고

```java
UriComponentsBuilder.fromHttpUrl(baseUrl)
    .path( .... )
```

2024-07-23 17:56 UTC, yoo-jaein commented on src/main/java/gift/users/kakao/KakaoAuthService.java
> +public class KakaoAuthService {
이 클래스 내에 메서드 너무 잘 나누신 것 같아요! 👍

2024-07-23 17:56 UTC, yoo-jaein commented on src/main/java/gift/users/kakao/KakaoAuthService.java
> +    private String getKakaoToken(String code) throws JsonProcessingException {
로깅이 강화되면 좋겠어요!

2024-07-23 17:56 UTC, yoo-jaein commented on src/main/java/gift/users/kakao/KakaoAuthService.java
> +            .header("Authorization", "Bearer " + token)
이런 문자열들은 상수로 처리하는 것이 좋습니다

2024-07-23 17:56 UTC, yoo-jaein commented on src/main/java/gift/users/kakao/KakaoAuthService.java
> +        String response = restClientBuilder.build().post()
String으로 응답을 받는 것보다 DTO를 사용하는 것이 타입 안정성과 코드 가독성 측면에서 더 좋습니다.
응답을 디버깅할때도 DTO가 더 편해요!

2024-07-23 17:56 UTC, yoo-jaein commented on src/main/java/gift/users/kakao/KakaoAuthService.java
> +    private Long getKakaoUser(String token) throws JsonProcessingException {
JsonProcessingException은 메서드 내에서 예외 처리하고 메서드 시그니처에서 제거하는 것은 어떨까요!
조금 더 구체적인 예외(예: KakaoAuthenticationException)로 변환해서 던져주는 것도 괜찮겠네요

```java
    private Long getKakaoUser(String token) {
        try {
            ...
            return userService.findByKakaoIdAndRegisterIfNotExists(kakaoId.toString());
        } catch (JsonProcessingException e) {
            throw new AuthenticationException("Failed to process Kakao user data", e);
        } catch (Exception e) {
            throw new AuthenticationException("Failed to get Kakao user data", e);
        }
    }
```

2024-07-23 17:56 UTC, yoo-jaein commented on src/main/java/gift/users/kakao/KakaoProperties.java
> +@ConfigurationProperties(prefix = "kakao")
👍

2024-07-23 17:56 UTC, yoo-jaein commented on src/test/java/gift/service/KakaoAuthServiceTest.java
> +}
예외 케이스도 추가하면 좋을 것 같아요. (예: 토큰 요청 실패..)

2024-07-24 08:47 UTC, hyyyh0x commented
피드백 반영 완료했습니다. 추가로 상품, 옵션, 카테고리, 회원 아이디를 조회할 때 NotFoundException을 던지는데, 이 부분을 NotFoundIdException으로 바꿔서 에러 메시지가 출력되도록 변경했습니다.
확실히 코드가 많이 깔끔해진 것 같습니다! 그 덕분에 과제하는데에 더욱 재미와 보람을 느끼고 있는 것 같습니다 :) 감사합니다!
부족한 부분은 또 수정하겠습니다.

2024-07-24 13:20 UTC, yoo-jaein requested changes
리뷰 반영된 것 확인했습니다!
인증 부분에서 추가로 개선해볼만한 점이 있어 코멘트 새로 남겼습니다.
확인 부탁드려요 :)

2024-07-24 13:20 UTC, yoo-jaein commented on src/main/java/gift/users/kakao/KakaoAuthService.java
> +            logger.error("Kakao token response body is null.");
꼼꼼한 로깅 👍

2024-07-24 13:20 UTC, deactivated-user commented on src/main/java/gift/users/kakao/KakaoAuthService.java
> +            logger.info("Failed to recieve kakao token: {}", e.getMessage());
여기는 로그 레벨이 error가 되어야겠네요!

2024-07-24 13:20 UTC, yoo-jaein commented on src/main/java/gift/users/kakao/KakaoAuthApiController.java
> +    public ResponseEntity<String> kakaoCallBack(@RequestParam("code") String code) {
accessToken을 직접 반환하고 있는데 보안상 이슈가 될 수 있습니다!
(HTTPS를 사용하더라도 네트워크 상에서 토큰이 노출될 가능성 있음)

2024-07-24 13:20 UTC, deactivated-user commented on src/main/java/gift/users/kakao/KakaoAuthApiController.java
> +    public ResponseEntity<String> kakaoCallBack(@RequestParam("code") String code) {
OAuth 인증을 서비스에 넣으면 일반적으로 이렇게 구성합니다!

클라이언트 - 내 서버 간 인증에서는 JWT 사용
- 우리 회원에 대한 권한 확인
- 클라이언트가 모든 API 요청에 JWT를 포함시킴

내 서버 - 카카오 API 간 인증에서는 카카오 액세스 토큰 사용
- 카카오 API에 대한 호출 권한 확인
- 내 서버가 특정 유저의 요청을 받았을 때 그 유저의 JWT를 보고 데이터베이스에서 액세스 토큰을 가져오고 카카오 API를 호출함

2024-07-24 13:20 UTC, yoo-jaein commented on src/main/java/gift/users/kakao/KakaoAuthApiController.java
> +    public ResponseEntity<String> kakaoCallBack(@RequestParam("code") String code) {
이런 플로우로 개선해볼 수 있을 것 같아요~
혹시 이해가 잘 안되신다면 멘토링 신청해주셔도 됩니다.
```text
- 사용자가 카카오 로그인을 통해 인증
- 내 서버가 카카오로부터 액세스 토큰+리프레시 토큰 등... 을 받음
- 내 서버는 이 액세스 토큰을 사용해 카카오 API를 사용함 (해당 유저의 정보를 가져온다든지, 메시지를 쏜다든지..)
- 내 서버는 JWT를 생성하여 클라이언트에 전송
- 클라이언트는 이후 모든 요청에 이 JWT를 포함시켜 인증
- 내 서버는 카카오 액세스 토큰(과 기타 등등.. )을 데이터베이스에 안전하게 저장하고, 필요할 때 꺼내서 사용
```

2024-07-24 13:20 UTC, yoo-jaein commented on src/main/java/gift/users/kakao/KakaoAuthService.java
> +                .toEntity(KakaoUserDTO.class);
응답 상태코드가 200 OK가 아닌 경우에 대한 처리를 추가하면 좋겠습니다!

2024-07-25 05:45 UTC, hyyyh0x commented on src/main/java/gift/users/kakao/KakaoAuthApiController.java
> +    public ResponseEntity<String> kakaoCallBack(@RequestParam("code") String code) {
멘토링 신청하려 보니 멘토링 스케줄에 멘토님 일정이 더 이상 없네요..!

accessToken을 직접 반환하는 것이 보안상 이슈가 된다는 부분에서 이해가 가지 않는 것이 있습니다. 
accessToken을 직접 반환하지 않으면 어떻게 로그인 후 accessToken을 가지고 접근해야 하는 wishList 와 같은 곳에서 accessToken을 주고 접근할 수 있는지 이해가 잘 가지 않습니다.

accessToken을 직접 반환하는 것을 하지 않는다면 어떻게 유저가 wishList와 같은 곳에 접근 가능한지 궁금합니다!

2024-07-25 06:03 UTC, yoo-jaein commented on src/main/java/gift/users/kakao/KakaoAuthApiController.java
> +    public ResponseEntity<String> kakaoCallBack(@RequestParam("code") String code) {
accessToken을 직접 반환하면 해커에 의해 탈취될 수 있습니다.
탈취되면 해커가 해당 토큰으로 카카오 api를 호출해 사용자 신원을 도용할 수 있고, 개인정보도 접근할 수 있습니다. 혹은 유료 api를 무단으로 호출할 수도 있구요.
그래서 accessToken과 refreshToken 등 카카오 인증 정보는 사용자에게 넘기는 것이 아니라 데이터베이스에 보관해야 합니다.

### 기존 유저 테이블:
- 사용자 ID
- 이메일
- 비밀번호
- 기타 데이터

### OAuth 토큰 테이블:
- 사용자 ID
- 제공자 (예: 카카오, 구글 등)
- 액세스 토큰
- 리프레시 토큰
- 토큰 만료 시간
- 기타 관련 메타데이터

사용자와 내 서버간 인증에선 jwt를 사용하고, 
카카오 api 호출이 필요한 경우 위의 토큰 테이블에서 사용자 ID로 해당 유저의 액세스 토큰을 찾은 뒤, 그 액세스 토큰으로 호출해야 합니다.

2024-07-25 06:06 UTC, yoo-jaein commented on src/main/java/gift/users/kakao/KakaoAuthApiController.java
> +    public ResponseEntity<String> kakaoCallBack(@RequestParam("code") String code) {
멘토링은 시간 수정해두었습니다!

2024-07-25 08:31 UTC, yoo-jaein approved these changes
step1 머지하겠습니다!

2024-07-25 08:31 UTC, merged