강원대 BE_김병수 5주차 과제 (step1)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #144
Opened 2024-07-23 23:07 UTC by GamJaDo

# 어려웠던 점
- 기능 요구 사항에서 설명해 준 로그인 과정을 따라 작성하기가 어려웠었습니다.
- 하지만 공식 문서를 천천히 읽어 나가면서 이해하는 과정이 있어서 이번 과제는 재미있게 했던 것 같습니다.

2024-07-24 15:22 UTC, jaymarystella requested changes
안녕하세요~
1단계 구현관련해서 간단한 피드백 몇가지만 남겼으니 확인부탁드립니다.

2024-07-24 15:22 UTC, jaymarystella commented on src/main/java/gift/config/RestTemplateConfig.java
> +    }
기본설정값들이 어떻게 들어가는지 살펴보시면 좋을것같아요.

2024-07-24 15:22 UTC, jaymarystella commented on src/main/java/gift/service/KakaoAuthService.java
> +        String url = "https://kauth.kakao.com/oauth/token";
url은 yml이나 최소 상수값으로 관리되면 더 좋을것같습니다.

2024-07-24 15:22 UTC, jaymarystella commented on src/main/java/gift/service/KakaoAuthService.java
> +    }
메서드의길이를 줄일 수 있는 방법을 찾아보면 어떨까요?

2024-07-24 15:22 UTC, jaymarystella commented on src/main/resources/application.yml
> +  client-id: ${KAKAO_CLIENT_ID}
👍🏼

2024-07-24 17:34 UTC, GamJaDo commented on src/main/java/gift/service/KakaoAuthService.java
> +        String url = "https://kauth.kakao.com/oauth/token";
yml에서 관리하도록 하였습니다.

2024-07-24 17:35 UTC, GamJaDo commented on src/main/java/gift/service/KakaoAuthService.java
> +    }
메서드들이 한가지 일만 잘하도록 세세히 나눴습니다.

2024-07-24 18:50 UTC, GamJaDo commented on src/main/java/gift/config/RestTemplateConfig.java
> +    }
[Spring RestTemplate Error Handling](https://www.baeldung.com/spring-rest-template-error-handling)를 읽고 응답 시간과, 에러 헨들링을 추가하였습니다.

2024-07-25 13:13 UTC, jaymarystella approved these changes
리뷰 반영하느라 고생많으셨습니다.
다음 단계에서 뵐게요~

2024-07-25 13:14 UTC, merged