전남대 BE_박민규 5주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #156
Opened 2024-07-24 06:12 UTC by ps9319

읗어ㅓㅎㅇ헣엏엏ㅇ 멘토님 이번에 오류가 안 잡혀서 일단 이렇게 제출하고 수정할 부분 수정해보겠습니다아...
다뤄보지 않은 걸 많이 다뤄봐서 이번에 시간이 너무 오래 걸렸습니다..

kakao.client-id="tmptmptmp"
kakao.redirect-url=http://localhost:8080

로 application-auth.properties 파일을 해놓았는데 

localhost:8080/api/oauth/redirect로 요청을 보내도
https://kauth.kakao.com/oauth/authorize?client_id=null 로 리다이렉트 되면서
자꾸 id값을 받아오지 못하고 null값을 받아와요 ㅠㅠㅠ

뭐가 문젠지 해결해보려다가 도저히 해결이 안돼서 일단 제출해보겠습니다아..

2024-07-26 05:30 UTC, dc-choi requested changes
안녕하세요 민규님!

일단 코멘트를 먼저 확인하였고 그 다음 전체적인 코드를 확인하였습니다.

일단 코드 세세히 리뷰를 드리는것 보다 우선적으로 코멘트에 대한 답부터 먼저 드리는게 좋아보여서 코멘트에 대한 답변만 드리도록 하겠습니다.

일단 질문주신 부분에 대해서 먼저 답을 드리자면 백엔드 자체에서 인가 코드를 얻어내서 액세스 토큰 요청을 보내는게 맞습니다.

서버에서 해당 부분에 대한 요청처리를 진행하는게 보안상 더 좋은 방법이에요~!

그리고 email 부분을 못가져온다고 하셨는데 아마 맨 처음 인가코드를 가져올 경우 scope를 지정해줘야 할 것으로 보여요~! (비즈앱 등록은 필요없긴 합니다... ㅎㅎ)

https://developers.kakao.com/docs/latest/ko/kakaologin/utilize#scope-user

해당 문서를 참고하시면 될 거 같아요~!

2024-07-26 13:06 UTC, ps9319 commented
우와아아아아ㅏ 며칠째 해결 못한 것을 멘토님 덕에 해결했습니다 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

> 일단 질문주신 부분에 대해서 먼저 답을 드리자면 백엔드 자체에서 인가 코드를 얻어내서 액세스 토큰 요청을 보내는게 맞습니다.

그럼 이 부분에서 KakaoClient에서 getAccessToken 요청을 보냈던 것처럼 getAuthorizeCode 같은 요청을 만들어야되는 걸까요??
일단 제대로 작동하는 것에 너무 기뻐서 이대로 제출하겠습니다!!!

2024-07-27 04:28 UTC, dc-choi requested changes
안녕하세요 민규님!

보면서 궁금했던 부분은 자세한 코멘트로 남겨두었습니다.

그리고 코드를 보니 보통 일반적으로 생각하는 OAuth2의 방식과는 좀 달라보이네요... ㅎㅎ

지금은 과제니깐 상관없는데 나중에 실제로 구현하게 되시는 경우에는 이렇게 하시면 안된다는 것만 참고해주십쇼!!

> 그럼 이 부분에서 KakaoClient에서 getAccessToken 요청을 보냈던 것처럼 getAuthorizeCode 같은 요청을 만들어야되는 걸까요??

이 부분은 이미 맨처음에 redirect를 해주는 부분에서 처리가 될 예정이라 상관없어보입니다~!

2024-07-27 04:28 UTC, dc-choi commented on src/main/java/gift/controller/AuthController.java
> +    @PostMapping("/api/oauth/register")
이 부분은 oauth를 사용하지 않아보입니다.

혹시 어떤 이유로 oauth를 사용하신건가요?

2024-07-27 04:28 UTC, dc-choi commented on src/main/java/gift/controller/AuthController.java
> +    @PostMapping("/api/oauth/login")
이 부분은 oauth를 사용하지 않아보입니다.

혹시 어떤 이유로 oauth를 사용하신건가요?

2024-07-27 06:44 UTC, ps9319 commented on src/main/java/gift/controller/AuthController.java
> +    @PostMapping("/api/oauth/login")
아 AuthController라 그냥 무의식 적으로 전부 oauth를 붙여버렸습니다..! 수정하겠습니다.

2024-07-27 06:47 UTC, ps9319 commented on src/main/java/gift/controller/AuthController.java
> +    @PostMapping("/api/oauth/register")
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-order/pull/156#discussion_r1693892630

2024-07-27 06:55 UTC, ps9319 commented on src/main/java/gift/controller/AuthController.java
> +
그리구 처음에 못 여쭤봤는데
제가 로그인은 authService에서 하고, 회원을 가입시키거나 정보를 찾는 것은 UserService에서 하느라 이 부분이 복잡해진 것 같은데 이렇게 구현해도 괜찮나요??

2024-07-27 06:56 UTC, ps9319 commented
> 그리고 코드를 보니 보통 일반적으로 생각하는 OAuth2의 방식과는 좀 달라보이네요... ㅎㅎ

혹시 일반적으로는 어떻게 구현해야하는지 가르쳐주실 수 있나요!!...?

https://github.com/kakao-tech-campus-2nd-step2/spring-gift-order/pull/156#discussion_r1693897268 이부분도 봐주시면 감사하겠습니다 🙇🏻‍♀️

2024-07-28 11:38 UTC, dc-choi commented
> 그리고 코드를 보니 보통 일반적으로 생각하는 OAuth2의 방식과는 좀 달라보이네요... ㅎㅎ
> 일반적으로는 어떻게 구현해야하는지 가르쳐주실 수 있나요!!...?

현재 테스트 단계라서 직접 받아온 코드를 다시 요청을 보내는 것처럼 보이는데 원래는 바로 처리할 수 있도록 하는게 일반적인 방법이라 그렇게 말씀을 드렸었습니다! 크게 문제될 부분은 아닌거 같아요~!

2024-07-28 11:39 UTC, dc-choi approved these changes
크게 문제될 부분은 없어보입니다! step2 과제 마저 리뷰하도록 하겠습니다!

2024-07-28 11:39 UTC, merged