강원대 BE_오승규 5주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #163
Opened 2024-07-24 07:03 UTC by 5win

안녕하세요 제이님
5주차 과제 1단계 PR 드립니다!

기능 구현하고 프론트쪽도 구현하다가 리다이렉션과 응답 받는 부분이 잘 되지않아서 프론트 부분은 로그인하고 bearer token 을 볼 수 있는 정도까지만 구현했습니다.

질문사항은 코멘트로 남겨놓겠습니다!

2024-07-24 07:07 UTC, 5win commented on src/main/java/gift/controller/KakaoLoginController.java
> +    @GetMapping("/login/kakao")
처음엔 index.html 뷰에 URL과 client_id를 넣어서 로그인 클릭 시 로그인 화면으로 바로 가도록 하려했으나
이렇게하면 민감 정보가 노출되는 바람에 이렇게 따로 리다이렉션을 하도록 했습니다.

2024-07-24 07:08 UTC, 5win commented on src/main/java/gift/controller/KakaoLoginController.java
> +    @ResponseBody
현재 엔드포인트가 2개 밖에 없어서 일단 하나의 컨트롤러에 함께 넣느라 `@ResponseBody`를 사용했습니다.
추후 기능이 확장되게 되면 나누도록 하겠습니다!

2024-07-24 07:09 UTC, 5win commented on src/main/java/gift/domain/KakaoLogin.java
> +public class KakaoLogin {
서비스에서 로직을 제거하기 위해 KakaoLogin이라는 도메인 클래스를 만들어서 책임을 할당해주도록 해봤습니다.

2024-07-24 07:26 UTC, 5win commented on src/main/java/gift/domain/KakaoLogin.java
> +    public Member generateMemberByKakaoUserInfo(KakaoUserInfo kakaoUserInfo) {
현재 요구사항에선 email을 만들 방법이 id를 이용해서 임의로 만드는 것이 최선인 것 같아 이렇게 일단 구현했습니다.

궁금한 점이 좀 있는데요
실제 서비스에서는 "카카오 로그인"을 통해 abc@kakao.com으로 계정을 만들었다면, 기존에 자체 로그인 서비스에서는 abc@kakao.com 로 로그인이나 접근이 되도록하면 안될 것 같은데 보통 두 회원 정보를 독립적인 DB에 저장하는 것이 일반적일까요?
기존 자체 로그인 서비스로 ID/PW를 통해 로그인했었는데 카카오 로그인 기능을 추가했다면, email로 ID를 대체할 순 있지만 PW에 대응되는 부분은 카카오API에서 제공해주지 않는 것 같아 같은 테이블에 저장하려면 임의로 PW를 지정해주어야 할 것 같습니다.
이런 경우를 봐도 테이블을 별도로 운영하는게 맞을 것 같다는 생각이 듭니다.

만약 이렇게 서로 다른 테이블로 운영을 한다면 카카오 인지, 구글인지, 자체 로그인인지를 식별할 수 있는 헤더값 같은 것을 함께 보내주도록 설계하는 것이 좋을까요?

2024-07-24 07:28 UTC, 5win commented on src/main/java/gift/service/KakaoService.java
> +        Optional<Member> queriedMember = memberJpaDao.findByEmail(kakaoMember.getEmail());
Member에 대한 도메인 클래스?는 기존에 따로 분리해놓지 않아서 일단 서비스에 로직을 작성했습니다.

2024-07-24 07:30 UTC, 5win commented on src/main/java/gift/controller/KakaoLoginController.java
> +public class KakaoLoginController {
카카오 로그인을 테스트하기 위해선 직접 로그인하고 토큰을 받아오는 작업이 필요해서 테스트코드를 통해 검증이 가능할지 잘 모르겠습니다.
다른 부분 구현해놓고 로그인해서 얻은 토큰을 매번 직접 바꿔주면 가능은 할 것 같은데...일단은 포스트맨을 통해 테스트했습니다.

2024-07-24 07:52 UTC, 5win commented on src/main/java/gift/domain/KakaoLogin.java
> +            .onStatus(httpStatusCode -> httpStatusCode == HttpStatusCode.valueOf(400),
지금 다시 보다보니 IllegalArgumentException으로 던지지 않고 커스텀으로 던진 뒤에
ExceptionHandler에서 받아서 상태코드까지 함께 반환해야 할 것 같네요..

이 부분은 다시 개선해보도록 하겠습니다!

2024-07-24 15:43 UTC, jaymarystella commented on src/main/java/gift/domain/KakaoLogin.java
> +    public Member generateMemberByKakaoUserInfo(KakaoUserInfo kakaoUserInfo) {
음 제가 이부분을 실제로 구현해본적은없는데요,

사용자가 소셜 로그인과 자체 로그인을 혼합하여 사용할 때 일관된 사용자 경험을 제공할 수 있도록 해야되는게 이상적으로 보입니다.
당연히 테이블은 하나로 운영할것같구요, 이메일과 이메일플랫폼제공자 id도 함께 관리되면 될것같아요. 어떤 방향으로 로그인시도를 하더라도 분기를 타서 로그인을 시켜주면 될것같습니다. (소셜로그인으로 가입하면 기존에 동일이메일이 있는지 확인하고 있다면 매핑을 시켜주고, 없다면 단순저장. 일반가입을 해도 마찬가지)

2024-07-24 15:44 UTC, jaymarystella commented on src/main/java/gift/controller/KakaoLoginController.java
> +public class KakaoLoginController {
위와같은 특성으로 매번 테스트가 어렵다면 Ignore처리해두셔도됩니다

2024-07-24 15:47 UTC, jaymarystella requested changes
안녕하세요 1단계 잘 구현해주셨네요~
피드백은 많이 없는데 한번씩 확인만해주세요

2024-07-24 15:47 UTC, jaymarystella commented on src/main/java/gift/domain/KakaoLogin.java
> +            .onStatus(httpStatusCode -> httpStatusCode == HttpStatusCode.valueOf(403),
이거 onstatus 내부분기를 하게되면 3번안쓰고 다 처리할 수 있지 않나요?

2024-07-24 15:47 UTC, jaymarystella commented on src/main/java/gift/domain/KakaoLogin.java
> +        KakaoTokenResponse response = restClient.post()
메서드 길이를 줄여보려면 어떻게 하면 좋을까요?

2024-07-24 15:47 UTC, jaymarystella commented on src/main/java/gift/dto/KakaoTokenResponse.java
> +@JsonNaming(value = PropertyNamingStrategies.SnakeCaseStrategy.class)
이건 왜이렇게 쓰셨나요?

2024-07-24 15:47 UTC, jaymarystella commented on src/main/java/gift/service/KakaoService.java
> +        Optional<Member> queriedMember = memberJpaDao.findByEmail(kakaoMember.getEmail());
넵 필요하다고 생각되시면 도메인정의를 따로해주세요!

2024-07-25 14:15 UTC, 5win commented on src/main/java/gift/domain/KakaoLogin.java
> +    public Member generateMemberByKakaoUserInfo(KakaoUserInfo kakaoUserInfo) {
일관된 사용자 경험적인 측면은 생각해보지 못했네요
그런 부분과 서비스 로직의 복잡성적인 측면으로 봤을 때도 단일 테이블로 운영하는게 좋을 것 같단 생각이 듭니다!
만약 회원 가입을 했는데 동일 이메일이 이미 존재하는 경우에는 기존 계정에 매핑하는 것도 좋은 방법인 것 같네요
좋은 의견 감사합니다!

2024-07-25 14:16 UTC, 5win commented on src/main/java/gift/domain/KakaoLogin.java
> +            .onStatus(httpStatusCode -> httpStatusCode == HttpStatusCode.valueOf(403),
넵 반영하여 switch를 사용해 개선했습니다!

2024-07-25 14:18 UTC, 5win commented on src/main/java/gift/domain/KakaoLogin.java
> +        KakaoTokenResponse response = restClient.post()
요청 body 만드는 부분은 private 메서드로 따로 분리했고 response 값도 따로 저장 없이 바로 return하도록 개선해보았습니다.
더 개선할 부분이 있다면 말씀해주세요!

2024-07-25 14:20 UTC, 5win commented on src/main/java/gift/dto/KakaoTokenResponse.java
> +@JsonNaming(value = PropertyNamingStrategies.SnakeCaseStrategy.class)
카카오 API로부터 데이터를 받아와 해당 객체로 바인딩을 시키는 과정에서 카카오API는 필드명을 스네이크 케이스로 반환하는 바람에 바인딩이 잘 되지 않았습니다.

해결 방법으로 `@JsonProperty`를 사용하는 방법도 있었는데 필드 개수가 많아서 한 번에 처리해주기 위해 사용했습니다.

2024-07-26 23:52 UTC, jaymarystella approved these changes
안녕하세요~
리뷰반영잘해주셨네요 다음단계 진행해주세요!

2024-07-26 23:52 UTC, merged