충남대 BE_이동현 5주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #164
Opened 2024-07-24 07:07 UTC by Thornappl2

- 관리자 페이지에 카카오 로그인 버튼을 추가하고 토큰 발급 확인 페이지를 추가하여 정상적으로 액세스 토큰이 발급되는 것을 확인하였습니다.
- 기존 jwtUtil을 통해 발급된 토큰과 서버에서 자체 발급한 토큰이 있을 텐데, 이를 통해 가입한 회원을 기존 Member와 분리하여 KakaoMember와 같은 형태로 구현해야 할까요? 아니면 기존 Member에 통합하는 것이 맞을까요?

2024-07-25 12:33 UTC, ksy90101 requested changes
간단한 피드백을 남겼으니 확인해주세요~

2024-07-25 12:33 UTC, ksy90101 commented on src/main/java/gift/dto/KakaoTokenResponse.java
> +public class KakaoTokenResponse {
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
이 키워드로 하면 JsonProperty를 추가할 필요가 없어보이긴 합니다.

2024-07-25 12:33 UTC, ksy90101 commented on src/main/java/gift/service/KakaoAuthService.java
> +    public KakaoTokenResponse getAccessToken(String code) {
API를 호출하는걸 따로 컴포넌트로 관리하면 어떨까요?

그렇게 하면 책임분리가 확실히 될거 같아요.

2024-07-25 13:41 UTC, Thornappl2 commented on src/main/java/gift/dto/KakaoTokenResponse.java
> +public class KakaoTokenResponse {
적용했습니다.

2024-07-25 15:08 UTC, Thornappl2 commented on src/main/java/gift/service/KakaoAuthService.java
> +    public KakaoTokenResponse getAccessToken(String code) {
반영하였습니다.

2024-07-26 13:47 UTC, ksy90101 approved these changes
고생많으셨어요~ 2단계예서 뵐게요~

2024-07-26 13:47 UTC, ksy90101 commented on src/main/java/gift/client/KakaoApiClient.java
> +public class KakaoApiClient {
👍

2024-07-26 13:47 UTC, ksy90101 commented on src/main/java/gift/service/KakaoAuthService.java
> +                "&redirect_uri=" + kakaoProperties.getRedirectUri();
https://ordilov.github.io/posts/Uri%20Builder

이걸 이용해서 만들면 깔끔할거 같아요,

2024-07-26 13:47 UTC, merged

2024-07-28 11:50 UTC, Thornappl2 commented on src/main/java/gift/service/KakaoAuthService.java
> +                "&redirect_uri=" + kakaoProperties.getRedirectUri();
2단계에 반영하겠습니다