경북대 BE_배규민 5주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #168
Opened 2024-07-24 08:19 UTC by GyuminBae

* 5주차 2단계 과제입니다.

2024-07-24 13:23 UTC, lsm7179 requested changes
규민님 과제 수고하셨습니다.
머지하기엔 조금 아쉬워서 피드백 남겼습니다.
반영 후 다시 요청주세요~!

2024-07-24 13:23 UTC, lsm7179 commented on src/main/java/gift/core/BaseAuditingEntity.java
> +    private LocalDateTime createdAt;
👍

2024-07-24 13:23 UTC, lsm7179 commented on src/main/java/gift/core/domain/product/ProductOption.java
> +    }
이부분은 단위테스트가 있으면 좋을거 같네요~

2024-07-24 13:23 UTC, lsm7179 commented on build.gradle
> +    implementation group: 'org.apache.httpcomponents.client5', name: 'httpclient5', version: '5.3.1'
이부분은 왜 추가했나요?🤔

2024-07-24 13:23 UTC, lsm7179 commented on src/main/java/gift/advice/GatewayTokenArgumentResolver.java
> +        System.out.println(parameter.hasParameterAnnotation(GatewayToken.class) && parameter.getParameterType().equals(String.class));
sout은 제거해주세요.
평소에도 log를 이용해주세요~

2024-07-24 13:23 UTC, lsm7179 commented on src/main/java/gift/order/infrastructure/gateway/KakaoOrderAlarmGateway.java
> +    }
LinkedMultiValueMap 대신에 추상화된 객체를 선언해보세요~

2024-07-24 13:23 UTC, lsm7179 commented on src/main/java/gift/order/service/OrderServiceImpl.java
> +    }
제일 중요한 로직인데 테스트코드가 없어도 될까요?

2024-07-24 13:24 UTC, GyuminBae commented on src/main/java/gift/advice/GatewayTokenArgumentResolver.java
> +        System.out.println(parameter.hasParameterAnnotation(GatewayToken.class) && parameter.getParameterType().equals(String.class));
앗 잠시 테스트용으로 작성했다 제거하는걸 깜빡했습니다!

2024-07-24 13:27 UTC, GyuminBae commented on build.gradle
> +    implementation group: 'org.apache.httpcomponents.client5', name: 'httpclient5', version: '5.3.1'
피드백해주신 커넥션 타임아웃 설정을 위해 예시로 주신 글에서 필요한 HttpComponentsClientHttpRequestFactory 가 스프링에서 dependency management로 관리하는 apache 버전보다 상위 버전에서 필요한 것 같아 추가했습니다. (없을 시 HttpClient 클래스를 못찾습니다)

2024-07-24 13:27 UTC, GyuminBae commented on src/main/java/gift/order/infrastructure/gateway/KakaoOrderAlarmGateway.java
> +    }
반영했습니다!

2024-07-24 13:27 UTC, GyuminBae commented on src/main/java/gift/core/domain/product/ProductOption.java
> +    }
반영했습니다!

2024-07-24 22:47 UTC, GyuminBae commented on src/main/java/gift/order/service/OrderServiceImpl.java
> +    }
테스트코드 추가했습니다!

2024-07-25 08:18 UTC, lsm7179 approved these changes
규민님 과제 수고하셨습니다~!
요구사항 구현과 테스트코드 잘 작성해주셨습니다.

2024-07-25 08:18 UTC, merged