경북대 BE_배준호 5주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #173
Opened 2024-07-24 12:33 UTC by BaeJunH0

피드백 내용 반영했습니다 ( properties 파일 분리 및 gitIgnore에 추가하여 온라인 환경에 공개되지 않게 하기, 새로 API 발급받기 )

step 2 요구 사항대로 구현했습니다
- 메세지 작성 기능
- 옵션 수량 차감 기능 ( 옵션 수량 이상의 값을 입력받을 때의 동작 예외 처리를 단순 무응답 처리, 추후 exception 처리 할게요 )
- 위시 리스트에 있을 때 삭제하는 기능
- 주문 내역을 카카오톡 메세지로 전송하는 기능

step 1에서 피드백 구현 없이 머지 부탁드려서 죄송합니다! 더 잘해보겠습니다!

2024-07-24 13:48 UTC, lsm7179 requested changes
준호님 2단계 과제 수고하셨습니다.
피드백 몇가지 드렸는데 보시고 반영 후 재요청 주세요.🔥

2024-07-24 13:48 UTC, lsm7179 commented on .gitignore
> +src/main/resources/secret.properties
`ignore`처리로 괜찮을까요?
https://velog.io/@crow/Spring-boot-%EC%99%B8%EB%B6%80-%ED%99%98%EA%B2%BD%EB%B3%80%EC%88%98-%EC%A3%BC%EC%9E%85
이런 방법은 어떤가요?

2024-07-24 13:48 UTC, lsm7179 commented on src/main/java/gift/DTO/Kakao/Commerce.java
> +    private int regular_price;
컨벤션을 지켜주세요.
camel case로 수정해주세요.
https://blog.naver.com/ege1001/220466932974

외부 json으로 파싱해야 되는거라면 https://velog.io/@sussa3007/Java-Snake-Case-Camel-Case-Data-%EB%B3%80%ED%99%98
해당글을 적용해보아요.

2024-07-24 13:48 UTC, lsm7179 commented on src/main/java/gift/DTO/Kakao/Content.java
> +    private String image_url;
컨벤션을 지켜주세요.
camel case로 수정해주세요.😁
다른것도 같이 확인해주세요~!

2024-07-24 13:48 UTC, lsm7179 commented on src/main/java/gift/security/KakaoTokenProvider.java
> +        userRepository.save(user);
이부분은 userService가 해야되는 역할인거 같네요.
지금 `getKakaoUserInfo`는 `KakaoTokenProvider`의 메서드 역할을 하고 있는거 같지 않아요.
필요하다면 userService가 KakaoTokenProvider를 참조해서 user를 생성하는 로직으로 수정해야될거같네요.

2024-07-24 13:48 UTC, lsm7179 commented on src/main/java/gift/service/KakaoUserService.java
> +    private static LinkedMultiValueMap<Object, Object> makeBody(
statice메소드여야 하나요?

2024-07-24 13:48 UTC, lsm7179 commented on src/main/java/gift/service/KakaoUserService.java
> +        return loginUrl;
필요하다면 `StringBuffer`로 만들어보세요.

`private String loginUrl;` 불변이 아니여도 되나요? 수정가능해도 될까요?

2024-07-24 13:48 UTC, lsm7179 commented on src/main/java/gift/service/OrderService.java
> +        );
`Order`를 생성할때 자동으로 시간을 채우는 방법이 있을거 같아요. 수정해보아요.

2024-07-24 13:48 UTC, lsm7179 commented on src/main/java/gift/service/OrderService.java
> +        }
이건 어떤 로직인가요?
수량이 감소되지 않으면 그냥 빈값을 내려주나요?

2024-07-24 13:48 UTC, lsm7179 commented on src/main/java/gift/service/OrderService.java
> +public class OrderService {
test 코드가 필요해보여요.

2024-07-24 14:27 UTC, BaeJunH0 commented on src/main/java/gift/service/KakaoUserService.java
> +    private static LinkedMultiValueMap<Object, Object> makeBody(
인텔리제이 자동 추출로 했더니... 다음부터는 더 확인하겠습니다!

2024-07-24 21:46 UTC, BaeJunH0 commented on src/main/java/gift/service/OrderService.java
> +        }
아마 exception으로 처리하려고 더미 코드를 넣어놓은 것 같은데, 이런 exception 처리까지도 요구 사항의 일부라고 본다면 저의 미스인 것 같습니다! 빨리 exception 처리 완료해보겠습니다!

2024-07-24 21:50 UTC, BaeJunH0 commented on src/main/java/gift/service/KakaoUserService.java
> +        return loginUrl;
loginUrl은 불변이면 안될 것 같습니다! 불변이라면 다른 유저가 로그인할 때에는 바뀌어야 되는 client id 부분을 바꿀 수 없게 되어 한 유저에 대한 처리만 수행할 수 있을 것 같습니다!

2024-07-24 21:53 UTC, BaeJunH0 commented on src/main/java/gift/service/KakaoUserService.java
> +        return loginUrl;
아... StringBuffer를 쓰는 이유를 이해했습니다! final로 만들어도 되겠네요! 조언 감사합니다!

2024-07-24 21:57 UTC, BaeJunH0 commented on src/main/java/gift/service/OrderService.java
> +        );
생성자 매개변수를 삭제하고 생성자 내부에서 이를 처리하도록 바꿨습니다!

2024-07-24 21:57 UTC, BaeJunH0 commented on src/main/java/gift/DTO/Kakao/Commerce.java
> +    private int regular_price;
적용 완료 했습니다!!

2024-07-24 22:01 UTC, BaeJunH0 commented on .gitignore
> +src/main/resources/secret.properties
그런데 이 방식과 새로운 properties 파일 사용 사이에 어떤 차이가 있나요? 
둘 다 동일하게 민감한 정보를 숨기는 역할을 한다면, **단순하게 파일을 새로 만드는 것**보다 **앞으로도 계속 쓸 수 있게 개발한경에 저장하는 것**을 더 편리하다고 보아서 해당 방식 사용을 제시해주신 것 인가요?

2024-07-24 22:07 UTC, BaeJunH0 commented on src/main/java/gift/DTO/Kakao/Content.java
> +    private String image_url;
적용했습니다!!

2024-07-24 22:08 UTC, BaeJunH0 commented on src/main/java/gift/security/KakaoTokenProvider.java
> +        userRepository.save(user);
클래스 별로 역할을 잘 생각해서 메서드를 분할했습니다!
앞으로 처음 설계할 때 좀 더 생각해보아야 할 사항인 것 같습니다!
조언 감사합니다!

2024-07-24 22:22 UTC, BaeJunH0 commented
우선 예외 처리와 테스트 코드 이외 부분 피드백 반영했습니다!
확실히 제가 모르거나 신경을 못 쓴 부분이 많다는 것을 많이 느낍니다!

@Value 어노테이션을 이용하여 값을 동적으로 받는 부분은 모두 final로 불변한 변수로 변경하고 생성자에서 값을 주입받을 때 최초로 한 번만 대입하는 방식으로 변경했습니다!

API 통신을 위한 DTO 클래스 필드도 컨벤션에 맞게 수정하고, 참고하라고 보내주신 글 읽고 이를 이용해서 API 사양에 맞게 값을 전달하도록 바꾸었습니다!
외부 API에 전달할 값이라서 무작정 문서만 보고 변수명을 결정해서 그랬던 것 같습니다! 지적 감사합니다!

Kakao 기능을 추가하면서 TokenProvider와 Service 이 두 가지 새로운 클래스를 만들면서 저도 좀 혼란스러운 부분이 많았던 것 같습니다, 그래서 메서드도 역할에 맞게 안들어가고 좀 뒤죽박죽이었던 것 같은데, 멘토님이 "역할" 이라는 키워드 주셔서 잘 수정할 수 있었던 것 같습니다.

도메인 클래스 내부에서 로직을 처리하는 부분은 계속 생각하면서 해야할 것 같습니다, 라이브 코딩 때나, 멘토님이 setter 지양하라고 해서 바꾸던 기억이 있어도 뭔가 일차원적으로 계속 만들게 되는 것 같습니다 ㅠㅠ

인텔리제이의 편의 기능은 분명 좋지만 한 번 쯤 검토해봐야 할 것 같습니다, 자동 생성 메서드가 기본 값이 static인지... static으로 들어가버렸군요...

과제가 진행될수록 여러모로 배워가는 게 많다고 느껴지는 요즘입니다.
이렇게 길게 피드백에 대해 코멘트 남기는 것도 처음인 것 같은데, 좋은 것 같습니다, 앞으로는 이렇게 혼자서 정리하는 시간도 가질겸 피드백 반영이나 궁금한 점 코멘트나 DM 남기겠습니다.

일단 당장 할 수 있는 부분은 구현이나 수정완료 한 것 같습니다, 그런데 제가 이번 주에 빠질 수 없는 개인 일정이 있어서... 아마 금요일 늦은 밤에나 다음 부분 진행할 수 있을 것 같습니다.... 죄송합니다 ㅠㅠ
이번 주 내로 꼭 예외 사항에 대한 부분과 구현 못한 Service 클래스에 대한 테스트 ( Order와 Kakao ) 진행하고, Controller 클래스에 대한 테스트까지 진행해보겠습니다!
개인적인 일도 이번 주 금요일이면 마무리 되어서 step 2도 앞으로 정말 조금 남았지만... ㅎㅎ 끝까지 열심히 과제 수행하고 남은 시간 멘토님한테도 많이 물어보면서 유종의 미 거두겠습니다! 
매번 제가 생각 못한 부분 짚어주시고, 레퍼런스도 제공해주셔서 감사합니다! 말씀은 안드렸지만 개인 노션에 다 정리하고 있습니다!!
앞으로도 잘 부탁드립니다!!

2024-07-26 07:52 UTC, lsm7179 commented
> 우선 예외 처리와 테스트 코드 이외 부분 피드백 반영했습니다! 확실히 제가 모르거나 신경을 못 쓴 부분이 많다는 것을 많이 느낍니다!
> 
> @value 어노테이션을 이용하여 값을 동적으로 받는 부분은 모두 final로 불변한 변수로 변경하고 생성자에서 값을 주입받을 때 최초로 한 번만 대입하는 방식으로 변경했습니다!
> 
> API 통신을 위한 DTO 클래스 필드도 컨벤션에 맞게 수정하고, 참고하라고 보내주신 글 읽고 이를 이용해서 API 사양에 맞게 값을 전달하도록 바꾸었습니다! 외부 API에 전달할 값이라서 무작정 문서만 보고 변수명을 결정해서 그랬던 것 같습니다! 지적 감사합니다!
> 
> Kakao 기능을 추가하면서 TokenProvider와 Service 이 두 가지 새로운 클래스를 만들면서 저도 좀 혼란스러운 부분이 많았던 것 같습니다, 그래서 메서드도 역할에 맞게 안들어가고 좀 뒤죽박죽이었던 것 같은데, 멘토님이 "역할" 이라는 키워드 주셔서 잘 수정할 수 있었던 것 같습니다.
> 
> 도메인 클래스 내부에서 로직을 처리하는 부분은 계속 생각하면서 해야할 것 같습니다, 라이브 코딩 때나, 멘토님이 setter 지양하라고 해서 바꾸던 기억이 있어도 뭔가 일차원적으로 계속 만들게 되는 것 같습니다 ㅠㅠ
> 
> 인텔리제이의 편의 기능은 분명 좋지만 한 번 쯤 검토해봐야 할 것 같습니다, 자동 생성 메서드가 기본 값이 static인지... static으로 들어가버렸군요...
> 
> 과제가 진행될수록 여러모로 배워가는 게 많다고 느껴지는 요즘입니다. 이렇게 길게 피드백에 대해 코멘트 남기는 것도 처음인 것 같은데, 좋은 것 같습니다, 앞으로는 이렇게 혼자서 정리하는 시간도 가질겸 피드백 반영이나 궁금한 점 코멘트나 DM 남기겠습니다.
> 
> 일단 당장 할 수 있는 부분은 구현이나 수정완료 한 것 같습니다, 그런데 제가 이번 주에 빠질 수 없는 개인 일정이 있어서... 아마 금요일 늦은 밤에나 다음 부분 진행할 수 있을 것 같습니다.... 죄송합니다 ㅠㅠ 이번 주 내로 꼭 예외 사항에 대한 부분과 구현 못한 Service 클래스에 대한 테스트 ( Order와 Kakao ) 진행하고, Controller 클래스에 대한 테스트까지 진행해보겠습니다! 개인적인 일도 이번 주 금요일이면 마무리 되어서 step 2도 앞으로 정말 조금 남았지만... ㅎㅎ 끝까지 열심히 과제 수행하고 남은 시간 멘토님한테도 많이 물어보면서 유종의 미 거두겠습니다! 매번 제가 생각 못한 부분 짚어주시고, 레퍼런스도 제공해주셔서 감사합니다! 말씀은 안드렸지만 개인 노션에 다 정리하고 있습니다!! 앞으로도 잘 부탁드립니다!!

열심히 해주셔서 저도 힘이 나네요.얼마든지 궁금한점 물어보세요. 물론 저도 다 아는건 아닙니다. ㅎㅎ 
"역할"에 대해선 조영호저자의 오브젝트 ,객체지향 사실과 오해 책들을 보면 더 이해하기 쉬울겁니다.

리뷰할때 많은 내용을 전달하게 되면 오히려 생각할 여지를 뺏는거 같아서 레퍼런스만 주고 고민 하게끔 유도 했습니다.
이런 부분이 불편 할 수 있지만 잘 해내고 계신거 같아요. 
지금 하고 있는 단계가 벅차다고 있다고 생각 할 수 있어요. 다만 지나고 나면 어느새 성장해 있는 자신을 마주하게 될거에요.
마지막까지 같이 화이팅해봐요.

2024-07-26 07:55 UTC, lsm7179 commented on .gitignore
> +src/main/resources/secret.properties
음.. 예를 들어 id,pw 를 숨기는 것과 pw를 숨기는것 중 어떤게 협업하기 수월할까요? 
여러사람이 앞으로도 계속 쓴다는 관점으로 생각해보면 좋을 거 같아요 😁
위에 전달해준 방법으로 하게 되면 properties에 key값이 있어서 어떤key값을 어디서 사용하는지 value값를 알지 못해도 알 수 가 있으니깐요.

2024-07-26 08:25 UTC, lsm7179 approved these changes
준호님 과제 수고하셨습니다.
간단한 피드백 남겼는데 보시고 반영해주세요~

2024-07-26 08:25 UTC, lsm7179 commented on src/main/java/gift/domain/Order.java
> +        this.orderDateTime = now.format(formatter);
👍
jpa에서는 시간에 대해서 자동으로 값을 넣어 주는 기능이 있습니다.
https://docs.spring.io/spring-data/jpa/reference/auditing.html

2024-07-26 08:25 UTC, lsm7179 commented on src/main/java/gift/service/OrderService.java
> +        }
아직 정리가 안되었네요~😨

2024-07-26 08:25 UTC, lsm7179 commented on src/main/java/gift/service/OrderService.java
> +public class OrderService {
`OrderService` test 코드 작성해주세요.

2024-07-26 08:25 UTC, merged

2024-07-27 10:35 UTC, BaeJunH0 commented on src/main/java/gift/domain/Order.java
> +        this.orderDateTime = now.format(formatter);
적용했습니다!!