강원대 BE_안승환 5주차(1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #174
Opened 2024-07-24 13:03 UTC by Awhn

1단계 수행한 내용입니다. 기능 요구 사항의 "카카오 로그인을 통해 인가 코드를 받고, 인가 코드를 사용해 토큰을 받은 후 향후 카카오 API 사용을 준비한다."가 좀 모호하여서, 일단 로그인을 통해 토큰을 받는 것 내용까지 구현하였습니다.

중요한 정보는 application.properties에 저장하고 git에서는 제외하였습니다.

2024-07-25 13:07 UTC, jaymarystella requested changes
안녕하세요
1단계 코드양은 많지 않네요 
간단한 부분 몇가지만 봐주시면 될것같습니다.

2024-07-25 13:07 UTC, jaymarystella commented on src/main/java/gift/controller/KakaoLoginController.java
> +        return ResponseEntity.ok("토큰을 받았습니다.");
응답코드가 있기 때문에 string본문은 필요없을것같습니다.

2024-07-25 13:07 UTC, jaymarystella commented on src/main/java/gift/domain/KakaoLoginProperties.java
> +    }
properties에 대한 set은 필요없지 않을까요?

2024-07-25 13:07 UTC, jaymarystella commented on src/main/java/gift/service/KakaoLoginService.java
> +        return kakaoTokenResponseDTO.getAccessToken();
메서드의 길이를 줄여볼 방법을 찾아보면 좋을것 같습니다.

2024-07-25 14:21 UTC, Awhn commented on src/main/java/gift/controller/KakaoLoginController.java
> +        return ResponseEntity.ok("토큰을 받았습니다.");
넵 브라우저로 간단하게 확인해보려고 추가했었습니다. 불필요하여서 삭제했습니다!

2024-07-25 14:45 UTC, Awhn commented on src/main/java/gift/service/KakaoLoginService.java
> +        return kakaoTokenResponseDTO.getAccessToken();
body 부분을 getBody 메서드로 분리하였습니다.

2024-07-25 14:45 UTC, Awhn commented on src/main/java/gift/service/KakaoLoginService.java
> +        return kakaoTokenResponseDTO.getAccessToken();
url을 불필요하게 변수라 삽입하지 않고 직접 값을 전달하도록 수정하였습니다.

2024-07-25 15:02 UTC, Awhn commented on src/main/java/gift/domain/KakaoLoginProperties.java
> +    }
막연하게 reflection api에서 필요할 거라 생각했습니다. [참고](https://programmersought.com/article/25581101625/)해보니 값을 넣는 과정에서 따로 메서드 선언은 필요 없는 거 같아 삭제하였습니다.

2024-07-26 23:54 UTC, jaymarystella approved these changes
안녕하세요
리뷰반영 잘해주셨습니다. 다음단계에서 뵐게요~

2024-07-26 23:54 UTC, merged