경북대 BE_우현서 5주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #178
Opened 2024-07-24 14:34 UTC by wndlthsk

RestClient를 사용하여 카카오 로그인 구현하였습니다!
kakao.client_id, kakao.redirect_uri은 application-secret.properties에 따로 두었습니다. 이렇게 숨겨두면 되는지 조언 부탁드립니다

2024-07-24 15:35 UTC, leaf-upper requested changes
안녕하세요 현서님
몇가지 코멘트를 드렸는데요~ 확인해주시고 코멘트드린대로 
OAuth를 구현해보시면 좋을것 같아요~!
👍 👍 궁금한점있으시면 코멘트 부탁드립니다~

2024-07-24 15:35 UTC, leaf-upper commented on src/main/java/gift/controller/KakaoLoginPageController.java
> +    @Value("${kakao.client_id}")
넵 clientId랑 redirectUri는 외부 환경변수 혹은 외부파일로 바인딩 받는건 잘 해주신것 같아요~
관련 값들은 별도 클래스를 선언해서 바인딩 받는것도 좋을것 같아요!
KakaoAuthProperties <- 이런 클래스 네이밍으로 `@ConfigurationProperties`을 알아보시고 사용해보시면 좋을것 같습니다.

2024-07-24 15:35 UTC, leaf-upper commented on src/main/java/gift/controller/KakaoLoginPageController.java
> +        String location = "https://kauth.kakao.com/oauth/authorize?response_type=code&client_id="+client_id+"&redirect_uri="+redirect_uri;
사용자가 LoginPage를 요청했을때 지금 작성해주신 location으로 사용자를 redirect 해보는건 어떨까요?

1. 사용자가 애플리케이션 서버로 로그인 페이지 요청
2. 애플리케이션 서버에서 kauth 페이지로 사용자를 302 redirect
3. 사용자는 해당 페이지에서 로그인하고, 카카오에서는 로그인이 성공하면 해당 사용자를 다시 애플리케이션으로 redirect (이때 code를 줌.)
4. 애플리케이션 서버에서는 이 code를 기반으로 다시 access token 요청, 사용자 정보 요청 등등 진행
위 Flow대로 OAuth Protocol을 한번 개발진행해보면 좋을것 같아요

2024-07-24 15:35 UTC, leaf-upper commented on src/main/java/gift/controller/KakaoLoginController.java
> +    public ResponseEntity<KakaoInfo> kakaoLogin(@RequestParam("code") String code) {
카카오 서버가 현서님이 작성해주신 애플리케이션 서버로 redirect를 해줄텐데요~ 지금 코드상으로는 "/kakao"가 redirectUri가 될것 같아요.

2024-07-24 15:35 UTC, leaf-upper commented on src/main/java/gift/service/KakaoService.java
> +        MultiValueMap<String, String> body = new LinkedMultiValueMap<String, String>();
👍 👍 되게 깔끔하게 코드작성을 잘진행해주셨네요~

2024-07-24 15:35 UTC, leaf-upper commented on src/main/java/gift/service/KakaoService.java
> +        System.out.println("responseBody : " +responseBody);
stdout 로그보다는 Logging Framework를 이용해서 애플리케이션 로그를 남기는것도 좋은 공부가 될것같아요

2024-07-24 15:35 UTC, leaf-upper commented on src/main/java/gift/domain/Product.java
> +        Option option = getOptionByName(optionName);
👍반영 감사합니다.

2024-07-26 16:18 UTC, wndlthsk commented
2단계도 추가하였습니다!
2단계 진행하면서 코드 정리를 못하였는데 추후에 계속 정리하도록 하겠습니다. 멘토링때 코멘트 주신 부분도 아직 다 반영하지 못하였습니다.! 이것도 주말동안 추가하겠습니다.

1. 카카오 사용자 정보를 Member에 넣으면서 id에 카카오에서 받은 id를 넣었는데, 이렇게 되면 Member에서 자동 생성되는 id와 겹칠 수도 있을 거 같습니다. 카카오에서 받은 id를 따로 저장하고 id는 자동 생성되는 것으로 두는 게 맞을까요?
2. 주문하기 구현하면서 메시지 전송까지 구현은 하였는데 뭔가 맞는 흐름인진 잘 모르겠습니다.. 
3. [docs : step3 구현 기능 목록](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-order/pull/178/commits/37e413fa897827d888918c1f13d53d7d48c0b6f7) 여기 step3는 오타입니다 ..!! step2입니다.

2024-07-28 11:25 UTC, leaf-upper approved these changes
👍 👍 
2단계까지 구현잘 진행해주셨고 3단계진행 부탁드려요~! 고생하셨습니다 현서님

2024-07-28 11:25 UTC, leaf-upper commented on src/main/java/gift/config/KakaoAuthProperties.java
> +public class KakaoAuthProperties {
👍 👍 
Application에 이미 `@ConfigurationScan`애너테이션을 붙여주셨기 때문에 여기서는 붙이지 않아도 좋을것 같아요.
final 키워드를 통해서 필드를 불변으로 관리하면 더 좋을것 같습니다

2024-07-28 11:25 UTC, leaf-upper commented on src/main/java/gift/controller/KakaoLoginController.java
> +    public ResponseEntity<JwtResponse> kakaoLogin(@RequestParam("code") String code) {
메서드 이름은 동사로 시작하면 좋을것 같아요~!

2024-07-28 11:25 UTC, leaf-upper commented on src/main/java/gift/controller/KakaoLoginPageController.java
> +    public RedirectView redirectLoginPage() {
👍 👍

2024-07-28 11:25 UTC, leaf-upper commented on src/main/java/gift/controller/OrderController.java
> +        productService.decreaseOptionQuantity(orderRequestDto.productId(), orderRequestDto.optionId(),orderRequestDto.quantity());
OrderService내에서 재고 처리 및 위시리스트 삭제관련 로직, 주문 메세지 발송등의 로직을 작성해서 "주문 비즈니스 로직"을 만들 수 있을것 같아요.

2024-07-28 11:25 UTC, leaf-upper commented on src/main/java/gift/controller/OrderController.java
> +        productService.decreaseOptionQuantity(orderRequestDto.productId(), orderRequestDto.optionId(),orderRequestDto.quantity());
참고해서 `@Transactional`도 한번 사용해보면 좋을것 같아요!~

2024-07-28 11:25 UTC, leaf-upper commented on src/main/java/gift/domain/Order.java
> +    private Long optionId;
Order에 productId도 있으면 좋을것 같아요~

2024-07-28 11:25 UTC, leaf-upper commented on src/main/java/gift/domain/Order.java
> +    private LocalDateTime orderDateTime;
orderDateTime보다 createdAt은 어떨까요?

2024-07-28 11:25 UTC, leaf-upper commented on src/main/java/gift/domain/Order.java
> +    public Order() {
생성자 접근제어자를 protected로 하면 좋을것 같아요

2024-07-28 11:25 UTC, merged