강원대 BE_김송목 5주차 과제(Step 1)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #179
Opened 2024-07-24 14:55 UTC by kimsongmok

카카오 로그인 구현했습니다
로그인 성공시 로그인 성공 페이지 나오게끔 했습니다.

2024-07-25 13:11 UTC, jaymarystella requested changes
안녕하세요
간단한 내용 몇가지만 봐주시면 될 것 같습니다.

2024-07-25 13:11 UTC, jaymarystella commented on src/main/java/gift/config/AppConfig.java
> +    return new RestTemplate();
기본설정으로 어떤것들이 들어가는지 살펴보시면 좋을것같습니다.

2024-07-25 13:11 UTC, jaymarystella commented on src/main/java/gift/service/KakaoService.java
> +            .substring(1);
메서드분리를 통해서 길이를 줄여볼까요?

2024-07-25 13:11 UTC, jaymarystella commented on src/test/java/study/TransactionTest.java
> +  private EntityManager em;
테스트하신 클래스가 들어간것같습니다.

2024-07-25 14:42 UTC, kimsongmok commented on src/test/java/study/TransactionTest.java
> +  private EntityManager em;
수업시간때 들었던거 저기에 했는데 들어간 것 같습니다. 빼겠습니다..!

2024-07-25 14:42 UTC, kimsongmok commented on src/main/java/gift/service/KakaoService.java
> +            .substring(1);
createParamsMap 생성으로 분리를 해보았으나 멘토님이 의도하신 분리가 맞는지 여쭤보고 싶습니다!

2024-07-25 14:42 UTC, kimsongmok commented on src/main/java/gift/config/AppConfig.java
> +    return new RestTemplate();
RestTemplate은 기본적으로 HTTP 요청을 쉽게 보내기 위한 유틸리티 클래스입니다.
기본 설정에는 Connection Timeout, Read Timeout 등의 설정이 포함되지 않으며, 
필요에 따라 커스터마이징 할 수 있습니다. 예를 들어, 인터셉터, 에러 처리기, 메시지 컨버터 등을 추가할 수 있습니다!

2024-07-26 23:53 UTC, jaymarystella commented
이거 PR이 closed를 하신거같습니다. 다시 열어주세요!

2024-07-27 11:46 UTC, jaymarystella commented on src/main/java/gift/service/KakaoService.java
> +            .substring(1);
넵 맞습니다!

2024-07-27 11:46 UTC, jaymarystella approved these changes
리뷰반영하느라 고생하셨습니다.
다음 단계 진행해주세요!

2024-07-27 11:46 UTC, merged