부산대 BE_원윤서 5주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #184
Opened 2024-07-24 16:15 UTC by yoonsu0325

2단계 주문하기 구현했습니다!
1. 현재 나에게 메시지 보내기 API를 사용할 때, 처음에는 TemplateObject, Content 등(커밋에서 Message Template)을 사용해서 body를 넣으려고 했는데 401에러가 발생해서 일단은 문자열로 통째로 집어넣었더니 동작은 되고 있습니다... 좀 더 깔끔하게 보낼 수 있는 방법이 없을까요...? 우선 이전에 시도했던 코드는 주석처리 해두었습니다!
2. 카카오 로그인을 한 경우에 새로 회원가입을 하도록 코드를 작성했는데 따로 리포지토리를 만들고 다시 연관관계 매핑하기가 번거로울 것 같아서 그냥 KakaoUser 안에 User를 넣어버렸는데 다시 KakaoUser를 만들어서(User 빼고) 리포지토리 만드는편이 나을까요?

2024-07-25 23:20 UTC, yoo-jaein requested changes
step2 고생하셨습니다!
질문에 대한 답변은 리뷰 코멘트로 남겼으니 확인해주세요 :)

2024-07-25 23:20 UTC, deactivated-user commented on src/main/java/gift/kakaoLogin/KakaoLoginService.java
> +        System.out.println(response.getBody());
System.out.println 대신 로깅 프레임워크(SLF4J, Logback..)를 사용하는 것이 좋습니다!

2024-07-25 23:20 UTC, deactivated-user commented on src/main/java/gift/kakaoLogin/KakaoUserInfoResponse.java
> +    String connected_at;
기존 코드 컨벤션인 카멜 케이스를 유지해주세요!

2024-07-25 23:20 UTC, deactivated-user commented on src/main/java/gift/kakaoLogin/KakaoUserInfoResponse.java
> +    String connected_at;
Jackson 라이브러리를 사용하면 Json 응답의 필드명과 자바 클래스 필드명을 다르게 설정할 수 있습니다!
```java
    @JsonProperty("connected_at")
    private String connectedAt;
```
- https://dev-jwblog.tistory.com/120 참고

2024-07-25 23:20 UTC, deactivated-user commented on src/main/java/gift/order/OrderService.java
> +        String send = "{\n" +
### 답변 1번
json 문자열을 직접 생성하는 대신 객체를 사용하고 Jackson 라이브러리로 직렬화하는 것이 안전합니다! 👀
- https://tychejin.tistory.com/134 참고

2024-07-25 23:20 UTC, deactivated-user commented on src/main/java/gift/user/KakaoUser.java
> +@Table(name = "KAKAOUSERS")
### 답변 2번
kakaousers와 users를 분리하셨군요!
카카오 사용자 정보와 사용자 정보라는 관점에서 엔티티의 관심사, 책임이 명확하네요.

다만 KakaoUser는 User의 한 종류이기 때문에 KakaoUser와 User 엔티티를 1:1 관계로 설정할 수 있을 것 같아요.

```java
// KakaoUser
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user; //
```

그리고 User에는 이 사용자가 어떤 사용자 타입인지 구분하는 필드가 있어도 괜찮겠네요.

```java
// User
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, nullable = false)
    private String email;

    @Column
    private String password;

    @Column
    private String name;

    @Enumerated(EnumType.STRING)
    @Column(name = "user_type", nullable = false)
    private UserType userType; //
```

그리고 비즈니스 로직에서는 User와 KakaoUser를 추상화한 IntegratedUser 인터페이스를 사용해서 코드 결합도를 낮출 수 있을 것 같아요.

```java
public interface IntegratedUser {
    Long getId();
    String getEmail();
    String getPassword();
    String getNickname();
    UserType getUserType();
    // 필요에 따라 추가 메서드 정의
}
```

```java
public class User implements IntegratedUser { ... }
public class KakaoUser implements IntegratedUser { ... }
// KakaoUser의 email, nickname 등은 연관된 User 객체에서 가져옴
```

마지막으로 ```@LoginUser```에서 IntegratedUser를 반환하도록 수정하면 기존 User 코드 구조를 크게 변경하지 않고도 KakaoUser를 지원할 수 있을 것 같습니다!

2024-07-25 23:20 UTC, deactivated-user commented on src/main/java/gift/user/KakaoUser.java
> +public class KakaoUser {
### 답변 3번
kakaousers, users 별로 모든 컨트롤러를 따로 구현하는 방법은 공수가 많이 들 것 같네요. 우선 현재 요구사항대로 주문 기능에 대해서만 kakaousers를 지원하도록 하면 충분할 것 같아요!

2024-07-26 06:43 UTC, yoonsu0325 commented
Jackson 사용하니까 확실히 코드가 깔끔해지고 좋네요😚

2024-07-27 03:35 UTC, yoo-jaein approved these changes
리뷰 반영된 것 확인했습니다!
머지하겠습니다 :)

2024-07-27 03:35 UTC, yoo-jaein commented
그쵸? 실무에서도 Jackson 꼭 사용한답니다 ㅎㅎ

2024-07-27 03:35 UTC, merged