전남대 BE_모아림 5주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #192
Opened 2024-07-24 20:25 UTC by ariimo

안녕하세요 멘토님 이번 주 잘 부탁드리겠습니다!

우선, kakao.client.id 부분은 필요하실 때, DM 연락을 주신다면 바로 보내드리도록 하겠습니다!
또한, 현재 외부 API를 활용하는 Test를 공부하고 있습니다. 허락해 주신다면 다음 스텝에서 구현하고 싶습니다.

2024-07-26 04:44 UTC, dc-choi requested changes
안녕하세요 아림님!

OAuth2라는 개념이 생소하면 어려울 수 있는데 잘 구현해주셨군요!

자세한 내용은 코멘트에 적어두었습니다. 확인 부탁드려요~!

2024-07-26 04:44 UTC, dc-choi commented on src/main/java/gift/services/KaKaoService.java
> +    private final static String KAKAO_AUTH_URI = "https://kauth.kakao.com";
이 부분도 propoerties에 넣는건 어떨까요?

보안상의 이유도 있지만 추후에 변경에 용이하게 처리하려면 propoerties에 환경변수 처리하는게 나아보입니다.

2024-07-26 04:44 UTC, dc-choi commented on src/main/java/gift/services/KaKaoService.java
> +    private final static String KAKAO_API_URI = "https://kapi.kakao.com";
이 부분도 마찬가지로 propoerties에 넣는건 어떨까요?

2024-07-26 04:44 UTC, dc-choi commented on src/main/java/gift/services/KaKaoService.java
> +        return KAKAO_AUTH_URI + "/oauth/authorize"
`KAKAO_AUTH_URI`에 /oauth/authorize를 넣어주세요.

그리고 추후 API EndPoint가 변경되는 경우 변경에 용이하게 하기 위해

1. 인가코드를 받아오는 API
2. Kakao Access Token을 받아오는 API

이렇게 따로 propoerties에 두는건 어떨까요?

2024-07-26 04:44 UTC, dc-choi commented on src/main/java/gift/services/KaKaoService.java
> +        try {
API에 대한 예외처리를 따로 신경써주신 부분이 좋습니다! 굿!

2024-07-26 04:44 UTC, dc-choi commented on src/main/java/gift/services/KaKaoService.java
> +            RestTemplate restTemplate = new RestTemplate();
`RestTemplate`을 사용하셨군요!

`RestTemplate`와 `RestClient`, `WebClient`의 차이점에 대해서 알고 계시나요?

2024-07-26 04:44 UTC, dc-choi commented on src/main/java/gift/services/KaKaoService.java
> +                KAKAO_AUTH_URI + "/oauth/token",
위에서 이야기 했던 부분에 대한 고민을 해봐주세요!

2024-07-26 04:44 UTC, dc-choi commented on src/main/java/gift/services/KaKaoService.java
> +        return accessToken;
`accessToken`과 `refreshToken`을 가져오는데 현재 `refreshToken`은 사용하지 않고 있습니다.

의도하신 부분일까요?

2024-07-26 04:44 UTC, dc-choi commented on src/main/java/gift/services/KaKaoService.java
> +    private KaKaoUserDto getUserInfoWithToken(String accessToken) throws Exception {
이 부분은 사용되지 않는 것으로 보이는데 혹시 어떤 의도로 작성되었는지 알 수 있을까요?

2024-07-26 07:09 UTC, ariimo commented on src/main/java/gift/services/KaKaoService.java
> +        return KAKAO_AUTH_URI + "/oauth/authorize"
나름 KAKAO_AUTH_URI와 KAKAO_API_URI 의 형식을 맞춘다는 생각이었는데, 기능 측면에서 접근하는 게 더 적절하군요! 수정하겠습니다!

유지보수나 가독성을 위해 properties에 각 URI를 넣는다는 것을 확인했습니다. 이 부분도 수정하겠습니다!!

2024-07-26 07:09 UTC, ariimo commented on src/main/java/gift/services/KaKaoService.java
> +    private final static String KAKAO_AUTH_URI = "https://kauth.kakao.com";
수정했습니다 :)

2024-07-26 07:10 UTC, ariimo commented on src/main/java/gift/services/KaKaoService.java
> +    private final static String KAKAO_API_URI = "https://kapi.kakao.com";
수정했습니다 :)

2024-07-26 07:10 UTC, ariimo commented on src/main/java/gift/services/KaKaoService.java
> +                KAKAO_AUTH_URI + "/oauth/token",
수정했습니다 :)

2024-07-26 07:22 UTC, ariimo commented on src/main/java/gift/services/KaKaoService.java
> +        return accessToken;
토큰에 대해 공부하며 사용자가 로그인하면 accessToken과 refreshToken 을 모두 받는다는 사실을 알게 되었습니다. 
따라서 이 둘을 모두 받아오게 구현했지만 당장은 accessToken 만 사용할 것 같아 우선 accessToken 만 return 하도록 만들었습니다. (Refresh Token 인증 과정은 요구사항에 존재하지 않아 형식상으로만 남겨둘 것 같긴 합니다..!)

제가 아직 refresToken 부분을 공부하지 않아서 그러는데, accessToken과 refreshToken을 함께 return 하는 게 일반적인 방식일까요??

2024-07-26 11:20 UTC, ariimo commented on src/main/java/gift/services/KaKaoService.java
> +    private KaKaoUserDto getUserInfoWithToken(String accessToken) throws Exception {
자료를 찾다가, 토큰을 통해 사용자 정보를 가져올 수 있다는 것을 알게되었고 이를 구현해 본 코드입니다. kakao developers에서 따로 설정한다면 이메일이나 닉네임 또한 가져올 수 있는 것으로 알고있습니다!

2024-07-26 12:03 UTC, ariimo commented on src/main/java/gift/services/KaKaoService.java
> +            RestTemplate restTemplate = new RestTemplate();
RestTemplate은 스프링 내에서 객체로 API 를 호출할 수 있게 해줍니다. 이전에 테스트를 작성하며 RestTemplate를 사용해 본 경험이 있어 자연스럽게 사용하게 된 것 같습니다! 

멘토님의 질문에 답하기 위해 RestTemplate와 RestClient,  RestTemplate의 차이점을 공부해보았습니다. 

우선 위 3가지 모두 RESTful 웹 서비스를 호출에 사용됩니다. 
1)  RestTemplate: 동기 방식으로만 작동하여, 요청을 보내고 응답을 받을 때까지 블로킹됩니다. 특정 클래스에 모든 HTTP 기능을 노출하는 것이 부담을 준다는 단점을 가집니다. 
2) WebClient: 위와 같은 RestTemplate의 단점을 극복합니다. WebFlux에 기반한 비동기 HTTP Client로 기존 동기 방식과 더불어 비동기 방식으로도 작동합니다. RestTemplate과 달리 Non-blocking 방식으로 진행하기에 네트워크 관련 병목현상을 줄일 수 있습니다. spring MVC를 기본적으로 제공하지 않기에 springWebFlux 라이브러리를 별도로 추가해야 하는 단점을 가집니다. 
3) RestClient: 동기 방식으로 작동하며 WebClient의 fluent API와 RestTemplate의 인프라를 결합한 형태입니다.

2024-07-27 04:02 UTC, dc-choi commented on src/main/java/gift/services/KaKaoService.java
> +        return accessToken;
일단 현 시스템에서 refresToken을 로직에서 가져온 후 클라이언트에 반환하지 않는 부분이 의문이 들어 말씀드렸었습니다.

refreshToken에 대해서 잠깐 설명을 드리자면...

JWT를 이용한 토큰 인증 방식의 단점은 토큰이 유출되면 서버에서 해당 토큰을 파기할 방법이 없습니다.

그래서 기존 토큰의 단점을 어느정도 보완한 것이 refreshToken을 사용하는 것입니다.

2024-07-27 04:03 UTC, dc-choi commented on src/main/java/gift/services/KaKaoService.java
> +    private KaKaoUserDto getUserInfoWithToken(String accessToken) throws Exception {
현재 사용되지 않는 부분은 없어도 된다는 생각입니다!

2024-07-27 04:06 UTC, dc-choi requested changes
안녕하세요 아림님~! 피드백 남겨드렸습니다!

해당 부분만 수정되면 크게 문제가 될 부분은 없어보이네요~

2024-07-27 04:10 UTC, ariimo commented on src/main/java/gift/services/KaKaoService.java
> +        return accessToken;
accessToken만 받아오도록 수정했습니다!

2024-07-27 04:11 UTC, ariimo commented on src/main/java/gift/services/KaKaoService.java
> +    private KaKaoUserDto getUserInfoWithToken(String accessToken) throws Exception {
넵 사용하지 않는 부분은 제거하도록 수정하겠습니다 :)

2024-07-27 04:42 UTC, dc-choi approved these changes
코드가 참 깔끔해서 좋네요! 바로 step2 과제 진행해주시면 될 거 같습니다!

고생하셨습니다!

2024-07-27 04:42 UTC, merged