경북대 BE_정성훈 5주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #196
Opened 2024-07-25 01:13 UTC by zzoe2346

2024-07-28 14:45 UTC, sang5c requested changes
테스트 코드와 REST Docs 적용까지! 👍👍  

현재 크게 수정할 부분은 없지만, 중요한 부분이 빠져있어 리뷰 남겼습니다.  
강의 자료의 힌트를 꼭 읽어보시고 적용해주세요 :)

2024-07-28 14:45 UTC, sang5c commented on src/main/java/gift/controller/api/OrderController.java
> +    }
작성해주신 코드에 따르면 주문 생성 과정에서 수행해야 하는 로직은
1. 주문을 생성하고
2. 옵션 수량을 차감한 다음
3. 위시리스트에서 제거 후
4. 카톡 메시지를 보낸다

로 보입니다!

이를 컨트롤러가 아닌 서비스 레이어에서 수행해보면 어떨까요?

2024-07-28 14:45 UTC, sang5c commented on src/main/java/gift/client/requestBody/KakaoMessageRequestBodyGenerator.java
> +            Logger.getLogger(KakaoMessageRequestBodyGenerator.class.getName()).log(Level.WARNING, "ObjectMapper가 JSON 파싱에 실패");
이렇게 사용하면 안되는 것은 아닌데,  
주로 전역 변수로 로거를 만들어두고 사용하는 편입니다.  
```
private static final Logger log = LoggerFactory.getLogger(KakaoMessageRequestBodyGenerator.class);
```

2024-07-28 14:45 UTC, sang5c commented on src/main/java/gift/client/requestBody/KakaoMessageRequestBodyGenerator.java
> +    private String message;
스프링 빈으로 등록된 객체에 멤버 변수를 두고 setter를 통해 값을 제어하면, 여러 사용자가 동시 사용시 문제가 발생할 수 있습니다.  
빈으로 사용하기 위해선 thread-safe하게 사용해야 해요!

2024-07-28 14:45 UTC, sang5c commented on src/main/java/gift/client/KakaoApiClient.java
> +        this.restClient = builder.build();
외부 API 호출시 가장 중요한 것은 예외처리와 타임아웃에 대한 제어입니다.  
응답이 늦어져서 요청이 쌓이면 전체 서비스 장애로 이어질 수 있어요.  
추가로, 문제가 생겼을 때 상세히 로그를 남기지 않으면 유지보수에 큰 어려움이 있을 수 있습니다.  

강의 자료의 힌트, 주문하기 피드백을 자세히 읽어보시고 예외처리와 타임아웃 처리를 해주세요!

2024-07-28 14:45 UTC, sang5c commented on src/main/java/gift/repository/KakaoAccessTokenRepository.java
> +    private static final Map<Long, String> database = new HashMap<>();
database에 저장하지 않고 Map에 저장하는 이유가 있을까요? 🤔

2024-07-28 14:45 UTC, sang5c commented on src/main/java/gift/service/TokenService.java
> +        return new JwtTokenResponse(tokenValue);
JWT는 JSON Web Token입니다.  
JWT Token은 JSON Web Token Token이라고 읽히구요 😉  
https://jwt.io/introduction

2024-07-28 15:25 UTC, zzoe2346 commented on src/main/java/gift/repository/KakaoAccessTokenRepository.java
> +    private static final Map<Long, String> database = new HashMap<>();
토큰 정보는 데이터베이스에 굳이 저장하지 않아도 된다고 여겼습니다. 여기서 제가 사용한 Map은 캐시역할을 가정하고 구현해보았습니다. 로그인마다 항상 토큰을 새로 받아
아래와 같은 이유로 Map에 저장해보았습니다.
1. 토큰 정보는 영속성이 필요하지 않은 데이터라고 판단하였습니다.
    - 카카오 토큰은 6시간의 유효기간을 가지고 있습니다. 6시간뒤 쓸모없어지는 데이터를 데이터베이스 같은 IO자원요소를 많이 사용하는 곳에 저장했다 삭제했다하면 쓸데없이 DB에 과부화를 줄것이라 생각하였습니다.
    - Map은 캐시를 가정하였습니다. 매우 간단한 Key-Value Store의 역할을 부여하였습니다. Database에 비해 훨씬 적은 자원을 사용하기에 시스템의 속도 개선을 기대할 수 있습니다.

2024-07-28 15:26 UTC, zzoe2346 commented on src/main/java/gift/client/requestBody/KakaoMessageRequestBodyGenerator.java
> +    private String message;
아! 수정해보겠습니다.

2024-07-28 15:48 UTC, zzoe2346 commented on src/main/java/gift/client/requestBody/KakaoMessageRequestBodyGenerator.java
> +            Logger.getLogger(KakaoMessageRequestBodyGenerator.class.getName()).log(Level.WARNING, "ObjectMapper가 JSON 파싱에 실패");
멘토님 말씀대로 수정해보니 훨씬 가독성이 좋은것 같습니다.!

2024-07-28 15:58 UTC, zzoe2346 commented on src/main/java/gift/service/TokenService.java
> +        return new JwtTokenResponse(tokenValue);
디테일하게 체크해주셔서 감사합니다! 제대로된 명칭으로 변경하겠습니다.

2024-07-29 00:27 UTC, zzoe2346 commented on src/main/java/gift/controller/api/OrderController.java
> +    }
넵 말씀대로해보겠습니다. 컨트롤러에 너무 많은 로직이 부여된듯합니다.

2024-07-29 03:56 UTC, zzoe2346 commented on src/main/java/gift/client/KakaoApiClient.java
> +        this.restClient = builder.build();
에러 발생시 로그를 남기도록 해보았습니다! 프론트에게 보여줄수 있는 예외처리에 집중했었던거 같습니다. Log를 활용해 서버에서 에러를 확인 할 수 있도록 하였습니다.

2024-07-29 04:10 UTC, zzoe2346 commented
### 에러 발생시 로그 기능을 추가하였습니다.
```
2024-07-29T13:08:36.436+09:00 ERROR 56823 --- [spring-gift] [    Test worker] g.client.RestClientResponseErrorHandler  : [카카오API ERROR 발생] 상태코드: 504 GATEWAY_TIMEOUT Gateway Timeout, 에러응답필드: {이건 카카오 서버에서 넘겨줍니다.}
```
API관련 에러발생시 로그처리와 예외처리 둘 다 되도록 수정하였습니다.

에러 핸들 관련 코드
```
@Override
    public void handleError(ClientHttpResponse response) throws IOException {
        BufferedReader reader = new BufferedReader(new InputStreamReader(response.getBody()));
        String bodyString = reader.lines().collect(Collectors.joining(System.lineSeparator()));

        log.error(String.format("[카카오API ERROR 발생] 상태코드: %s %s, 에러응답필드: %s", response.getStatusCode(), response.getStatusText(), bodyString));

        if(response.getStatusCode().is4xxClientError()){
            throw new HttpClientErrorException(response.getStatusCode(), response.getStatusText());
        }
        if(response.getStatusCode().is5xxServerError()){
            throw new HttpServerErrorException(response.getStatusCode(), response.getStatusText());
        }
    }
```

2024-07-29 04:11 UTC, zzoe2346 commented
### 에러 발생시 로그 기능을 추가하였습니다.
```
2024-07-29T13:08:36.436+09:00 ERROR 56823 --- [spring-gift] [    Test worker] g.client.RestClientResponseErrorHandler  : [카카오API ERROR 발생] 상태코드: 504 GATEWAY_TIMEOUT Gateway Timeout, 에러응답필드: {이건 카카오 서버에서 넘겨줍니다.}
```
API관련 에러발생시 로그처리와 예외처리 둘 다 되도록 수정하였습니다.

에러 핸들 관련 코드
```
@Override
    public void handleError(ClientHttpResponse response) throws IOException {
        BufferedReader reader = new BufferedReader(new InputStreamReader(response.getBody()));
        String bodyString = reader.lines().collect(Collectors.joining(System.lineSeparator()));

        log.error(String.format("[카카오API ERROR 발생] 상태코드: %s %s, 에러응답필드: %s", response.getStatusCode(), response.getStatusText(), bodyString));

        if(response.getStatusCode().is4xxClientError()){
            throw new HttpClientErrorException(response.getStatusCode(), response.getStatusText());
        }
        if(response.getStatusCode().is5xxServerError()){
            throw new HttpServerErrorException(response.getStatusCode(), response.getStatusText());
        }
    }
```

2024-07-29 18:19 UTC, sang5c approved these changes
고생하셨습니다~!  

6주차도 파이팅입니다!

2024-07-29 18:19 UTC, sang5c commented on src/main/java/gift/repository/KakaoAccessTokenRepository.java
> +    private static final Map<Long, String> database = new HashMap<>();
지금은 한 대의 서버에서 요청을 소화하기 때문에 문제가 없지만, 서버가 여러대가 뜨는 경우 메모리에 저장되기에 각 서버간에 서로 토큰이 공유되지 않습니다 :)  
이 부분 인지해주세요~

2024-07-29 18:19 UTC, merged