전남대 BE_김수랑 5주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #200
Opened 2024-07-25 05:46 UTC by rdme0

클래스 계층구조 이렇게 구현하였습니다!

                KakaoLogisterController
                                    |
                  KakaoLogisterService
                           /              \
   KakaoTokenService     MemberService
                                              \ 
                                          MemberRepository

2024-07-27 08:09 UTC, Hongdonggeon requested changes
안녕하세요 수랑님!
미션 구현하시느라 수고 많으셨습니다
현재 어플리케이션에 기존 로그인 기능이 실패하고 있는 것 같은데요
확인 한번 해주세요
무엇보다 프로그램 구현할때 가장 중요한건 버그 없이 기능이 잘 동작하는거예요!!
코멘트들도 확인해주세요 😃

2024-07-27 08:09 UTC, Hongdonggeon commented on src/main/java/gift/util/ResponseEntityUtil.java
> +    public static final Logger logger = LoggerFactory.getLogger(ResponseEntityUtil.class);
KakaoLogisterController에서도 사용하기 위해서 접근 지정자를 public으로 열어준 것 같은데요 각자 클래스에서 선언해서 logger를 선언해서 사용해도 될 것 같아요

2024-07-27 08:09 UTC, Hongdonggeon commented on src/main/java/gift/service/MemberService.java
> +            ) { throw new UserNotFoundException("아이디 또는 비밀번호가 올바르지 않습니다."); }
이 부분때문에 로그인이 되질 않고 있습니다 
accountType이 null이여서 아이디, 비밀번호를 올바르게 입력하더라도 로그인에 실패해요 
확인 부탁드립니다 

무엇보다 가장 중요한건 프로그램을 버그 없이 요구사항에 올바르게 구현하는건데요. 버그가 자주 발견되는 것 같아요. 미션 제출하기전에 모든 기능에 대해 잘 동작하는지 테스트 후 제출 부탁드립니다

2024-07-27 08:09 UTC, Hongdonggeon commented on src/main/java/gift/service/MemberService.java
> +            ) { throw new UserNotFoundException("아이디 또는 비밀번호가 올바르지 않습니다."); }
<img width="1193" alt="image" src="https://github.com/user-attachments/assets/fa03268c-c5c1-42a0-9b60-16387b308aee">

2024-07-27 08:09 UTC, Hongdonggeon commented on src/main/java/gift/service/MemberService.java
> +            ) { throw new UserNotFoundException("아이디 또는 비밀번호가 올바르지 않습니다."); }
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/cf6d46c9-8a11-4ab8-a1c9-8366b0e2259b">

2024-07-27 08:09 UTC, Hongdonggeon commented on src/main/java/gift/controller/KakaoLogisterController.java
> +public class KakaoLogisterController {
logister라는 단어는 꽤 생소한 단어인 것 같은데, 어떤 의미를 주고 싶었던걸까요?

2024-07-27 08:09 UTC, Hongdonggeon commented on src/main/java/gift/controller/KakaoLogisterController.java
> +@PropertySource("classpath:application-secret.properties")
이 클래스에서는 이파일에 선언된 값들을 사용하고 있지 않은 것 같은데요

2024-07-27 08:09 UTC, Hongdonggeon commented on src/main/java/gift/service/KakaoTokenService.java
> +                        throw new BadRequestException("서버에서 오류가 발생하였습니다.\n" + response.getBody()
5xx 번대 응답을 받은 경우에도 badRequestException으로 예외를 던지네요
4xx 번대 응답을 받은 경우와 분리하는게 좋지 않을꺼요?

2024-07-27 08:09 UTC, Hongdonggeon commented on src/main/java/gift/service/KakaoTokenService.java
> +                        throw new BadRequestException("서버에서 오류가 발생하였습니다.\n" + response.getBody()
여기도 확인 한번 해주세요

2024-07-27 08:09 UTC, Hongdonggeon commented on src/main/java/gift/service/KakaoTokenService.java
> +    private static final String USER_INFO_URL = "https://kapi.kakao.com/v2/user/me";
이 url들도 properties 한 파일에서 관리하면 좋을 것 같아요 
이런 value들이 여러 파일에 흩어져있는 것보다 application-kakao-login.properties와 같은 한 파일에서 관리해주는게 좋을 것 같습니다

2024-07-27 08:09 UTC, Hongdonggeon commented on src/main/java/gift/service/KakaoTokenService.java
> +    @Value("${kakao-redirect-uri}")
이 값은 secret.properties에서 관리하지 않아도 될 것 같은데요 
application-kakao-login.properties 같은 파일이 생기면 이곳에서 같이 관리하는게 좋을 것 같아요

2024-07-27 08:09 UTC, Hongdonggeon commented on src/main/java/gift/service/KakaoLogisterService.java
> +@PropertySource("classpath:application-secret.properties")
이곳에서 application-secret.properties 에 선언된 값을 사용하고 있나요?

2024-07-27 08:09 UTC, Hongdonggeon commented on src/main/java/gift/service/KakaoLogisterService.java
> +                throw new BadRequestException("해당 email로 가입된 계정이 이미 존재합니다.");
카카오 로그인과 동일한 이메일로 회원가입한 적이 있으면 회원가입에 실패시키나보네요

2024-07-27 12:31 UTC, rdme0 commented on src/main/java/gift/service/MemberService.java
> +            ) { throw new UserNotFoundException("아이디 또는 비밀번호가 올바르지 않습니다."); }
아 제가 Step2 branch에서 해당 버그를 발견해서 해결했었는데 Step1에도  해당 버그가 미처 존재할 줄 몰랐습니다
죄송합니다 ㅠㅠ
현재는 해당 버그 해결 하였습니다!

2024-07-27 12:35 UTC, rdme0 commented on src/main/java/gift/controller/KakaoLogisterController.java
> +public class KakaoLogisterController {
해당 컨트롤러는 카카오 로그인 또는 회원가입을 수행하는 기능을 갖고 있습니다. 그래서 이러한 기능을 가진 컨트롤러와 서비스의 이름을 무엇으로 지을지 고민하다가 KakaoLoginOrRegisterController 또는, KakaoLoginOrRegisterService 라는 이름으로 하기엔 너무 길다고 생각하여 Login + Register인 Logister라고 이름을 짓게 되었습니다.

2024-07-27 12:43 UTC, rdme0 commented on src/main/java/gift/service/KakaoTokenService.java
> +                        throw new BadRequestException("서버에서 오류가 발생하였습니다.\n" + response.getBody()
5xx 번대 예외를 InternalServerException 으로 리팩터링 하였습니다!

2024-07-27 12:46 UTC, rdme0 commented on src/main/java/gift/service/KakaoLogisterService.java
> +                throw new BadRequestException("해당 email로 가입된 계정이 이미 존재합니다.");
맞습니다 해당 기능을 추가해서 기본 로그인이 안되는 버그가 생긴 것으로 보입니다
현재는 해당 버그를 수정하였습니다!

2024-07-27 12:47 UTC, rdme0 commented
피드백 반영하였습니다.
감사합니다!

2024-07-28 06:42 UTC, Hongdonggeon commented on src/main/java/gift/controller/KakaoLogisterController.java
> +public class KakaoLogisterController {
logister라는 단어를 만들어내는 것 보다는,
kakaoAuthcontroller, kakaoMemberController 와 같은 표현이 더 좋을 것 같아요

2024-07-28 06:43 UTC, Hongdonggeon approved these changes
수랑님 안녕하세요
미션 반영하시느라 수고 많으셨습니다!
1단계는 머지할게요~

2024-07-28 06:43 UTC, merged