경북대 BE_도기헌 5주차 과제 (1단계, 2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #202
Opened 2024-07-25 06:02 UTC by Dockerel

깃이 꼬여 해결하다보니 부득이하게 1단계, 2단계를 같이 올리게 되었습니다. 양해 부탁드립니다.
---
# 1단계
이번 1단계는 카카오 로그인을 구현하는 것이었습니다.

프론트에서 인가코드를 받고, 해당 인가코드를 백으로 fetch로 전달해주고, 백에서 액세스 토큰을 발급받아 다시 해당 토큰을 프론트로 넘겨주는 과정을 구현해보았습니다.

서비스 계층의 동작을 테스트로 구현해보려 했는데 어떤식으로 해야할지 잘 모르겠어서 구현하지 못했습니다.
만약 액세스 토큰을 잘 받아오는지 확인하거나 혹은 status code를 테스트해보려 하면 처음부터 인가 코드를 포함하여 post 요청을 보내는 것 부터 다 확인해야 할 것 같은데 이건 서비스 계층의 범위를 넘어가는 테스트 같았고 또한 애초에 인증을 하려면 제 개인정보라도 넣어야 인증이 진행이 될텐데 그런 방식으로 테스팅 하는건 올바른 방법이 아닐 것 같았습니다.
혹시 이런 인증관련 테스트 코드는 어떤식으로 작성하면 될까요?
---
# 2단계
 이번 2단계는 주문 객체를 만들어 해당 내용을 카카오톡 나에게 보내기로 보내는 것이었고 이때 1단계에서 받아온 kakaoAccessToken을 사용하였습니다.

 앱 키, 인가 코드를 숨기라고 하셔서 application-dev.properties로 따로 빼서 저장하고 .gitignore에 넣을까 했는데 리뷰하실 때 불편하실까봐 그냥 올렸습니다. 

 테스트 코드를 더 짜야 할 것 같은데 위에 1단계에서 말씀드렸던 것 처럼 어떤 식으로 짜야할지 감이 잡히지 않아 그냥 order service에 대한 테스트 코드만 간단하게 짜보았습니다. 혹시 외부 api에서 받아오는 데이터들에 대한 테스트는 어떻게 처리하시는 편일까요? 가짜 api를 만드는 선택지도 있겠지만 실제 api가 잘 작동하는지에 대한 테스트는 어떻게 진행되는지 궁금합니다.

감사합니다~!

2024-07-27 11:44 UTC, gongdongho12 requested changes
안녕하세요
5주차 과제 고생 많으셨습니다!

코드에 BeforeEach와 Map<String, String> 대한 강박관념이 녹아 있는 것 같아요
관련해서 이부분에 이렇게 쓰는걸 Default로 두고 개발하는 것 보다는
항상 어떻게 작성되어야 코드가 깔끔해질지 고민해보시는 것이 좋지 않을까 싶습니다!

> 애초에 인증을 하려면 제 개인정보라도 넣어야 인증이 진행이 될텐데 그런 방식으로 테스팅 하는건 올바른 방법이 아닐 것 같았습니다.
혹시 이런 인증관련 테스트 코드는 어떤식으로 작성하면 될까요?

저도 코드에 작성된 계정 테스트 방식으로 진행합니다!
API 레벨에서 테스트 하고 싶다면, 임시 계정을 DB에 반영해두고 그걸 POST로 요청해서 하는 방식으로 테스트 작성합니다
다만 이건 통합테스트 이다 보니 시간이 조금 걸릴 수 있는 점 참고 부탁드립니다!
그리고 테스트 어노테이션이 포함되면 자동으로 DB에 반영되었다가 롤백이 되는 구조라 별도로 본인 계정을 넣어야 한다의 고민은 따로 안하셔도 됩니다

이게 2단계 질문과 동일한 설명으로 생각됩니다!

5주차 마무리까지 화이팅입니다!

2024-07-27 11:44 UTC, gongdongho12 commented on src/main/java/gift/config/FilterConfig.java
> +        registrationBean.addUrlPatterns("/api/users/me");
이런 부분을 AOP로 빼두면 어떨까요?
매번 컨트롤러 작업하고 적용이 필요한데, 어짜피 추가하는 부분이 컨트롤러와 RequestMapper가 포함되는데, 이런 부분을 공통화하면 좋을 것 같습니다

2024-07-27 11:44 UTC, gongdongho12 commented on src/main/java/gift/controller/rest/OrderController.java
> +        }
이런 기능은 orderService에 소셜 계정 여부를 체크해서 진행하는게 좋지 않을까요?
컨트롤러에서 처리하는 것은 기능이 별도로 튀어나온 느낌을 주는 것 같습니다!

2024-07-27 11:44 UTC, gongdongho12 commented on src/main/java/gift/controller/rest/UserController.java
> +                .body(userUtility.accessTokenToObject(response.get("accessToken")));
`accessTokenToObject` 메서드를 이렇게 3개나 사용하는 부분이 있는데요
차라리 별도 클래스로 만들어 두면 어떨까요?

2024-07-27 11:44 UTC, gongdongho12 commented on src/main/java/gift/controller/rest/UserController.java
> +    }
이 부분도 Map을 그대로 쓰기 보다는 메시지 객체를 만들어 두면 좋겠죠?

2024-07-27 11:44 UTC, gongdongho12 commented on src/main/java/gift/service/UserService.java
> +        return response;
이런 부분에서 객체를 Map으로 사용해달라는 내용이 있었나요?
모든 부분에 Map을 사용하면, 추후 Swagger를 추가하더라도 그 타입에 대해서 정확한 확인이 불가능해집니다!

되도록이면 DTO로 Response를 리턴하는 방향으로 작업해주시면 좋을 것 같아요

2024-07-27 11:44 UTC, gongdongho12 commented on src/main/resources/templates/login.html
> +    }
이 값도 서버측에서 가지고있고 템플릿 엔진으로 파라미터로 수정되는 방식으로 접근해보면 어떨까요?

2024-07-27 11:44 UTC, gongdongho12 commented on src/main/resources/templates/login.html
> +    }
사실 서버사이드 렌더링이라 이 부분도 서버에서 전달주고 있긴 하지만요!

2024-07-27 11:44 UTC, gongdongho12 commented on src/test/java/gift/entity/ProductDTOTest.java
> +    }
이 두개의 테스트 차이를 잘 모르겠어요!
그래도 확실히 케이스를 넓혀주니까 확인 범위가 늘어나는점이 좋네요 👍🏼

2024-07-27 11:44 UTC, gongdongho12 commented on src/test/java/gift/entity/WishlistDTOTest.java
> +}
존재하는 상품 테스트 -> 위시리스트 존재하는 상품 테스트
형식으로 최대한 구체화 해주는게 좋지 않을까요?
상품 테스트의 경우엔 Product를 찾으러 갈 수 있는데 지금의 테스트는 위시리스트의 테스트이니까요!

2024-07-27 11:44 UTC, gongdongho12 commented on src/test/java/gift/filter/AdminFilterTest.java
> +    }
이런 부분 생각해보기 쉽지 않은데 딱 필요한 부분에 정확하게 구분해 주셨어요!
다만 setUp은 메서드이니까, beforeEach로 쓰기 보다는 저걸 파라미터로 받아서 각각 given에서 넣어주는 것도 좋지 않았을까 생각이 드네요

별도로 어드민용, 유저용 토큰을 beforeEach로 하기에는 어짜피 각각 개별적으로 사용하는 방식이니까요

2024-07-27 13:55 UTC, Dockerel commented on src/main/java/gift/config/FilterConfig.java
> +        registrationBean.addUrlPatterns("/api/users/me");
AOP를 이런 곳에 활용해 볼 수도 있겠군요!
그러니까 멘토님 말씀은 위에 등록 부분을 aop로 빼서 controller 전에 실행되도록
```java
@Aspect
@Component
public class FilteringAop {

    @Pointcut("execution(* gift.aop.controller..*(..))")
    public void controllerMethods() {}

    @Before("controllerMethods()")
    public void logBeforeControllerMethods() {
        // url 등록
    }
}
```

이...런..? 느낌으로 해보라는 것 일까요?? 사실 구현은 아직 못해서 일단 간단하게

```java
private static final String[] JWT_URL_PATTERNS = {
            "/api/products/*",
            "/api/orders/*",
            "/api/wishlists/*",
            "/api/users/me"
    };

    @Bean
    public FilterRegistrationBean<JwtFilter> jwtFilter() {
        FilterRegistrationBean<JwtFilter> registrationBean = new FilterRegistrationBean<>();
        registrationBean.setFilter(new JwtFilter(tokenPrefix, userUtility));

        for (String url : JWT_URL_PATTERNS) {
            registrationBean.addUrlPatterns(url);
        }

        return registrationBean;
    }
```

위와 같은 방식으로 그나마 관리가 간단하게 리펙터링 해보았습니다!

2024-07-27 13:56 UTC, Dockerel commented on src/main/java/gift/controller/rest/OrderController.java
> +        }
듣고보니 그런것 같아서 service 안으로 넣어서 주문이 만들어진 이후에 실행되도록 만들어 놓았습니다!

2024-07-27 14:01 UTC, Dockerel commented on src/main/java/gift/controller/rest/UserController.java
> +                .body(userUtility.accessTokenToObject(response.get("accessToken")));
말씀하신대로 accessToken을 message로 반환하는 형태는 위 클래스에서만 쓰이더라구요! 아래에서 말씀하신 DTO로 반환하는 방식까지 추가하여 리펙터링 해보았습니다!

2024-07-27 14:06 UTC, Dockerel commented on src/main/java/gift/controller/rest/UserController.java
> +    }
아하 네넵 근데 생각해보니 exception이 발생하는 케이스가 존재하지 않는 것 같아 그냥 빼고 반환형 객체를 적용시켜 리펙터링 해보았습니다
```java
@GetMapping("/me")
    public ResponseEntity<UserResponseDTO> me(HttpSession session) {
        String email = (String) session.getAttribute("email");
        String role = (String) session.getAttribute("role");

        UserResponseDTO res = new UserResponseDTO(email, role);
        return ResponseEntity.ok().body(res);
    }
```

2024-07-27 14:07 UTC, Dockerel commented on src/main/java/gift/service/UserService.java
> +        return response;
아하 넵 그런데 저 부분은 service에서 controller로 데이터를 넘겨주는 용도라서 dto response와 관련이 없긴 합니다! 다른 controller의 부분들은 전부 dto 객체의 리턴으로 리펙터링 해놓았습니다~!

2024-07-27 14:09 UTC, Dockerel commented on src/main/resources/templates/login.html
> +    }
오 네넵 찾아보니 script 태그에
```html
<script th:inline="javascript"></script>
```
위와 같이 추가하면
```js
const kakaoParams = {
        client_id: [[${clientId}]],
        redirect_uri: [[${redirectUrl}]],
        response_type: [[${responseType}]],
    }
```
이렇게 가져다 쓸 수 있다고 하더라구요!

말씀하신 방식이 이 방식이 맞을까요??

2024-07-27 14:10 UTC, Dockerel commented on src/test/java/gift/entity/ProductDTOTest.java
> +    }
앗 지금 보니 두 테스트 모두 별반 다를게 없긴 하네요 ㅋㅋㅋㅋ

2024-07-27 14:11 UTC, Dockerel commented on src/test/java/gift/entity/WishlistDTOTest.java
> +}
지금 보니 테스트 이름이 많이 모호하긴 한것 같네요! 
```
위시리스트에_추가하고_싶은데_실제로_존재하는_상품인_경우
위시리스트에_추가하고_싶은데_실제로_존재하지_않는_상품인_경우
```
위와 같이 구체화 하였습니다

2024-07-27 14:12 UTC, Dockerel commented on src/test/java/gift/filter/AdminFilterTest.java
> +    }
감사합니다 ㅎㅎㅎ 말씀하신대로 따로 넣어주는게 더 깔끔하겠더라구요! 각각 given에 넣어주었습니다~!

2024-07-27 14:16 UTC, Dockerel commented on src/test/java/gift/filter/AdminFilterTest.java
> +    }
다음주에 배포 수업이라 프론트와 같이 협업을 하는데 제 코드를 보여주기가 너무 부끄러워 자체적으로 리펙터링을 해보느라 커밋한 코드가 본의아니게 굉장히 많아졌네요 ㅎ.... 항상 코드 봐주셔서 너무 감사하고 이번주도 고생하셨습니다!

2024-07-28 05:12 UTC, gongdongho12 commented on src/main/java/gift/controller/rest/UserController.java
> +    }
exception이 나는 경우에 메시지는 controllerAdviser를 활용하는 방식을 추천드립니다!

2024-07-28 05:13 UTC, gongdongho12 commented on src/main/resources/templates/login.html
> +    }
넵넵 맞습니다

2024-07-28 05:14 UTC, gongdongho12 approved these changes
2단계 과제까지 고생하셨습니다

2024-07-28 05:16 UTC, merged