충남대 BE_이은경 5주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #211
Opened 2024-07-25 07:28 UTC by pkyung

## 과제 진행 사항
### 주문하기
- [x] 주문 테이블 설계 후 구현
- [x] 주문 dto 생성
- [x] 주문 시에 옵션 차감하는 메서드
- [x] 위시 리스트에 있는 경우 위시 리스트 삭제
- [x] 카카오톡 메시지 전송

2024-07-25 12:36 UTC, ksy90101 requested changes
간단한 피드백을 남겼으니 확인해주세요.
아울러 트랜잭션 보장부분 꼭 확인해주시구요!

2024-07-25 12:36 UTC, ksy90101 commented on src/main/java/gift/component/KakaoApiComponent.java
> +        templateObj.put("link", linkObj);
이걸 DTO로 한번 해보면 어떨까요?

2024-07-25 12:36 UTC, ksy90101 commented on src/main/java/gift/controller/OrderController.java
> +
이렇게 되면 트랜잭션 보장이 될까요?

2024-07-26 05:12 UTC, pkyung commented on src/main/java/gift/controller/OrderController.java
> +
orderProcessingService를 만들어서 트랜잭션이 보장되도록 수정했습니다.

2024-07-26 05:26 UTC, pkyung commented on src/main/java/gift/component/KakaoApiComponent.java
> +        templateObj.put("link", linkObj);
네 dto로 수정했습니다.

2024-07-26 05:36 UTC, ksy90101 commented on src/main/java/gift/dto/KakaoMessageRequest.java
> +public record KakaoMessageRequest(
스네이크케이스를 고려 하셨나요?

2024-07-26 05:36 UTC, ksy90101 commented on src/main/java/gift/dto/KakaoMessageRequest.java
> +public record KakaoMessageRequest(
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class) 키워드 참고해보세요.

2024-07-26 05:53 UTC, pkyung commented on src/main/java/gift/dto/KakaoMessageRequest.java
> +public record KakaoMessageRequest(
값을 getter로만 반환하게 사용하여 고려하지 않았습니다.

2024-07-26 06:05 UTC, pkyung commented on src/main/java/gift/dto/KakaoMessageRequest.java
> +public record KakaoMessageRequest(
네 참고해보겠습니다.

2024-07-28 06:10 UTC, ksy90101 approved these changes
고생하셨습니다~ :+1

2024-07-28 06:10 UTC, merged