전남대_BE 박진화 5주차 과제(Step1)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #215
Opened 2024-07-25 08:59 UTC by Jinhwa-Park

**질문 사항**
```KakaoService```에서 ```Unchecked cast: 'java.lang.Object' to 'java.util.Map<java.lang.String,java.lang.Object>'```라는 경고가 발생했습니다.
이 경고를 해결하고 싶어서 https://memo-the-day.tistory.com/4 이 포스팅에 있는 방법을 참고하여 코드를 변경했습니다. 하지만 여전히 같은 경고가 발생해서 어떻게 이 문제를 해결하는 게 좋을지 조언을 받고 싶습니다.

또한 ```RequiredArgsConstructor```를 한 번 써보려고 lombok을 이번에 추가해봤습니다. 이후에 발생한 경고들 중에는 Getter, Setter를 사용하라고 하는 경고가 추가되었는데, 꼭 사용해야만 하는건지도 궁금합니다!

UnitTest를 진행하고 전부 통과하는데 혹시 테스트해보는 게 좋을 것 같은 사항이 있는지도 조언을 받고 싶습니다!

2024-07-26 22:06 UTC, pkeugine requested changes
아직 PR 이 준비되지 않았다고 하여 request changes 보냅니다.
준비되면 다시 리뷰 요청해주세요.

2024-07-28 14:11 UTC, pkeugine approved these changes
안녕하세요 진화님,
step 1 진행하느라 고생 많으셨어요.
이후 단계를 위해 이 step 은 머지하도록 하겠습니다!

2024-07-28 14:11 UTC, pkeugine commented on .gitignore
> +application-API-KEY.properties
파일 끝에 공백줄 추가 꼭 해주세요.
다른 파일들도 확인해주시구요.

2024-07-28 14:11 UTC, pkeugine commented on src/main/java/gift/Application.java
> +@ConfigurationPropertiesScan
해당 어노테이션은 어떤 이유로 추가하게 되었나요?

2024-07-28 14:11 UTC, pkeugine commented on src/main/java/gift/controller/KakaoController.java
> +                "https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=%s&redirect_uri=%s&scope=%s",
url 은 설정 파일에 분리해보면 어떨까요? 이렇게 했을 때의 장점을 생각해보아요.
그리고 이렇게 요청을 보낼 url 을 만드는 로직은 service 쪽에서 진행해봐도 괜찮을 것 같아요.

2024-07-28 14:11 UTC, pkeugine commented on src/main/java/gift/service/KakaoService.java
> +        MultiValueMap<String, String> body = new LinkedMultiValueMap<>();
`MultiValueMap` 은 어떠한 이유로 사용되었나요?
예시 코드에 있는 부분이긴 하지만, 이왕 사용한거 그 이유를 알고 사용하면 좋을 것 같아서 남기는 질문입니다.

2024-07-28 14:11 UTC, pkeugine commented on src/main/java/gift/service/KakaoService.java
> +    public String getAccessToken(String authorizationCode) {
메서드가 굉장히 긴데 메서드를 분리해보면 좋을 것 같아요.

2024-07-28 14:11 UTC, merged

2024-07-28 16:58 UTC, Jinhwa-Park commented on .gitignore
> +application-API-KEY.properties
그때 공백 줄 옵션을 분명히 켰는데 왜 안되는걸까요.... 제가 하나하나씩이라도 붙이겠습니다..

2024-07-28 16:59 UTC, Jinhwa-Park commented on src/main/java/gift/Application.java
> +@ConfigurationPropertiesScan
Application 실행 시에 creating bean 관련해서 에러가 자주 발생하더라구요. 그 당시에 해결하기 위해서 빈을 찾아주고 자동으로 주입해준다고 하는 해당 어노테이션을 추가하게 되었습니다.

2024-07-28 17:03 UTC, Jinhwa-Park commented on src/main/java/gift/controller/KakaoController.java
> +                "https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=%s&redirect_uri=%s&scope=%s",
지금 생각해보기에는 url을 설정 파일에 두면 코드별로 url을 관리하기 쉬워지고 보안적으로 좋을 것 같다는 생각이 듭니다. url은 설정 파일에 옮기고 로직도 service로 옮기겠습니다.

2024-07-28 17:05 UTC, Jinhwa-Park commented on src/main/java/gift/service/KakaoService.java
> +        MultiValueMap<String, String> body = new LinkedMultiValueMap<>();
하나의 키에 여러 개의 값을 가질 수 있어서 파라미터를 나누어 쓰지 않고도 한 번에 보낼 수 있고, 파라미터 별로 자료형을 계속 변경하지 않아도 돼서 사용한 것 같습니다.

2024-07-28 17:05 UTC, Jinhwa-Park commented on src/main/java/gift/service/KakaoService.java
> +    public String getAccessToken(String authorizationCode) {
넵 알겠습니다!