충남대 BE_배민수 5주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #227
Opened 2024-07-25 15:35 UTC by minsu-cnu

중간에 실수로 client id를 커밋에 포함시켜버려서, gitignore에 추가해두고 키는 새로 발급받았습니다.

해당 키들은 슬랙 DM으로 전달드리겠습니다!

<hr/>

토큰 관련 로직을 다음과 같이 설계하고 구현하였습니다.
설계 중 구현하지 않은 부분도 있지만, 리프레시 토큰 활용 등의 부분들도 포함하여 전체적인 그림을 잡고 싶어서 아래와 같이 설계를 하고 구현을 시작했습니다.
코드를 보실 때 참고가 되실까봐 아래에 필기 내용을 남깁니다!

<br/>

자체 엑세스 토큰 : 회원 id, 만료일시, 소셜 로그인 상태 여부, 소셜 엑세스 토큰 (빈문자열 가능)
자체 리프레시 토큰 : 회원 id, 만료일시, 소셜 로그인 상태 여부, 소셜 리프레시 토큰 (빈문자열 가능)
DB 리프레시 토큰 엔티티 : 회원 id, 토큰 값, 만료일시, 소셜 로그인 상태 여부

<인터셉터>
기존 : 엑세스 토큰만 처리 (로그인이 필요한 API 호출 시 작동)
추가 : 리프레시 토큰 처리 인터셉터 (엑세스 토큰 재발급 자체 API의 엔드포인트로 진입 시에만 작동)

<일반 로그인>
회원가입 후 로그인 : 자체 엑세스 토큰, 자체 리프레시 토큰 발급 (자체 리프레시 토큰 DB 저장)
로그인이 필요한 서비스 : 인터셉터에서 토큰 검증 후 사용(일반도 되고 소셜 로그인 상태여도 괜찮. 그저 회원 ID만 필요)
로그인 여부가 필요없는 서비스 : 인터셉터 토큰 검증하지 않음
자체 엑세스 토큰 만료 시 : 만료 응답. 클라이언트는 따로 서버에서 구현해 둔 자체 액세스 토큰 재발급 API에 자체 리프레시 토큰을 넘겨 호출할 수 있음
재발급 호출 했는데 자체 리프레시 토큰 만료 시 : 재로그인 요구 응답

<소셜 로그인>
회원가입 및 로그인 : 카카오 엑세스 토큰과 카카오 리프레시 토큰을 자체 엑세스 토큰과 자체 리프레시 토큰에 담은 후 이걸 응답
카카오 로그인이 필요한 서비스 : 인터셉터에서 토큰 검증 후 사용. 토큰에 들어있는 소셜 여부 값을 보고 만약 카카오 유저가 아닌 상태라면 카카오 로그인을 요구하는 응답 (누군가 고의로 소셜 여부를 true로 조작했다면, 이걸 판별하기 위한 값을 DB에 따로 저장하고 있어야 하는지 애매함)
카카오 로그인이 필요없는 서비스 : 인터셉터 토큰 검증하지 않음
자체 엑세스 토큰 만료 시 : 만료 응답. 클라이언트는 따로 서버에서 구현해 둔 자체 엑세스 토큰 재발급 API에 자체 리프레시 토큰을 넘겨 재발급 가능
재발급 시 : 자체 리프레시 토큰이 유효하다면(소셜보다 유효기간이 짧다고 가정), 소셜 리프레시도 유효한거니까 카카오 인증 서버에 재발급 호출해서 카카오 엑세스를 새로 받고, 이걸 자체 액세스로 감싸서 클라이언트에게 제공
재발급 호출 했는데 자체 리프레시 토큰이 만료 : 재로그인 요구 응답

<미구현>
엑세스 토큰 만료 관련 로직
리프레시 토큰 로직

2024-07-26 15:00 UTC, jjongwa requested changes
2단계 잘 구현해 주셨어요! 질문에 대한 답변 후 다시 리뷰 요청 주시면 머지하도록 하겠습니다~!

PR 설명에 민수님의 설계 과정을 찬찬히 설명해 주셔서 이해하는데 도움이 많이 됐습니다! 👍 👍 

그래도 조금 헷갈리는 부분이 있어서 이렇게 다시 정리를 해보면 어떨까요..!

소셜 로그인에서 사용한 access, refresh가 있고,
서비스 자체에서 내려주는 access, refresh가 있는데.

각각 
1. refresh O / access 만료
2. refresh O / access 유실
3. refresh 만료 / access 만료
4. refresh 만료 / access O
5. refresh 만료 / access 유실
6. refresh 유실 / access 만료
7. refresh 유실 / access O

각각의 경우가 어떤 상황에 해당하고, 현재 시스템 상에서 어떤 식으로 처리될 것으로 예상 되는지 한번 다시 정리해 봅시다!

2024-07-26 15:00 UTC, jjongwa commented on src/main/java/gift/product/controller/auth/AdminAuthController.java
> +        redirectAttributes.addAttribute("refreshToken", jwtResponse.refreshToken());
해당 문자열도 상수화하면 좋아 보이네요.!

2024-07-26 15:00 UTC, jjongwa commented on src/main/java/gift/product/controller/auth/AdminAuthController.java
> +    private final String REDIRECT_ADMIN_LOGIN_PROCESSING = "redirect:/admin/login/process";
물론 지금은 상관 없겠지만 보통 static을 붙이는 편입니다~!
(그리고 static final인 값에만 대문자로 표시하는 컨벤션도 있습니다.!)

2024-07-26 15:00 UTC, jjongwa commented on src/main/java/gift/product/controller/auth/AdminAuthController.java
> +    }
메서드 분리 좋습니다! 👍

2024-07-26 15:00 UTC, jjongwa commented on src/main/java/gift/product/controller/auth/AdminAuthController.java
> +        cookie.setPath("/");
setPath를 설정하면 어떤 효과가 발생하나요?
현재 "/" 으로 되어 있음을 무엇을 의미하나요?

2024-07-26 15:00 UTC, jjongwa commented on src/main/java/gift/product/controller/order/OrderController.java
> +    }
여기서 attribute에 id가 없거나 존재하지 않는 값이 올 수 있을까요?

LoginMember라는 네이밍은 dto보다는 domain에 까깝게 인식될 거 같기도 하네요..!

2024-07-26 15:00 UTC, jjongwa commented on src/main/java/gift/product/model/Order.java
> +@Table(name = "\"order\"")
order라는 단어가 db의 예약어로 등록되어 있는 경우 orders 같은 형식으로 테이블 네이밍을 바꿀 수 있습니다! 이러한 상황에 사용하는 설정이  name이구요~!

2024-07-26 15:00 UTC, jjongwa commented on src/main/java/gift/product/model/Order.java
> +    private final LocalDateTime orderDateTime;
해당 어노테이션은 어떤 역할을 하나요?
orderDateTime은 어떤 시점에 값이 결정될까요?

2024-07-26 15:00 UTC, jjongwa commented on src/main/resources/application-test.properties
test 설정 따로 준거 굿입니다~! 💯

2024-07-26 15:00 UTC, jjongwa commented on src/test/java/gift/service/OrderServiceTest.java
> +    }
```suggestion
   @Test
    void 주문_조회() {
        //given
        LoginMember loginMember = new LoginMember(1L);
        Order order = new Order(1L, loginMember.id(), 1, "test_message");
        given(orderRepository.findByIdAndMemberId(1L, loginMember.id())).willReturn(Optional.of(order));

        //when
        orderService.getOrder(order.getId(), loginMember);

        //then
        then(orderRepository).should().findByIdAndMemberId(order.getId(), loginMember.id());
    }
```

그냥 숫자만 맞게 맞춰 넣는 것 보다 요런 식으로 앞에서 만들어놓을 객체의 값을 사용하는게 조금 더 탄탄한 테스트를 만들 수 있습니다.!

지금은 하나의 케이스만 검증하지만 경우에 따라 `@ParameterisedTest`와 `@CSVSource` 등을 사용해 여러 건의 케이스를 동적으로 주입받아 사용하는 경우 이런 식으로 구성할 수 없거든요.!

2024-07-26 15:00 UTC, jjongwa commented on src/test/java/gift/service/OrderServiceTest.java
그리고 mock을 활용하는 테스트인 만큼 예외 상황에 대한 TC도 추가해 주면 좋을 것 같네요~!

2024-07-26 15:00 UTC, jjongwa commented on src/test/java/gift/service/WishServiceTest.java
> +    }
바로 위 메서드도 마찬가진데, 실패에 관한 테스트라는 걸 네이밍에 나타내주면 조금 더 가독성이 높아질 것 같습니다.!

위시_리스트에_상품_중복_추가_시도를_하면_예외_처리한다.
or
실패_위시_리스트에_상품_중복_추가

2024-07-26 15:00 UTC, jjongwa commented on src/main/java/gift/product/model/KakaoToken.java
> +    }
해당 클래스는 카카오에서 발급해주는 토큰을을 저장해 놓은 용도인가요?
아니면 서비스 자체에서 내려주는 토큰인건가요?

refresh와 access를 모두 저장하는 이유는 무엇인가요?

2024-07-26 15:00 UTC, jjongwa commented on src/main/java/gift/product/controller/auth/AdminAuthController.java
프로젝트 패키지 구조에 변경사항이 있군요!
기본적으로 레이어드 아키텍처를 따라가면서 controller는 model별로 하위 패키지를 나눠 주었는데요, 이렇게 변경한 이유가 있을까요?
서비스는 그대로 모여있고 컨트롤러쪽만 세분화한 이유가 궁금합니다!

2024-07-27 08:47 UTC, minsu-cnu commented on src/main/java/gift/product/controller/auth/AdminAuthController.java
> +        redirectAttributes.addAttribute("refreshToken", jwtResponse.refreshToken());
앗 이제 보니 중복되는 문자열이 많았었네요. 조언 감사합니다 해당 부분 반영하겠습니다!

2024-07-27 08:47 UTC, minsu-cnu commented on src/main/java/gift/product/controller/auth/AdminAuthController.java
> +    private final String REDIRECT_ADMIN_LOGIN_PROCESSING = "redirect:/admin/login/process";
해당 부분 반영하여 코드 수정하겠습니다!

2024-07-27 08:48 UTC, minsu-cnu commented on src/main/java/gift/product/controller/auth/AdminAuthController.java
> +    }
감사합니다!ㅎㅎ

2024-07-27 08:48 UTC, minsu-cnu commented on src/main/java/gift/product/controller/auth/AdminAuthController.java
> +        cookie.setPath("/");
setPath의 기능을 자세히 알아보지 않고 아무 생각없이 썼던 것 같습니다..!
이번 기회에 어떤 효과를 내는지 공부해보았습니다.

쿠키를 통해 클라이언트가 엑세스 토큰 정보를 갖고 있을 수 있게 하는데, setPath를 통해 해당 쿠키가 유효하게 될 URL 범위를 지정할 수 있습니다.

현재는 "/"로 되어있는데, 이는 즉 서버의 모든 URL에 요청을 날릴 때 해당 쿠키에 접근할 수 있음을 의미합니다.

그런데 생각해보니 해당 쿠키 로직은 관리자 페이지에서만 사용하고 있어서, URL 범위를 관리자 페이지로 제한해두는게 좋을 것 같아 이를 반영하였습니다.

2024-07-27 08:48 UTC, minsu-cnu commented on src/main/java/gift/product/controller/order/OrderController.java
> +    }
해당 request에 id attribute가 없거나 존재하지 않는 값이 오는 경우는 없다고 생각합니다.
왜냐하면 OrderController의 모든 요청 핸들러 메서드들은 실행 이전에 인터셉터를 실행하는데, 이 인터셉터에서는 헤더에 있는 토큰에 대하여 먼저 검증을 수행합니다.

만약 토큰에 회원 ID 클레임이 없거나, ID값은 들어있지만 ID에 해당하는 유저가 DB에 없는 경우 인터셉터에서 예외를 발생시켜주기 때문에, OrderController단까지 도달한 시점에는 말씀하신 예외 상황이 발생할 수 없다고 생각합니다.

한편, 멘토님 리뷰를 보고 저도 도메인에 더 가깝게 느껴질 수 있는 네이밍이라고 생각이 들어서, 더 명확하게 ID를 담은 DTO라는 것을 한 눈에 알 수 있게 네이밍을 변경해보았습니다.

2024-07-27 08:48 UTC, minsu-cnu commented on src/main/java/gift/product/model/Order.java
> +@Table(name = "\"order\"")
리뷰 반영하여 orders로 네이밍을 바꾸도록 설정을 변경하였습니다. 감사합니다!

2024-07-27 08:48 UTC, minsu-cnu commented on src/main/java/gift/product/model/Order.java
> +    private final LocalDateTime orderDateTime;
해당 어노테이션은 엔티티를 DB에 저장할 때, 해당 필드에 현재 일시를 자동으로 넣어주는 역할을 합니다.

여기서 orderDateTime은 Order 엔티티 객체가 레포지토리의 save를 통해 영속성 컨텍스트 쓰기 지연 저장소에 올라가고, 커밋 시 DB에 INSERT 쿼리로 해당 엔티티를 저장하는 시점에 값이 결정됩니다.

2024-07-27 08:48 UTC, minsu-cnu commented on src/main/resources/application-test.properties
감사합니다!

2024-07-27 08:50 UTC, minsu-cnu commented on src/test/java/gift/service/OrderServiceTest.java
> +    }
조언 주신 부분에 대해 기존에는 필요성 체감을 못했어서 간과했었는데, 알려주신 @ParameterisedTest와 @CSVSource에 대해 검색해보고 공부해보니 확실히 필요성이 체감이 됐습니다. 감사합니다! 해당 부분 반영하였습니다.

2024-07-27 08:51 UTC, minsu-cnu commented on src/test/java/gift/service/OrderServiceTest.java
리뷰 반영하여 주문 도메인 서비스 계층에 대한 예외 테스트를 모두 추가하였습니다!

2024-07-27 08:51 UTC, minsu-cnu commented on src/test/java/gift/service/WishServiceTest.java
> +    }
말씀주신대로 앞에 실패 접미사를 붙여두니 훨씬 가독성이 좋아졌습니다. 감사합니다!

2024-07-27 08:57 UTC, minsu-cnu commented on src/main/java/gift/product/model/KakaoToken.java
> +    }
해당 클래스는 카카오에서 발급해주는 토큰들을 저장하기 위한 용도입니다.
카카오에서 발급해주는 엑세스 토큰과 리프레시 토큰을 DB에 저장하는 이유는 다음과 같습니다.

우선 첫 번째 설계대로 구현했을 때는 자체 토큰에 카카오 토큰을 클레임 형태로 집어넣어서 클라이언트에 제공했었습니다.
그런데 이렇게하니 민감한 카카오 토큰을 자체 토큰에 담아버리게 되었고, 클라이언트 단에서 다른 사용자가 악의적인 목적을 가지고 이를 해독하여 카카오 토큰을 얻어낼 수 있습니다.

기본적으로 자체 토큰을 통해 서버에서 먼저 사용자 검증을 수행하고, 이 후에 카카오 토큰으로 카카오 API를 호출하는 것이 보안상 안전하다고 생각하는데 위 방식으로 카카오 토큰이 쉽게 탈취당하면 이 것에 문제가 생깁니다.

이러한 보안적인 측면 외에도, 자체 토큰에 담는 정보가 너무 많아져 토큰의 크기가 커지는 문제도 있습니다.

이 문제들을 해결하기 위해 카카오 토큰을 DB에 저장해서 관리하는 방식을 채택하였습니다.

클라이언트에는 자체 토큰을 발급하는데, 여기에는 이제는 회원 ID 정보만 담겨있습니다.
클라이언트가 만약 카카오 API와 관련된 어떤 서비스를 호출한다면, 우선 서버에서는 자체 토큰을 받아 이를 파싱하여 회원 ID를 얻습니다.
그리고 이 ID로 카카오 토큰 테이블을 조회하여 카카오 엑세스 토큰을 얻어내어 이 것으로 카카오 API를 호출합니다.

만약 카카오 API를 호출했는데 카카오 엑세스 토큰이 만료되어 갱신이 필요한 상황이 발생한다면, DB에 있던 카카오 리프레시 토큰으로 카카오에 토큰 갱신 API를 호출해서 토큰을 갱신합니다.

이러한 이유로 카카오 엑세스 토큰과 카카오 리프레시 토큰을 DB에 저장하게 되었습니다.

다만 이 경우 DB에 회원들의 카카오 토큰들을 다 담아야 하는 비용이 발생하는데, 이 비용을 감안할만큼 보안상의 이점이 있는 설계인지는 아직 두루뭉실하고 체감이 잘 되지는 않습니다.

이 때문에 카카오 엑세스 토큰은 자체 토큰에 담아서 보내도록 하고, DB에는 카카오 리프레시 토큰만 관리하는 방식이 약간의 절충안이 될 수도 있지 않을까?하는 고민이 있습니다.

2024-07-27 08:57 UTC, minsu-cnu commented on src/main/java/gift/product/controller/auth/AdminAuthController.java
도메인이 점점 많아지면서 그에 따라 컨트롤러가 많아져서 파일 탐색이 점점 번거로워졌습니다.
그래서 좀 더 빠르고 간편한 탐색을 위해, 전체적인 레이어드 아키텍처 구조를 유지하면서, 그 하위에서 도메인 별로 폴더링을 추가로 하였습니다.

컨트롤러만 폴더링을 추가로 한 이유는, 서비스와 레포지토리 등의 경우 도메인 별로 단 하나의 파일만 존재해서 폴더링을 딱히 하지 않아도 탐색이 쉬웠기 때문입니다.

추후에 한 도메인에 대해 여러 서비스 또는 레포지토리 파일을 구현하게 된다면, 그 때는 서비스와 레포지토리 등의 계층도 도메인 별로 세분화 작업을 수행할 계획입니다.

2024-07-27 09:01 UTC, minsu-cnu commented
말씀 주신 대로 토큰 관련 로직을 전체적으로 다시 한번 구상해보았습니다. 만료 검증 및 재발급 로직이 아직 구현되지는 않은 상태이지만, 이와 관련된 케이스들도 모두 포함하여 전체적으로 설계를 해보았습니다!

<자체 토큰 케이스>
refresh O / access 만료 : 로그인 후 브라우저를 활동 없이 오래 켜두었다가 어떤 서비스를 호출한 경우
-> 인터셉터에서 예외 처리해서, 자체 엑세스 토큰 만료되었다는 메시지를 응답 (클라이언트단에서 이 응답을 예외 처리 후, 자체 리프레시 토큰으로 자체 엑세스 토큰 재발급 API를 호출 및 기존에 요청하려던 서비스를 다시 호출)

refresh O / access 유실 : 클라이언트 브라우저에서 새로고침 한 경우 (리액트 상태관리로 엑세스 토큰을 관리하는 경우, 새로고침 시 엑세스 토큰 증발해서 다시 발급받아야 함)
-> 자체 리프레시 토큰으로 자체 엑세스 토큰 재발급 API 호출

refresh 만료 / access 만료 : 로그인한지 너무 오래됐을 때
-> 로그인 필요한 서비스 호출 시 자체 엑세스 토큰을 헤더에 담아서 서버로 보냄
-> 서버 인터셉터에서 만료를 확인하고 재로그인 응답
-> 클라이언트에서 자체 리프레시 토큰으로 자체 엑세스 토큰 재발급 API 호출
-> 자체 리프레시 토큰 만료를 확인하고, 재로그인 요구 메시지 응답 및 메인 화면 또는 로그인 화면으로 클라이언트를 리다이렉트시킴

refresh 만료 / access O : 자체 엑세스 토큰 갱신한지 얼마 안돼서 직후에 자체 리프레시 토큰이 만료된 경우
-> 로그인 필요 서비스 호출은 정상 작동
-> 만약 자체 엑세스 토큰이 만료되었거나, 새로고침을 해서 자체 엑세스 토큰을 재발급하려는 상황이 오는 경우, 이 때는 자체 리프레시 토큰이 만료되었으므로 재로그인 요구 메시지를 응답하고 메인 화면 또는 로그인 화면으로 클라이언트를 리다이렉트시킴

refresh 만료 / access 유실 : 새로고침해서 클라이언트에 자체 엑세스 토큰이 없는데 자체 리프레시 토큰도 만료인 상태
-> 로그인이 필요한 서비스 호출 시, 자체 엑세스 토큰이 없으니 자체 엑세스 토큰 유실 메시지 응답
-> 클라이언트는 해당 응답을 받고 자체 리프레시 토큰으로 자체 엑세스 토큰 재발급 API를 호출
-> 서버는 자체 리프레시 토큰이 만료되었으니 재로그인 요구 메시지를 응답 및 메인 화면 또는 로그인 화면으로 리다이렉트

refresh 유실 / access 만료 : 클라이언트 단에서 쿠키 또는 로컬 스토리지에 문제가 생겨서 자체 리프레시 토큰이 유실됐는데, 자체 엑세스 토큰도 만료가 된 상황
-> 로그인이 필요한 서비스 호출 시, 서버는 자체 엑세스 토큰 만료 응답
-> 클라이언트는 해당 응답을 보고 자체 엑세스 토큰 재발급 API를 호출
-> 서버에는 자체 리프레시 토큰이 null로 들어왔으므로 재로그인 요구 메시지 응답

refresh 유실 / access O : 클라이언트 단에서 문제가 생겨 자체 리프레시 토큰이 유실됐지만 자체 엑세스 토큰은 아직 살아있는 상황
-> 로그인 필요 서비스 호출은 정상적으로 작동
-> 추후 자체 엑세스 토큰 만료 또는 유실 시, 자체 엑세스 토큰 재발급 API 호출할 때 서버 단에서는 자체 리프레시 토큰이 null이 들어왔으므로 재로그인 요구 메시지 응답

refresh X / access X : 비로그인 유저
-> 로그인 필요없는 서비스는 정상 작동
-> 로그인 필요 서비스 호출 시, 자체 엑세스 토큰 만료 응답
-> 클라이언트는 해당 응답을 보고 자체 엑세스 토큰 재발급 API를 호출
-> 서버는 자체 리프레시 토큰이 null이니 재로그인 요구 메시지를 응답
-> 클라이언트는 해당 응답을 보고 사용자에게 재로그인 시도시킴



<클라이언트가 호출한 서비스가 카카오 API를 내부적으로 활용하는 서비스인 경우>
자체 엑세스 토큰이 유효해서 해당 서비스 호출은 정상적으로 이루어진 상태임을 가정.
-> 자체 엑세스 토큰을 파싱해서 얻은 회원 ID로 카카오 토큰 테이블을 조회해서 카카오 엑세스 토큰을 얻어옴

카카오 refresh X / 카카오 access X : 일반 로그인 유저이고 카카오 소셜 로그인은 하지 않은 상태인 경우
-> 카카오 토큰 테이블에서 토큰을 조회할 때 예외 발생
-> 클라이언트에게 카카오 로그인 요구 메시지 응답
-> 클라이언트는 해당 응답을 받고 로그인 화면 등으로 자체적으로 리다이렉트

카카오 refresh O / 카카오 access 만료 : 카카오 로그인 이후 시간이 지나 카카오 엑세스 토큰이 만료된 경우
-> 카카오 API 호출 시 카카오 엑세스 토큰 만료 응답 받음
-> 서버는 카카오 리프레시 토큰을 통해 카카오 엑세스 토큰과 리프레시 토큰을 재발급
-> 이 때 리프레시 토큰은 유효 기간이 1개월 이상 남은 경우에는 null이 들어오므로, 처리 로직 만들어주기
-> 다시 원래 하려던 카카오 API 호출

카카오 refresh O / 카카오 access 유실 : DB 오류 등으로 카카오 엑세스 토큰이 유실된 경우
-> not null 제약 조건 위배. 발생한 예외를 캐치해서, 해당 튜플을 회원 ID로 접근해서 제거해주고 클라이언트에게 카카오 로그인 요구 메시지 응답
-> 클라이언트는 해당 응답을 받고 로그인 화면 등으로 자체적으로 리다이렉트

카카오 refresh 만료 / 카카오 access 만료 : 카카오 로그인 이후 시간이 많이 지났을 때
-> 카카오 API 호출 시 카카오 엑세스 토큰 만료 응답 받음
-> 서버는 카카오 리프레시 토큰을 통해 카카오 엑세스 토큰과 리프레시 토큰을 재발급 시도
-> 카카오로부터 리프레시 토큰 만료 응답 받음
-> 서버는 클라이언트에게 카카오 재로그인을 요구하는 메시지를 응답

카카오 refresh 만료 / 카카오 access O : 카카오 리프레시 토큰이 만료되고, 마지막 엑세스 토큰이 살아있는 상황
-> 정상적으로 카카오 API 호출 가능
-> 추후 카카오 엑세스 토큰 만료 시, 토큰 갱신 필요

카카오 refresh 만료 / 카카오 access 유실 : DB 오류 등으로 카카오 엑세스 토큰이 유실된 경우
-> not null 제약 조건 위배. 발생한 예외를 캐치해서, 해당 튜플을 회원 ID로 접근해서 제거해주고 클라이언트에게 카카오 로그인 요구 메시지 응답
-> 클라이언트는 해당 응답을 받고 로그인 화면 등으로 자체적으로 리다이렉트

카카오 refresh 유실 / 카카오 access 만료 : DB 오류 등으로 카카오 리프레시 토큰이 유실된 경우
-> not null 제약 조건 위배. 발생한 예외를 캐치해서, 해당 튜플을 회원 ID로 접근해서 제거해주고 클라이언트에게 카카오 로그인 요구 메시지 응답
-> 클라이언트는 해당 응답을 받고 로그인 화면 등으로 자체적으로 리다이렉트

카카오 refresh 유실 / 카카오 access O : DB 오류 등으로 카카오 리프레시 토큰이 유실된 경우
-> not null 제약 조건 위배. 발생한 예외를 캐치해서, 해당 튜플을 회원 ID로 접근해서 제거해주고 클라이언트에게 카카오 로그인 요구 메시지 응답
-> 클라이언트는 해당 응답을 받고 로그인 화면 등으로 자체적으로 리다이렉트

2024-07-28 00:27 UTC, jjongwa commented on src/main/java/gift/product/controller/auth/AdminAuthController.java
> +        cookie.setPath("/");
👍 
나중에 프론트와 함께 협업 프로젝트를 할 때 CORS를 비롯해 이것저것 만져야 할텐데, 화면이 나오지 않는 경우 쿠키 쪽 설정이 문제인 경우가 많으니 기억하고 계시면 좋습니닷

2024-07-28 00:28 UTC, jjongwa commented on src/main/java/gift/product/model/Order.java
> +    private final LocalDateTime orderDateTime;
좋습니다~!ㅎㅎ
이러한 어노테이션을 사용해 시간을 저장할 때에는 어느 시점의 값이 저장되는지 알고 있는게 중요해요~!

2024-07-28 00:29 UTC, jjongwa commented on src/test/java/gift/service/OrderServiceTest.java
> +    }
필수는 아니지만, 기존에 존재하는 테스트 중 한두개를 다음 단계에서 ParameterisedTest로 바꿔 보는 것도 추천드립니다!

2024-07-28 00:36 UTC, jjongwa commented on src/main/java/gift/product/model/KakaoToken.java
> +    }
서비스에 따라 다르겠지만, 항상 카카오의 로그인 정보가 필요한 기능들이라면 위와 같이 둘 다 저장해 놓는게 좋아 보이긴 하네요.!

> 자체 토큰에 담는 정보가 너무 많아져 토큰의 크기가 커지는 문제도 있습니다.

요 부분도 벌써 체험해 보신거 아주 좋은 것 같아요ㅎㅎ 쿠키의 단점 중 하나인데 플젝을 진행하다보면 가끔가다 애매한 상황이 오거든요..
이렇게 고민한 경험이 있으면 앞으로 비슷한 상황을 만날 때 더 합리적인 판단을 할 수 있는 바탕이 될 것 같습니다~!

2024-07-28 00:38 UTC, jjongwa commented on src/main/java/gift/product/controller/auth/AdminAuthController.java
네네 지금은 필요성이 느껴진 부분에만 세분화를 진행했는데

> 추후에 한 도메인에 대해 여러 서비스 또는 레포지토리 파일을 구현하게 된다면, 그 때는 서비스와 레포지토리 등의 계층도 도메인 별로 세분화 작업을 수행할 계획입니다.

이러한 상황이 오게 된다면, 아예 처음부터 도메인 별로 패키지를 나누는 방식도 있습니다~!
(product 패키지 안에 cotroller, service, repo 패키지가 하위로 있는)

이렇게 도메인 별로 패키지를 나누는 방식은 어떤 장점이 있을지 생각해 보는 것도 추천드려요!

2024-07-28 00:41 UTC, jjongwa approved these changes
💯 💯 💯 
조금 귀찮을 수도 있는 리뷰를 남겼는데 완전 꼼꼼하게 정리해 주셨어요~! 👍 

이렇게 서비스의 보안적 측면으로 고민해본 경험이 나중에 새로운 서비스를 구현할 때 큰 도움이 될거예요!
approve & merge 하겠습니다~!

2024-07-28 00:41 UTC, merged