전남대 BE_김보민 5주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #236
Opened 2024-07-25 23:29 UTC by KBM05haruin30

# 1단계
### 코드 작성하면서 어려줬던 점
1. 처음 인가 코드를 얻었을 때 인가 코드를 직접 복사하여 입력할 수 있는 칸을 만들었습니다.  그 칸에 입력 시 액세스 토큰을 얻을 수 있게 만들었지만 자동으로 할 수 있는 방법이 없을까? 하다가 슬랙에 다른 쿠키즈분들에게 물어보았습니다. 얻은 해결 방법은  코드가 발급되는 리디렉션 링크를 컨트롤러에서 매핑하는 것이었습니다. 물어보기 전까지 어떻게 자동으로 얻을 수 있는지 어려워했습니다.
2. 액세스 토큰을 얻게 되면 JSON 형태로 얻게 됩니다. 이 중 필요한 "access_token" 만을 얻기 위해 코드를 짜는 것이 어려웠습니다. 검색을 해보면 JSON에서 특정 값을 얻기 위해서는 JSONObject를 사용하거나 GSON을 사용하는 것 같습니다. 둘 다 처음 보는 것이라 다른 쿠키즈들은 어떻게 해결했나 PR을 봐보았습니다. 여기서 DTO를 사용하시는 것을 보고 힌트를 얻었습니다. 그래서 'JSON DTO' 라고 검색을 하니 key가 카멜 케이스인 경우가 아니라면 DTO 클래스에 `@JsonProperty`를 붙여주어야 한다고 나와 있었습니다. 그래서 붙여서 사용했습니다.
3. 과제의 내용 중 `향후 카카오 API 사용을 준비한다.` 라는 내용의 해석이 어려웠습니다. 액세스 토큰 추출까지는 성공했지만 이 토큰을 가지고 사용자 정보 중 email을 얻어 놓아야 하는 것인지 잘 모르겠어서 액세스 토큰 추출까지만 해놓았습니다.

### 중점적으로 봐주셨으면 하는 점
과제 요구 사항을 잘 수행했는지 봐주셨으면 합니다. 추가로 인가 코드를 받고 그 코드로 액세스 토큰을 받는 과정이 매끄럽게 진행되는지도 봐주셨으면 합니다.

### 궁금한 점
1. 코드가 발급되는 리디렉션 링크를 컨트롤러에 매핑했습니다. 자동으로 액세스 토큰을 얻을 수 있지만 브라우저의 주소창에는 인가 코드가 보이게 되었습니다. 이걸 해결하고자 redirect로 페이지를 옮기려고 했습니다. 이 때 문제점은 redirect로 받아온 액세스 토큰이 넘어가지 않는 것이었습니다. 이걸 해결하기 위해 `RedirectAttributes` 를 사용했습니다. 팀원과의 이야기를 통해 팀원분은 컨트롤러에 `String accessToken` 을 만들어서 사용하면 `RedirectAttributes`를 사용하지 않아도 된다고 했습니다. 이 두 가지 방법 중 어느 방법이 적절한 방법인지 궁금합니다.
2. 액세스 토큰의 내용 중 원하는 내용만 얻기 위해 DTO를 사용하는 것이 맞는지, 아니면 JSONObject나 GSON을 사용해야 하는지 궁금합니다.
3. 액세스 토큰을 html의 script를 사용하여 localStorage에 저장하도록 했습니다. 이렇게 액세스 토큰을 저장해 두어도 되는지도 궁금합니다.
4. .gitignore에 `application-secret-key.properties`를 추가했는데도 브랜치에 들어가보면 해당 파일이 보이게 됩니다. 해결 하기 위해 검색을 해보니 git에 있는 캐시 파일을 지워주고 다시 add를 해주면 된다고 했습니다. 이렇게 하면 작성한 커밋들이 사라지는 것은 아닌가 싶어 아직 시도해보지 않았는데 해당 코드를 순서대로 입력하면 되는 것인지 궁금합니다.
``` 
git rm -r --cached .
git add .
git commit -m "feat : 캐시 삭제" 
```

2024-07-26 06:19 UTC, KBM05haruin30 commented
팀원분이 버튼을 눌러 카카오 로그인 화면으로 이동하면 개발자 도구를 통해 REST API 키가 노출되는 것을 확인해주었습니다. 그래서 카카오 로그인 화면을 삭제하고 컨트롤러에서 만들었던 login링크를 서비스로 옮겼습니다. 그래서 http://localhost:8080/kakao/auth 를 입력하면 바로 로그인 화면으로 이동하게 됩니다. 여기서 제가 기대한 것은 이동할 때 개발자 도구에 clientId가 안 잡히는 것인데 여전히 잡히게 됩니다. 원래 잡히는 것이 정상인지, 안 잡혀야 한다면 안 잡히게 하는 방법이 무엇인지 궁금합니다!

2024-07-27 10:16 UTC, Hongdonggeon requested changes
안녕하세요 보민님
미션 구현하시느라 수고많으셨습니다
`향후 카카오 API 사용을 준비한다.` 가 토큰 추출까지 한다는 말인 것 같은데 , 저도 요구사항은 확인해보겠습니다!
코멘트들 확인해주세요

2024-07-27 10:16 UTC, Hongdonggeon commented on src/main/resources/application-secret-key.properties
> +kakao.redirect-url=http://localhost:8080
git의 캐시가 문제가 되는거라 보민님이 작성한 명령어로 캐시 제거후에 커밋해보세요

2024-07-27 10:16 UTC, Hongdonggeon commented on src/main/java/gift/controller/KakaoLoginController.java
> +    @GetMapping("/")
api 경로를 /로 하신이유가 뭔가요?

2024-07-27 10:16 UTC, Hongdonggeon commented on src/main/java/gift/service/KakaoService.java
> +        String loginUrl = "https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=" + clientId + "&redirect_uri=" + redirectUrl;
이런 url들도 properties 한 파일에서 관리해주는게 좋을 것 같아요

2024-07-27 10:24 UTC, Hongdonggeon commented
- 첫번째 질문을 이해를 못했습니다ㅠ 자세하게 설명해주실 수 있을까요?


- 결국 dto 객체도 json body를 스프링이 바인딩해주는거예요. 스프링에서 json Body를 dto 객체로 바인딩해주는 원리와 jsonObject나 gson에 대해서도 찾아보면 좋을 . 것같아요

- localStorage에 토큰을 저장해둬서 토큰이 살아있으면 로그인이 유지되어있는 장점이 있겠죠? 근데 토큰이 영구적으로 살아있으면 안되니까 만료기간 설정과 refresh token과 같은 개념이 있는데요. 한번 찾아보면 도움이 될 것 같아요

- 작성된 커밋들이 사라지는게 아니라 캐시가 지워지는거예요! 보민님이 작성한대로 해보면 될거예요

2024-07-27 10:33 UTC, KBM05haruin30 commented on src/main/resources/application-secret-key.properties
> +kakao.redirect-url=http://localhost:8080
넵 감사합니다! 혹시나 문제 생길까봐 사용을 안하고 있었는데 작성해둔 명령어로 캐시 제거 후에 커밋하니 application-secret-key.properties가 보이지 않게 되었습니다!

2024-07-27 10:37 UTC, KBM05haruin30 commented on src/main/java/gift/controller/KakaoLoginController.java
> +    @GetMapping("/")
처음에 인가 코드를 얻을 때 `http://loaclhost:8080/?code=` 형식으로 얻어져서 /를 사용했습니다. 지금 실행을 해보니 불필요하다는 것을 알았습니다. 지우도록 하겠습니다!

2024-07-27 10:45 UTC, KBM05haruin30 commented on src/main/java/gift/service/KakaoService.java
> +        String loginUrl = "https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=" + clientId + "&redirect_uri=" + redirectUrl;
넵 알겠습니다! 이 url들도 application-secret-key.properties에 넣어두겠습니다.

2024-07-27 10:56 UTC, KBM05haruin30 commented
코드가 발급이 될 때 주소가 `http://localhost:8080/?code=`형식으로 나왔습니다. 인가 코드가 공개되면 안되기 때문에 redirect로 `http://localhost:8080/kakao/success`로 바로 이동하게 하였습니다. 
여기서 redirect로 `@GetMapping("/kakao/success")`로 이동하게 되면 `@GetMapping`에서 받아온 accessToken 값은 중간에서 사라져서 `RedirectAttributes`를 사용했습니다. 
이것에 관하여 팀원과 이야기를 했었는데 팀원분은 컨트롤러에 `private String accessToken`을 선언하여 사용하면 `RedirectAttributes`를 사용하지 않아도 accessToken 값을 쓸 수 있다고 했습니다. 
컨트롤러에서 accessToken을 선언해서 사용하는 방법과 `RedirectAttributes`를 이용해서 accessToken을 사용하는 방법 중 어느 방법이 적절한 방법인지 궁금했습니다!

2024-07-28 06:37 UTC, Hongdonggeon commented
- redirectAttributes
제가 redirectAttribute를 처음보긴했는데, redirectAttributes를 사용하는게 잘못되었다고는 생각이 안드는 것 같아요!

2024-07-28 06:38 UTC, Hongdonggeon approved these changes
보민님 미션 구현하느라 수고 많으셨습니다! 
1단계는 머지할게요!! 
2단계도 화이팅입니다 :)

2024-07-28 06:38 UTC, merged