충남대 BE_박서현 5주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #240
Opened 2024-07-26 03:12 UTC by sseooh

2024-07-26 11:19 UTC, jjongwa requested changes
2단계 구현 고생하셨습니다.! 
리뷰에 대한 답변 후 다시 요청주세요~!
그리고 제가 다른 리뷰들은 대부분 서현님의 의견을 물어보는 경우가 많아요! 무조건적으로 변경했습니다! 보단 이렇게 작성한 이유와 생각의 흐름을 적어주시면 좋을 것 같아요~!

2024-07-26 11:19 UTC, jjongwa commented on src/main/java/gift/domain/OrderItem.java
> +    private Option option;
현재 orderItem이 굉장히 많은 다른 엔티티들과 연관관계를 가지고 있네요!
각 엔티티 간의 구조를 그림으로 표현해 주실 수 있을까요?
이렇게 하나의 엔티티가 많은 연관관계를 가지고 있는 경우 어떠한 단점이 있을까요?

연관된 충분한 데이터가 있다고 가정할 때, order, product, option을 각각 삭제하려면 어떠한 사전 조건이 있어야 하나요?

2024-07-26 11:19 UTC, jjongwa commented on src/main/java/gift/service/OrderService.java
> +            order.getOrderItems().add(orderItem);
```
OrderItem orderItem = new OrderItem(
                    order,
                    product,
                    option,
                    itemRequest.getQuantity()
            );
```

이런 식으로 orderItem 객체를 만들어 줄 수도 있을 거 같은데, 기본 생성자를 만들고 setter를 사용한 이유가 있을까요? 
order 부분도 같습니다.!

2024-07-26 11:19 UTC, jjongwa commented on src/main/java/gift/service/OrderService.java
> +
orderService가 다른 서비스를 가지고 있네요!

서비스와 리포지터리의 계층 관계를 두는 이유는 무엇인가요?
이렇게 서비스 끼리의 계층 관계를 두었을 때의 장점과 단점은 무엇일까요?

2024-07-26 11:19 UTC, jjongwa commented on src/main/java/gift/service/OrderService.java
> +            }
productService에서 다음과 같이 정의되어 있는데요.,

```
public Product getProductById(Long id) {
        return productRepository.findById(id).orElse(null);
    }
```
여기서 throw를 하지 않고 null을 반환하는 이유는 무엇인가요?

null이 애플리케이션 로직 상에서 돌아다니면 어떠한 문제가 있을까요?

2024-07-26 11:19 UTC, jjongwa commented on src/test/java/gift/OrderServiceTest.java
> +public class OrderServiceTest {
테스트 클래스와 메서드에는 접근제어자 필요 없습니다!

2024-07-26 11:19 UTC, jjongwa commented on src/test/java/gift/OrderServiceTest.java
전체적으로 mockIng을 사용한 테스트를 많이 구성해 주셨네요!

mock을 사용한 방법과 실제 데이터를 사용하는 클래식한 방법 중 해당 방식을 고른 이유는 무엇인가요?
어느 부분에서 이점을 느꼈을까요?

2024-07-26 11:19 UTC, jjongwa commented on src/main/java/gift/dto/OrderRequest.java
> +    public void setItems(List<OrderItemRequest> items) {
여기서도 굳이 setter를 사용할 필요가 있을까요..!

2024-07-26 11:19 UTC, jjongwa commented on src/main/java/gift/service/KakaoTokenService.java
> +    }
현재 KakaoToken을 반환하고 있지만, 해당 반환값이 사용되는 곳은 없는 것 같아요!

2024-07-26 11:19 UTC, jjongwa commented on src/main/java/gift/service/KakaoTokenService.java
> +        }
Optional 타입으로 받고 orElseGet()을 통해 if문에 해당하는 로직을 개선해 보면 어떨까요?

2024-07-26 11:19 UTC, jjongwa commented on src/main/java/gift/service/KakaoService.java
메서드의 반환값 설정과 분기를 통해 예외처리 하는 부분을 중심으로 조금 다듬어 보는건 어떨까요?

전체적으로 해당 클래스의 로직이 뭔가 우당탕탕 만들어진거 같네요..

2024-07-26 11:19 UTC, jjongwa commented on src/main/java/gift/service/MemberService.java
> +    private final SecureRandom random = new SecureRandom();
그냥 Random이 아닌 SecureRandom을 쓴 이유는 무엇인가요?

2024-07-26 11:19 UTC, jjongwa commented on src/main/java/gift/service/KakaoService.java
해당 부분에 대한 테스트도 추가해 주면 좋을 것 같네요~!

2024-07-27 23:11 UTC, sseooh commented on src/main/java/gift/domain/OrderItem.java
> +    private Option option;
<img width="907" alt="image" src="https://github.com/user-attachments/assets/d92df9d8-c32f-42c9-9012-655d1610ca73">

하나의 엔티티가 많은 연관관계를 가지고 있는 경우에는 전체적으로 연관관계가 복잡해지기 때문에 데이터가 자주 변경되는 경우에는 데이터의 일관성을 유지하는게 어려울 수 있다는 단점이 있습니다..!

orderitem이 order, product, option을 참조하고 있기 때문에, 각각을 삭제하려면 먼저 해당 orderitem을 삭제해야 합니다.

2024-07-27 23:16 UTC, sseooh commented on src/main/java/gift/service/OrderService.java
> +            order.getOrderItems().add(orderItem);
orderItem 엔티티와 관련해서 수정을 여러 번 하다보니 편하게 수정하기 위해 setter로 먼저 작성한 후, 이후에
`OrderItem orderItem = new OrderItem(
                    order,
                    product,
                    option,
                    itemRequest.getQuantity()
            );`
이런 식으로 수정하려고 했으나 잊었습니다..!

2024-07-27 23:46 UTC, sseooh commented on src/main/java/gift/service/OrderService.java
> +
리포지터리는 데이터와의 상호작용, 서비스는 비즈니스 로직을 담당합니다.

서비스끼리의 계층 관계를 두는 경우, 이러한 관계가 많아질수록 의존성을 관리하기가 복잡해지고, 각 서비스를 호출하는 것에 따른 오버헤드도 발생할 수 있다는 단점이 있습니다.

2024-07-28 00:01 UTC, sseooh commented on src/test/java/gift/OrderServiceTest.java
mock을 사용한 테스트는 실제 데이터나 외부 시스템에 의존하지 않는 방식이기 때문에, 테스트 속도도 빠르고 의도한대로 테스트 시나리오를 설정할 수 있기 때문에 좋은 방식이라고 생각했습니다!

실제 데이터를 사용해서 테스트를 하는 방식은 데이터의 정확성과 일관성을 보장할 수 있고, 실제 데이터를 사용하기 때문에 동일한 테스트 케이스를 다양한 데이터로 반복하며 테스트를 할 수 있다는 장점이 있습니다.

2024-07-28 00:29 UTC, sseooh commented on src/main/java/gift/service/MemberService.java
> +    private final SecureRandom random = new SecureRandom();
그냥 Random은 초기 seed에 따라서 생성되는 숫자가 결정되고, 동일한 seed를 사용하면 동일한 난수가 생성된다고 알고 있습니다. 반면에 SecureRandom은 난수를 생성할 때 예측이 불가능한 seed를 사용하기 때문에 보안이 중요한 경우에 자주 사용합니다. 비밀번호 생성에 사용해야 하기 때문에 보안이 중요하다고 생각했고, 따라서 SecureRandom을 사용했습니다..!

2024-07-28 00:39 UTC, sseooh commented on src/main/java/gift/service/OrderService.java
> +            }
null 처리를 위한 조건문이 많이 추가되면 코드가 복잡해지고, 유지보수가 어려워진다는 단점이 있습니다. 또한, 예상하지 못한 부분에서 null 값이 튀어나오면 비즈니스 로직이 올바르게 동작하지 않을 수 있습니다.

null은 사용한 이유는 단순하게 product를 찾을 때 찾기에 성공하면 해당 객체를 전달하고, 찾지 못한다면 찾고자 하는 product가 없는 것이기 때문에 null로 처리했습니다..! 해당 부분은 throw를 하도록 수정했습니다.

2024-07-28 15:48 UTC, jjongwa approved these changes
👍 👍

2024-07-28 15:51 UTC, jjongwa commented on src/main/java/gift/service/MemberService.java
> +    private final SecureRandom random = new SecureRandom();
그렇다면 과연 그 동일한 seed가 중복되거나 탈취될 경우가 있을지, 
SecureRandom의 단점은 없을지 (단점이 없다면 그냥 Random이 있을 필요가 없겠죠?) 등을 생각해 보며 사용하는 걸 추천드려요~!

지금 사용하고 있는 Random 생성 로직들도 다른 환경에서는 사용하지 못할 수도 있습니다..!

2024-07-28 15:52 UTC, jjongwa commented on src/test/java/gift/OrderServiceTest.java
그럼 그 테스트 속도 차이를 느껴 봤는지가 궁금하네요..! 나중에 기회가 되면 직접 비교해 보며 체감하는 걸 추천드립니다.!

2024-07-28 15:53 UTC, merged