전남대 BE 김수랑 5주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #244
Opened 2024-07-26 05:14 UTC by rdme0

5주차 step2 과제 완료하여 PR 올립니다
이번 주차 기능에 대한 테스트 코드와 프론트에서의 ui는 따로 요구사항에 있지 않고, 시간도 너무 오래 걸릴 것 같아서 구현하지 않았습니다..!

2024-07-28 15:55 UTC, Hongdonggeon requested changes
안녕하세요 수랑님
미션 잘 구현해주셨어요! 수고하셨습니다
리뷰 반영하면서, 코멘트에 남겨 놓았지만 트랜잭션에 대해서 잘 고려해보시면 좋을 것 같아요
주문 로직에서 트랜잭션이 묶여야될 로직과 묶이지 않아도될 로직들을 잘 판단하고 고민해보면 좋을 것 같습니다

2024-07-28 15:55 UTC, Hongdonggeon commented on src/main/java/gift/dto/betweenClient/JwtDTO.java
> +package gift.dto.betweenClient;
패키지를 이렇게 분리한 이유가 어떻게 될까요?

2024-07-28 15:55 UTC, Hongdonggeon commented on src/main/java/gift/service/OptionService.java
> +        return orderInfo;
전달해주는 정보들이 optionEntity에 있는 정보들인데 optionEntity 객체를 넘겨주는건 어떨까요?

2024-07-28 15:55 UTC, Hongdonggeon commented on src/main/java/gift/dto/betweenClient/order/OrderRequestDTO.java
> +        return new OrderHistory(option, quantity, LocalDateTime.now(), message);
주문 생성 시간을 dto에서 주입해주고 있는데요? dto 보다 service 객체나, orderHistory의 엔티티에서 해주는게 좋지 않을까요?

2024-07-28 15:55 UTC, Hongdonggeon commented on src/main/java/gift/controller/OrderController.java
> +
현재 주문이 진행되면
- 차감
- 장바구니 상품 삭제
- 메시지 전송 
- 주문 저장 

차감과 주문 저장은 한 트랜잭션에 묶여있지 않을까요?  차감까지 정상 진행후 , 장바구니 상품삭제에서 예외가 발생한다면 주문 데이터는 저장되어 있지 않고 차감만 되어있을 것 같아요
트랜잭션 고려해주세요!

2024-07-29 05:31 UTC, rdme0 commented on src/main/java/gift/controller/OrderController.java
> +
아 역시 @Transactional로 묶는 것이 맞았군요..!
수정하였습니다!
제가 컨트롤러에서 @Transaction로 묶는 것이 어색하다고 느껴져서 4-tier 아키텍쳐로 더 쪼개려다가 잊어버려서 이렇게 된 것 같습니다

2024-07-29 05:38 UTC, rdme0 commented on src/main/java/gift/dto/betweenClient/JwtDTO.java
> +package gift.dto.betweenClient;
이번 요구사항을 구현하면서 DTO 수가 많아짐에 따라 DTO 디렉토리에서 너무나 많은 DTO들이 보여서 어디와 어디 사이의 DTO인지와, 어떤 기능을 위한 DTO인지로 분류하고 싶었습니다!

2024-07-29 05:40 UTC, rdme0 commented
피드백 반영하였습니다
감사합니다!

2024-07-29 16:23 UTC, Hongdonggeon commented on src/main/java/gift/controller/OrderController.java
> +
컨트롤러에서 @transactional로 묶어도 트랜잭션이 의도한대로 동작할까요?

2024-07-29 16:25 UTC, Hongdonggeon commented on src/main/java/gift/dto/betweenClient/JwtDTO.java
> +package gift.dto.betweenClient;
연동하는 외부 api가 늘어날때마다 패키지를 계속해서 분리해내실까요? 만약 order에 대한 로직들이 외부 카카오 api, 클라이언트, 외부 타사 api들 모든 곳곳에서 쓰인다면 어느 패키지에 포함시킬 . 것같아요?

2024-07-29 16:27 UTC, Hongdonggeon approved these changes
안녕하세요 수랑님
피드백 반영하느라 수고많으셨습니다!
패키지와 `@Transactional` 관련해서 코멘트 남겨놓았어요
이부분 확인하고 3단계 pr에서 고민해보고 반영해주시면 좋을 같아요! (제 의견을 반영하라는 건아니고! 수랑님 생각을 반영해주세요~)

2024-07-29 16:27 UTC, merged

2024-07-30 19:22 UTC, rdme0 commented on src/main/java/gift/dto/betweenClient/JwtDTO.java
> +package gift.dto.betweenClient;
외부 API가 늘어난다고 하더라도 어떤 API를 위한 DTO인지는 분류를 하는 것이 현재로썬 제일 깔끔하다고 생각합니다.
그렇지만 만약에 여러가지 간에서 공통적으로 사용되는 DTO들이 생기게 된다면 betweenClient와 betweenKakaoApi 폴더를 지우고, 그냥 기능별로만 디렉토리로 분류를 할 것 같습니다.

2024-07-30 19:29 UTC, rdme0 commented on src/main/java/gift/controller/OrderController.java
> +
제가 시간이 없어서 짤막하게 알아본 것을 말씀드리자면 @Controller에서는 @Transactional 이 작동되지 않습니다.
그 이유로는 첫 번째로 @Transactional은 프록시 객체를 이용한 것인데 컨트롤러에서는 그게 작동되지 않고, 두 번째론 무엇보다도 일단 비즈니스 로직이 컨트롤러에 노출되면 안된다는 이유입니다.
그래서 결국엔 4계층으로 쪼개서 해결하였습니다