경북대 BE_김영인
kakao-tech-campus-2nd-step2/spring-gift-order pull request #247
Opened 2024-07-26 05:33 UTC by Youngini

5주차 과제 2단계 과제 입니다!

2024-07-26 05:41 UTC, Youngini commented
> 5주차 과제 2단계 과제 입니다!

상품을 주문한 기록도 DB에 저장되는 것이 맞다고 생각해서, Order이라는 Entity를 만들어서 사용자, 상품, 옵션, 주문 시간, message를 attribute로 가지도록 구현했습니다.

그리고 점점 파일이 많아지면서 파일 구조가 코드를 수정할 때 불편해지고 있는데, domain별로 폴더를 구성하는 방식이 이런 경우에 더 편리한지, 멘토님은 어떤 파일 구조를 더 선호하시는 지가 궁금합니다!

2024-07-27 13:14 UTC, gongdongho12 requested changes
영인님 안녕하세요!

카카오 로그인 로직 확인했는데, 관련해서 테스트가 작성되면 좋을 것 같습니다

Step1 반영되면 이 PR에 rebase 한번 적용해서 conflict 해소 부탁드립니다

2024-07-27 13:14 UTC, gongdongho12 commented on src/main/java/gift/controller/KakaoAuthController.java
> +    }
카카오 로그인인데 /kakao Path 지정을 따로 하지 않아도 괜찮을까요?

2024-07-27 13:14 UTC, gongdongho12 commented on src/main/java/gift/service/KakaoTokenService.java
> +        }
단계적 예외처리 👍🏼

2024-07-27 13:14 UTC, gongdongho12 commented on src/main/java/gift/service/KakaoTokenService.java
> +    }
이 json구조가 실제로 바뀔 수 있을 것 같은데 Json객체를 직접 만들어서 string으로 변환해주는 구조가 확장성에 도움이 되지 않을까요?

2024-07-27 13:14 UTC, gongdongho12 commented on src/main/java/gift/service/KakaoTokenService.java
> +        );
sendKakaoMessage인데 여기서 문자열을 만들어 주기 보다는, sendKakaoMessage는 전달 역할만 하고
문자열은 파라미터로 받아서 전달하는 방식이 좋지 않을까요?

2024-07-27 13:14 UTC, gongdongho12 commented on src/main/java/gift/service/KakaoTokenService.java
> +        String token = "Bearer {token}"; // 실제 토큰으로 교체 어떤식으로 할 지 생각하기 (어디에 저장할까?)
토큰도 파라미터로? 아니면 현재 세션객체에서 토큰을 뽑는 방법 등으로 해결해보면 좋을 것 같습니다

2024-07-28 11:41 UTC, Youngini commented on src/main/java/gift/controller/KakaoAuthController.java
> +    }
api/kakao 로 지정했습니다!

2024-07-28 12:23 UTC, Youngini commented on src/main/java/gift/service/KakaoTokenService.java
> +        String token = "Bearer {token}"; // 실제 토큰으로 교체 어떤식으로 할 지 생각하기 (어디에 저장할까?)
HttpSession을 사용해서 토큰을 처리해보려고 했습니다!

2024-07-28 14:43 UTC, gongdongho12 approved these changes
고생하셨습니다

2024-07-28 14:43 UTC, merged