경북대 BE_김민주 5주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #251
Opened 2024-07-26 06:10 UTC by minju26

2024-07-26 15:17 UTC, gongdongho12 requested changes
민주님 안녕하세요 1단계 고생하셨습니다

카카오 로그인 처음 구현해 보시는 건데 잘 구현해 주셨어요 💯 
리뷰 확인해서 한번 고민해서 반영 부탁드립니다!

2024-07-26 15:17 UTC, gongdongho12 commented on src/main/java/gift/constant/Message.java
> +    public static final String ALREADY_REGISTERED_ERROR_MSG = "이미 가입된 회원입니다.";
카카오 로그인의 일반적인 페이지에서는 별도 카카오 회원가입 보다는, 로그인만 두고 로그인하고 있으면 -> 로그인되고, 없으면 회원가입 방식으로 가면 `이미 가입된 회원입니다` 메시지는 필요없고 더 사용성이 높아지지 않을까요?

2024-07-26 15:17 UTC, gongdongho12 commented on src/main/java/gift/controller/AuthController.java
카카오 로그인은 Auth 서비스에 일부일 것 같은데요, Auth 서비스의 로그인 메서드로 카카오 로그인 유무 등을 보내서 처리하는 방식으로 메서드를 캡슐화 해보면 어떨까요?

2024-07-26 15:17 UTC, gongdongho12 commented on src/main/java/gift/domain/Member.java
> +        this.isKakao = isKakao;
현재는 카카오 로그인만 존재하지만, 추후 확장성도 고려해두는게 좋지 않을까요?
Enum 타입을 사용해서요!

2024-07-26 15:17 UTC, gongdongho12 commented on src/main/java/gift/controller/AuthController.java
> +    }
카카오 로그인 API를 /members로 사용하는 것 보다는 /members/kakao 이런식으로 url만 보더라도 이해할 수 있도록 정리하는 편이 좋지 않을까요?

2024-07-26 15:17 UTC, gongdongho12 commented on src/main/java/gift/service/KaKaoLoginService.java
> +                .toEntity(String.class);
카카오 로그인이 아니더라도 Bearer 토큰을 헤더에 넣는 과정은 쓸 수 있을 것 같은데요
중복되는 코드를 메서드로 정리해보면 어떨까요?

2024-07-26 15:17 UTC, gongdongho12 commented on src/main/java/gift/service/KaKaoLoginService.java
> +    }
카카오 로그인 암호화를 말씀주셨는데
만약 이렇게 로그인 계정을 만든다면, 일반 로그인은 숫자를 반복적으로 만들어서 넣을 수 있지 않을까요?
1000부터 10000까지요!

그래서 랜덤값도 좋지만 카카오 회원이면 기존 로그인을 막아두는 로직이 있으면 좋을 것 같습니다

2024-07-29 05:09 UTC, minju26 commented on src/main/java/gift/constant/Message.java
> +    public static final String ALREADY_REGISTERED_ERROR_MSG = "이미 가입된 회원입니다.";
앗 저 메세지는 이미 이메일로 회원가입 한 회원이 (같은 이메일 주소로)카카오로 회원가입을 시도 했을 경우에 표시합니다!

2024-07-29 05:10 UTC, minju26 commented on src/main/java/gift/domain/Member.java
> +        this.isKakao = isKakao;
step2을 진행하면서 Enum 타입으로 수정했습니다 :)

2024-07-29 05:10 UTC, minju26 commented on src/main/java/gift/controller/AuthController.java
> +    }
아하! 이해가 쉽도록 그렇게 수정하도록 하겠습니다!

2024-07-29 05:12 UTC, minju26 commented on src/main/java/gift/service/KaKaoLoginService.java
> +    }
비밀번호를 비워두기 좀 그래서 임의로 채워두는 느낌으로 해보았는데, 
아예 막아두는 방향으로 하는 것이 좋을 것 같네요! 그렇게 수정해보도록 하겠습니다👍

2024-07-29 05:16 UTC, minju26 commented on src/main/java/gift/service/KaKaoLoginService.java
> +                .toEntity(String.class);
으음..! 메서드로 정리를 하게 되면 아래와 같이 요청 메서드에 따라 코드가 조금씩 달라질 것 같은데, 이 부분은 어떻게 처리를 해야할까요..?! 
```
client.get().header(~~) 
client.post().header(~~)
```
앗 혹시 `"Authorization", "Bearer " + accessToken` 이것만 메서드로 정리하는 것이 좋을 것 같다고 말씀해주신걸까요?!

2024-07-29 05:24 UTC, minju26 commented on src/main/java/gift/controller/AuthController.java
으음 그러면 일반 로그인은`/members/login`, 카카오 로그인은 `/members/kakao` 이렇게 구분 하되, 
어떤 방식인지 정보를 Auth 서비스의 login 메서드로 넘겨서 둘 다 login 메서드로처리하는 것이 좋을까요?!

2024-07-29 06:30 UTC, minju26 commented on src/main/java/gift/controller/AuthController.java
```
    @PostMapping("/login")
    public ResponseEntity<AuthResponse> memberLogin(@RequestBody AuthRequest authRequest) {
        return new ResponseEntity<>(authService.login(authRequest), HttpStatus.OK);
    }

    @GetMapping("/kakao")
    public ResponseEntity<AuthResponse> kakaoLogin(@RequestParam("code") String code) {
        return new ResponseEntity<>(kaKaoLoginService.kakaoLogin(code), HttpStatus.OK);
    }
```

현재는 이렇게 `이메일 로그인 - id(email),pw 담긴 request`,  `카카오 로그인 - 인가코드` 를 인자로 넘기고 있습니다.
같은 로그인 메서드를 사용한다면.. 현재 다른 것을 전달하고 있는 파라미터를 어떤식으로 처리해야 할지 고민이 됩니다..!

2024-07-29 13:32 UTC, gongdongho12 commented on src/main/java/gift/service/KaKaoLoginService.java
> +                .toEntity(String.class);
client를 호출할때마다 생성해서 사용하고 있어요!

공식문서에 보시면 defaultHeader라는 요소도 있구요!
https://docs.spring.io/spring-framework/reference/integration/rest-clients.html
RestClient.builder()를 커스텀화해서 토큰이 들어가면 넣어주고 하는 객체로 만들어주는게 좋지 않을까요?

지금은 RestClient.builder().build() 빌더인데 빌더처럼 사용하지 않고 그냥 단순 클라이언트 객체로만 쓰고 있으니까요!

2024-07-29 13:32 UTC, gongdongho12 commented on src/main/java/gift/controller/AuthController.java
아 메서드를 합쳐보면 어떻느냐는 의견은 아니구요
authService 서비스 안에서 kakaoLogin도 일부 메서드로 가지고 있게 하는거죠!

사실 Auth 전체 로그인시스템을 가리키고, Kakao로그인은 그 Auth의 일부이니까요!
그래서 AuthService와 KakaoService가 분리되는게 아닌 기능의 포함도에 따라 구성하는게 어떻냐는 의견입니다!

2024-07-29 13:45 UTC, gongdongho12 approved these changes
지난주가 끝난 이후라 반영내용은 3단계에 남겨주세요 😄

2024-07-29 13:45 UTC, merged