충남대 BE_이택 5주차 과제 step2
kakao-tech-campus-2nd-step2/spring-gift-order pull request #254
Opened 2024-07-26 06:31 UTC by LeeTaek2T

2024-07-28 06:19 UTC, ksy90101 requested changes
언제든지 궁금한게 있다면 DM주세요~

2024-07-28 06:19 UTC, ksy90101 commented on src/main/java/gift/DTO/KakaoJwtToken.java
> +  public KakaoJwtToken(Long id, String accessToken, String tokenType, String refreshToken,
여기에 말하고 싶은게, acceessToken, refreshToken만 필요한게 아닐까 해요.
나머지들은 필요한 이유를 여기에 작성해주시면 좋을거 같아요.

2024-07-28 06:19 UTC, ksy90101 commented on src/main/java/gift/DTO/Orders.java
> +public class Orders {
모델링이 이해가 잘 안가는데요.

하나의 주문에 여러개의 상품의 여러개의 옵션이 들어갈수 있어야 하지 않나요?

2024-07-28 06:19 UTC, ksy90101 commented on src/main/java/gift/Service/OrderService.java
> +  public OrderDto orderOption(OrderDto orderDto) {
트랜잭션 보장이 가능한가요?

2024-07-28 06:51 UTC, LeeTaek2T commented on src/main/java/gift/DTO/KakaoJwtToken.java
> +  public KakaoJwtToken(Long id, String accessToken, String tokenType, String refreshToken,
토큰의 구조를 살펴보니 말씀해주신 Token외에 다른 것들은 필요하지 않은 것 같아 삭제하였습니다.
그리고 id는 데이터를 가져올 때 좀 더 편리하게 갖고오기 위해 넣었습니다.
혹시 토큰을 저장할 때는 토큰 자체는 unique하게 발급되니까 토큰에 @Id를 해줘야 하나요? 아니면 저와 같이 id를 따로 만들어줘도 될까요?

2024-07-28 07:05 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Orders.java
> +public class Orders {
하나의 옵션을 다수의 사용자들이 이용한다고 생각하여 이전과 같이 했었는데 다시 생각해보니 멘토님의 말씀이 맞는 것 같습니다. 수정하겠습니다

2024-07-28 08:38 UTC, LeeTaek2T commented on src/main/java/gift/Service/OrderService.java
> +  public OrderDto orderOption(OrderDto orderDto) {
order를 하는동안 optino이 바뀌는 등 문제가 생길 수 있으니 해당 함수가 실행되는 동안 다른 것이 관련된 것들을 간섭할 수 없게 하겠습니다.

2024-07-28 12:13 UTC, ksy90101 commented on src/main/java/gift/DTO/KakaoJwtToken.java
> +  public KakaoJwtToken(Long id, String accessToken, String tokenType, String refreshToken,
id는 가지고 있어도 됩니다~
다른 값들중에 쓰지 않는 값들을 지워보자는 의미였어요.

2024-07-30 06:08 UTC, ksy90101 approved these changes
허들에서 이야기한대로 3단계예서 허들에 피드백 드린거 수정 부탁드립니다~

2024-07-30 06:08 UTC, merged