경북대 BE_주보경 5주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #265
Opened 2024-07-26 07:26 UTC by jupyter471

서비스와 컨트롤러의 메서드가 너무 무거워지는 느낌입니다. 
http 요청은 서비스말고 따로 처리할 수 있을까요?

우선 구현만 해두어서 코드가 깔끔하지 않은데 오늘내로 리팩토링하겠습니다!

2024-07-29 18:55 UTC, sang5c commented
리뷰는 오늘(30일)중으로 진행하겠습니다 :)  
3단계가 준비 되시면 같이 올려주세요~!

2024-07-30 10:31 UTC, jupyter471 commented
> 리뷰는 오늘(30일)중으로 진행하겠습니다 :) (재촉이 아니고 안내입니다)
> 
> 3단계가 준비 되시면 같이 올려주세요~!

3단계까지 모두 구현 완료하였습니다 ㅎㅎ 일정이 밀려 정말 죄송합니다...

2024-07-30 17:31 UTC, sang5c requested changes
swagger까지 고생하셨습니다!  
리뷰 확인하시고, 수정해주세요 :) 

> http 요청은 서비스말고 따로 처리할 수 있을까요?

말씀하시는 infra를 어떻게 정의하셨는가에 따라 다릅니다. 분리는 자유입니다~

> 주문 트랜잭션 API 호출 분리 관련

장단점과 상황에 따라 판단하고 선택해야 합니다.  
상황에 맞게 판단하고 수행해야 하고, 이렇게 해야한다는 없습니다.  

어려웠던 점에 작성하신 질문도 동일한 답변을 드립니다. :)  
신경쓰인다면 분리한 후 장단점을 비교해보시면 좋을 것 같습니다.

2024-07-30 17:31 UTC, sang5c commented on src/main/java/gift/service/KakaoOAuthService.java
> +        System.out.println(response.getBody());
직접 출력하는 대신 로거를 이용해보면 어떨까요?
```java
private static final Logger log = LoggerFactory.getLogger(KakaoOAuthService.class);

// 사용
log.info("hello world!");
```

2024-07-30 17:31 UTC, sang5c commented on src/main/java/gift/service/KakaoOAuthService.java
> +        if (response.getStatusCode() != HttpStatus.OK) {
예외 처리 부분은 추후 문제를 해결하는 과정에서 굉장히 큰 역할을 수행합니다.  
1단계의 힌트를 참고해서 예측 가능한 에러에 대한 처리와 로그를 상세히 남겨보면 어떨까요?

2024-07-30 17:31 UTC, sang5c commented on src/main/java/gift/service/KakaoOAuthService.java
> +    }
response body를 객체로 받으면 map을 사용하거나, JsonNode를 다루지 않을 수 있어 좀 더 명확한 코드가 될 것 같습니다.

2024-07-30 17:31 UTC, sang5c commented on src/main/java/gift/infra/TemplateObject.java
> +public record TemplateObject(String object_type, @Length(min = 1, max = 200) String text, Link link) {
자바에서 변수는 카멜 케이스로 사용합니다.  
링크를 참고해서 수정해주세요. 키워드는 jackson annotations 입니다.  
https://www.baeldung.com/jackson-annotations#1-jsonproperty

2024-07-30 17:31 UTC, sang5c commented on src/main/java/gift/infra/TemplateObject.java
> +    public record Link(String web_url, String mobile_web_url) {
여기도 같습니다~

2024-07-30 17:31 UTC, sang5c commented on src/main/java/gift/service/KakaoOAuthService.java
> +        RestClient client = RestClient.builder().build();
힌트를 꼭 정독해보시고, 외부 API 호출에서 가장 중요한 요소인 예외 처리, 로그, 타임아웃 설정을 진행해주세요!

2024-07-30 17:31 UTC, sang5c commented on src/main/java/gift/controller/OrderController.java
> +    @ApiResponses({
java 8 이후로 wrapper annotation을 사용하지 않아도 됩니다.  

```java
@ApiResponse(responseCode = "201", description = "주문 성공")
@ApiResponse(responseCode = "400", description = "잘못된 요청")
```

2024-07-30 17:31 UTC, sang5c commented on src/main/java/gift/service/OrderService.java
> +    public void handleOrder(Long memberId, OrderRequestDto request) {
주문 내역에 대한 저장은 따로 하지 않아도 괜찮을까요?

2024-07-30 17:31 UTC, sang5c commented on src/main/java/gift/service/OrderService.java
> +        //1. 옵션 수량 차감
주석이 없어도 동일한 의미를 나타내고 있습니다!

2024-07-30 17:31 UTC, sang5c commented on src/main/java/gift/service/OrderService.java
> +            templateObjectJson = objectMapper.writeValueAsString(templateObject);
메서드로 분리하면 중괄호 밖의 값에 대해 제어하지 않아도 됩니다.

2024-07-30 17:31 UTC, sang5c commented on src/main/java/gift/service/OrderService.java
> +    private void sendMessage(String accessToken) {
메서드가 20라인이네요! 메서드 분리를 시도해보면 어떨까요?

2024-07-30 17:31 UTC, sang5c commented on src/main/java/gift/service/OrderService.java
> +        body.add("template_object", templateObjectJson);
Map이 너무 많네요! 과도한 Map 사용은 유지보수를 어렵게 만듭니다.

2024-07-30 17:31 UTC, sang5c commented on src/main/resources/application.properties
> +kakao.redirect-u-rL=http://localhost:8080/oauth/kakao/redirect
오타가 있는 것 같네요

2024-07-30 17:31 UTC, sang5c commented on src/test/java/gift/RestTemplateTest.java
> +public class RestTemplateTest {
주석 처리되면 관리되지 않을 가능성이 높습니다. 제거를 고려해주세요~

2024-07-30 17:34 UTC, sang5c commented
협업 과제를 우선적으로 수행해주세요!

2024-07-31 04:23 UTC, jupyter471 commented on src/main/java/gift/service/KakaoOAuthService.java
> +        System.out.println(response.getBody());
넵 수정하겠습니다!

2024-07-31 04:55 UTC, jupyter471 commented on src/main/java/gift/infra/TemplateObject.java
> +public record TemplateObject(String object_type, @Length(min = 1, max = 200) String text, Link link) {
카카오에서 명시하는 변수와 맞추다보니 실수했습니다...ㅜㅜ JsonProperty 어노테이션을 활용하여 해결하였습니다!

2024-07-31 04:56 UTC, jupyter471 commented on src/main/java/gift/service/OrderService.java
> +    public void handleOrder(Long memberId, OrderRequestDto request) {
6주차  요구사항에 주문내역에 대한 요구사항이 있습니다 미리 적용해두겠습니다!

2024-07-31 04:56 UTC, jupyter471 commented on src/main/java/gift/service/OrderService.java
> +        //1. 옵션 수량 차감
제거하겠습니다!

2024-07-31 04:58 UTC, jupyter471 commented on src/main/resources/application.properties
> +kakao.redirect-u-rL=http://localhost:8080/oauth/kakao/redirect
자동완성으로 제공되는 것을 사용하다보니  아무생각없이 사용했네요... 수정하겠습니다!

2024-07-31 05:51 UTC, jupyter471 commented on src/main/java/gift/controller/OrderController.java
> +    @ApiResponses({
제가 이해한게 맞는지 확인하고 싶습니다...! @ApiResponses를 인터페이스로 등록하고 Repeatable로 클래스 위에서 정의하라는 말씀이신가요..?

2024-07-31 05:52 UTC, jupyter471 commented on src/main/java/gift/service/OrderService.java
> +    private void sendMessage(String accessToken) {
넵..!

2024-07-31 06:59 UTC, jupyter471 commented on src/main/resources/application.properties
> +kakao.redirect-u-rL=http://localhost:8080/oauth/kakao/redirect
엇 멘토님 url 로 바꾸니깐 url이 이상하게 주입되는 것 같습니다...! 일단 원래대로 변경해두겠습니다...!

2024-07-31 07:02 UTC, jupyter471 commented on src/main/java/gift/service/KakaoOAuthService.java
> +    }
JsonProperty로 필요한 필드 지정해두고 response를 .toEntity(생성한 DTO)로 받아오는 방식으로 변경하겠습니다!

2024-07-31 08:53 UTC, jupyter471 commented on src/test/java/gift/RestTemplateTest.java
> +public class RestTemplateTest {
제거 해두겠습니다

2024-07-31 08:54 UTC, jupyter471 commented on src/main/java/gift/service/KakaoOAuthService.java
> +        if (response.getStatusCode() != HttpStatus.OK) {
로그로 에러를 받아와 남기도록 하였습니다 감사합니다

2024-07-31 10:03 UTC, jupyter471 commented on src/main/java/gift/service/OrderService.java
> +            templateObjectJson = objectMapper.writeValueAsString(templateObject);
객체로 값을 받아오면서 해당 로직은 필요없게 되었습니다 ㅎㅎ 삭제하겠습니다!

2024-07-31 10:06 UTC, jupyter471 commented on src/main/java/gift/service/KakaoOAuthService.java
> +        RestClient client = RestClient.builder().build();
공부해보겠습니다...!

2024-07-31 10:35 UTC, jupyter471 commented on src/main/java/gift/service/OrderService.java
> +            templateObjectJson = objectMapper.writeValueAsString(templateObject);
넵 분리하겠습니다

2024-07-31 10:40 UTC, jupyter471 commented on src/main/java/gift/service/OrderService.java
> +            templateObjectJson = objectMapper.writeValueAsString(templateObject);
Json으로 변환하고 예외를 처리하는 부분을 util로 아예 빼두었습니다!

2024-07-31 10:42 UTC, jupyter471 commented on src/main/java/gift/service/OrderService.java
> +        body.add("template_object", templateObjectJson);
카카오로 Post하는 경우에는 Map방식이 필요한 것 같습니다...! 다른 방법이 있는지 더 알아보겠습니다.

2024-07-31 13:19 UTC, jupyter471 commented on src/main/java/gift/service/KakaoOAuthService.java
> +        if (response.getStatusCode() != HttpStatus.OK) {
RestClient는 좀 더 간편하게 에러를 처리할 수 있는 것 같습니다
```
.onStatus(HttpStatusCode::isError, (req, res) -> {
                    log.error("Error Response Body: {}", (res.getBody()));
                    throw new IllegalArgumentException("사용자 정보 조회 오류");
                })
```
이렇게 처리하였습니다! isError는 4xx, 5xx 모두 포함하는 로직입니다!

2024-08-01 12:37 UTC, sang5c approved these changes
머지하겠습니다~!  
몇가지 리뷰 남겼으니 확인해주세요.

2024-08-01 12:37 UTC, sang5c commented on src/test/java/gift/E2ETest.java
>          System.out.println(response.getBody());
여기도 출력이 하나 남았네요~  
테스트 코드에선 단정문을 사용해주세요

2024-08-01 12:37 UTC, sang5c commented on src/main/java/gift/service/OrderService.java
> +    private void sendMessage(String accessToken) {
메서드 분리가 아직 안됐네요!

2024-08-01 12:37 UTC, sang5c commented on src/main/java/gift/controller/OrderController.java
> +    @ApiResponses({
`@ApiResponses`를 제거하셔도 동일한 코드라는 의미입니다~

2024-08-01 12:37 UTC, sang5c commented on src/main/java/gift/infra/TemplateObject.java
> +public record TemplateObject(String object_type, @Length(min = 1, max = 200) String text, Link link) {
`@JsonNaming`도 찾아보시면 좋겠네요 :)

2024-08-01 12:37 UTC, merged