충남대 BE_정현서 5주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #276
Opened 2024-07-26 08:05 UTC by hynseoj

2024-07-28 06:16 UTC, ksy90101 requested changes
고생하셨습니다~
질문은 DM주시면 허들로 한번 이야기 나눠요!

2024-07-28 06:16 UTC, ksy90101 commented on src/main/java/gift/auth/oauth/entity/OauthToken.java
> +        }
if문이 있어야 하는 이유가 무엇인가요?

2024-07-28 06:16 UTC, ksy90101 commented on src/main/java/gift/domain/order/controller/OrderRestController.java
> +        };
이거에 대해 트랜잭션 보장을 할 필요가 없을까요?

2024-07-28 06:16 UTC, ksy90101 commented on src/main/java/gift/domain/order/dto/OrderRequest.java
> +    int totalPrice
여기에 대해선 validate가 필요 없을까요?

2024-07-28 06:16 UTC, ksy90101 commented on src/main/java/gift/domain/order/entity/Order.java
> +    private String message;
이 message는 어떤걸 의미하나요?

2024-07-28 06:16 UTC, ksy90101 commented on src/main/java/gift/domain/order/entity/OrderItem.java
> +    private Option option;
해당 option이 product에 option이라는걸 보장해야 하지 않을까요?
데이터 무결성 관점에서요.

2024-07-28 06:16 UTC, ksy90101 commented on src/main/java/gift/domain/order/service/OrderItemManager.java
> +    public void create(User user, Order order, List<OrderItemRequest> orderItemRequests) {
1. service가 아닌 이유가 무엇인가요?
2. 트랜잭션 보장이 되나요?

2024-07-28 06:21 UTC, hynseoj commented on src/main/java/gift/auth/oauth/entity/OauthToken.java
> +        }
카카오 API 명세를 보니까 갱신 요청 시에는 refresh token의 만료 시간이 1개월 미만으로 남았을 때만 응답으로 전달된다고 해서 이 경우에는 DB의 refresh token 값이 바뀌지 않도록 조건문을 추가했습니다!

2024-07-28 06:25 UTC, hynseoj commented on src/main/java/gift/domain/order/controller/OrderRestController.java
> +        };
사용자가 구매 여부를 정확하게 인지할 수 있게 하기 위해서는 트랜잭션으로 묶는 게 좋을 것 같습니다.
코드를 짜면서 아직 트랜잭션을 고려보지 않았는데 전체적으로 생각해보고 수정해보겠습니다!

2024-07-28 06:27 UTC, hynseoj commented on src/main/java/gift/domain/order/dto/OrderRequest.java
> +    int totalPrice
message는 사용자의 선택사항이라고 판단했고, totalPrice에 대해서는 필요할 것 같습니다! 빠뜨렸습니다...하하

2024-07-28 06:28 UTC, hynseoj commented on src/main/java/gift/domain/order/entity/Order.java
> +    private String message;
수령인에게 전달될 메시지입니다. 좀 더 의미를 표현할 수 있는 이름을 생각해보겠습니다!

2024-07-28 06:31 UTC, hynseoj commented on src/main/java/gift/domain/order/entity/OrderItem.java
> +    private Option option;
맞습니다! 구매 로직 상에서는 product와 option의 관계를 확인하고 있는데, entity validation을 아직 구현하지 못했습니다.. 해보겠습니다!

2024-07-28 06:45 UTC, hynseoj commented on src/main/java/gift/domain/order/service/OrderItemManager.java
> +    public void create(User user, Order order, List<OrderItemRequest> orderItemRequests) {
1. 해당 클래스를 OrderService에서 사용해야 하는데 Service 계층 간 의존성을 가지지 않도록 Manager 라는 이름으로 component로 등록했습니다.
   지금까지는 Service 클래스에서 다른 Service와 Respository를 기준 없이 가지고 있었는데 의존 관계를 관리하기 어려운 것 같아 계층을 분리해봤습니다. 그런데 아직 다 정리되진 않은 것 같습니다..😅
2.  보장되지 않습니다. 옵션 차감과 주문 목록에 아이템을 추가하는 일을 한 단위로 묶을 필요가 있습니다. 수정하겠습니다!

2024-07-29 05:31 UTC, ksy90101 approved these changes
고생하셨습니다~

2024-07-29 05:31 UTC, merged