경북대 BE_김민주 5주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #289
Opened 2024-07-26 08:30 UTC by minju26

2024-07-27 12:19 UTC, gongdongho12 requested changes
2단계 작업도 고생 많으셨습니다!

리뷰 확인해서 3단계 작업까지 화이팅입니다

2024-07-27 12:19 UTC, gongdongho12 commented on src/main/java/gift/domain/KakaoToken.java
> +    private Member member;
카카오 토큰과 멤버가 1:1이면 별도로 DB를 분리하지 않아도 괜찮지 않을까요?
그냥 멤버 엔티티에 토큰을 nullable로 두면 되지 않을까 싶어서요!

2024-07-27 12:19 UTC, gongdongho12 commented on src/main/java/gift/service/OrderService.java
> +        sendMessage(orderRequest.message(), token.getAccessToken());
이 처리는 현재 로그인 정보가 카카오일때만인데 조건을 따로 넣지 않아도 괜찮을까요?
카카오 로그인 객체가 아니면 카카오 토큰이 없을 거니까요

2024-07-27 12:19 UTC, gongdongho12 commented on src/test/java/gift/service/OrderServiceTest.java
> +                .isEqualTo(initQuantity - orderRequest.quantity());
리뷰 반영해주셨군요 👍🏼

2024-07-29 05:35 UTC, minju26 commented on src/main/java/gift/domain/KakaoToken.java
> +    private Member member;
아하 그런 방법도 있네요!
토큰 테이블을 분리할 때, 혹시 추후에 토큰을 redis와 같은 다른 db에서 관리하게 될 수 있을 것 같아서 분리해보았습니다.
아직 그럴 경우는 없을 것 같으니 nullable을 활용하는 방법으로 수정해보겠습니다 :)

2024-07-29 05:37 UTC, minju26 commented on src/main/java/gift/service/OrderService.java
> +        sendMessage(orderRequest.message(), token.getAccessToken());
으음! 로그인 객체인지 확인하는 로직을 추가해야겠네요..!!
추가해보록 하겠습니다 :)

2024-07-29 05:38 UTC, minju26 commented
개인적인 사정이 있어서 피드백 해주신 내용 확인이 늦었습니다🥹 
오늘 내로 모두 반영해서 수정하도록 하겠습니다!

2024-07-29 13:34 UTC, gongdongho12 commented on src/main/java/gift/domain/KakaoToken.java
> +    private Member member;
join의 리소스와 고작 단순 2개의 칼럼 추가에 대한 리소스를 비교한다면 join이 확실히 더 많은 리소스를 차지하거든요!
넵 말씀주신대로 레디스를 적용한다면 말씀주신 방향이 좋겠지만 이렇게 DB로 간다면 되도록 1:1관계는 분리하지 않는게 좋은 것 같습니다!

2024-07-29 13:46 UTC, gongdongho12 approved these changes
지난주가 끝난 이후라 반영내용은 3단계에 남겨주세요 😄 
앗 conflict... 😢

2024-07-29 13:51 UTC, minju26 commented
> 지난주가 끝난 이후라 반영내용은 3단계에 남겨주세요 😄 앗 conflict... 😢

넵 알겠습니다!
으악.. 전 커밋에 이어서 분기했는데도 충돌이 나네요.. 지금 해결해서 푸시 하겠습니다!

2024-07-29 13:59 UTC, merged