부산대 BE_박혜연 5주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #290
Opened 2024-07-26 08:37 UTC by hyyyh0x

테스트 코드를 아직 작성하지 못했습니다. 과제 제출 기한이 다가와서 미리 올려둡니다.
테스트 코드 작성을 완료하고 다시 리뷰 요청 드리겠습니다!

### 멘토링에서 말씀해주신 부분
1. 멘토링에서 말씀드린 상품 업데이트시 DB 아이디 변경되는 문제는 해결했습니다. 원인은 category 값 설정에 있었습니다.. 부모에서 자식과의 관계를 끊고 있었습니다. 이제 정상적으로 작동합니다!
2. 말씀해주신 양방향, 단방향도 수정해두었습니다. 필요하다고 생각되는 부분은 계속 양방향으로 두었습니다.
3. Filter도 추가, 헷갈리지 않도록 변수와 메서드 이름도 변경했습니다.

### 변경사항
1. wishList에서 상품은 중복될 수 있도록 변경하였고 이에 따라 컨트롤러도 위시리스트 아이디 값으로 삭제, 수정하는 것으로 변경하였습니다. (상품, 옵션 둘다 같으면 변경 불가)

2. optionService의 subtract를 카카오 메시지를 보내는 데에 성공하면 차감할 수 있도록 설정했습니다.
subtract 메서드 안에 있던, `옵션 수량보다 많은 요청을 하면 에러 메시지를 띄우는 부분`은 따로 다른 메서드에 분리해두어 메시지를 보내기 전에 상품을 구매 가능한지 확인하도록 했습니다.
메시지를 보내는 데에 실패했을 때에는 구매가 완료되지 않도록 하기 위해 변경했습니다.

3. 토큰 저장에 관련한 클래스(entity, repository, service) 들이 카카오 폴더에 있는 것은 적절하지 않다고 생각하여 따로 토큰 폴더를 만들어 옮겼습니다.

### 진행 중
카카오 뿐만 아니라 다른 소셜미디어와도 연결 할 수 있도록 변경하고 있습니다. 테스트 추가하면서 같이 추가하겠습니다.

2024-07-26 15:00 UTC, hyyyh0x commented
완료했습니다. 테스트 코드는 너무 오래 걸려서 전부 추가 하지는 못했고 이번 과제 위주로 추가했습니다.

2024-07-27 11:33 UTC, yoo-jaein requested changes
step2 고생하셨습니다!
코멘트 확인 부탁드립니다 :)

2024-07-27 11:33 UTC, yoo-jaein commented on src/main/java/gift/users/kakao/KakaoOrderService.java
> +    public KakaoOrderDTO kakaoOrder(long userId, KakaoOrderDTO kakaoOrderDTO,
```@Transactional``` 을 메서드에 추가해서 주문 프로세스 전체가 하나의 트랜잭션으로 처리되도록 하면 좋겠습니다!

2024-07-27 11:33 UTC, yoo-jaein commented on src/main/java/gift/users/kakao/KakaoOrderService.java
> +        ObjectNode templateObject = objectMapper.createObjectNode();
ObjectNode 대신 java 객체를 직접 사용할 수도 있습니다.
```java
// 객체 선언
public record KakaoMessageTemplate {
    private String objectType;
    private Content content;
    private List<Item> items;
    private List<Button> buttons;
}

public record Content {
    private String title;
    private String description;
    private String imageUrl;
    private int imageWidth;
    private int imageHeight;
}

public record Item {
    private String itemName;
    private String itemSubtitle;
    private int quantity;
}
...
```

```java
private String makeKakaoMessage(KakaoOrderDTO kakaoOrderDTO) {
    ObjectMapper objectMapper = new ObjectMapper();

    KakaoMessageTemplate template = new KakaoMessageTemplate();
    template.setObjectType("commerce");

    Content content = new Content();
    content.setTitle("주문이 완료되었습니다");
    content.setDescription("주문 내역을 확인해주세요");
    content.setImageUrl(productService.getProductById(kakaoOrderDTO.productId()).getImageUrl());
    content.setImageWidth(640);
    content.setImageHeight(640);
    template.setContent(content);

    ...

    Button button = new Button();
    button.setTitle("주문 상세 보기");
    Link link = new Link("https://yourwebsite.com/orders");
    button.setLink(link);
    ...

    String messageObject;
    try {
        messageObject = objectMapper.writeValueAsString(template); // 여기
        logger.info("json: {}", messageObject);
    } catch (JsonProcessingException e) {
        throw new KakaoOrderException("잘못된 json 형식입니다.");
    }
    return URLEncoder.encode(messageObject, StandardCharsets.UTF_8);
}
```

2024-07-27 11:33 UTC, yoo-jaein commented on src/main/java/gift/users/user/User.java
> +    private String snsId;
다른 서비스 로그인에도 대응할 수 있게 확장성있게 바뀐게 좋네요!

2024-07-27 11:33 UTC, yoo-jaein commented on src/main/java/gift/users/kakao/KakaoOrderService.java
> +                .body("template_object=" + messageObject).retrieve().toEntity(String.class);
```java
    ResponseEntity<KakaoApiResponse> response;
    try {
        response = restClientBuilder.build()
            .post()
            .uri(kakaoProperties.sendToMeUrl())
            .header(HEADER_NAME, kakaoProperties.userHeaderValue() + " " + accessToken)
            .body("template_object=" + messageObject)
            .retrieve()
            .toEntity(KakaoApiResponse.class);
```
응답을 처리할 때 String이 아니라 KakaoApiResponse 객체를 만들어서 사용하면 타입 안정성이 보장됩니다. 추가로 API 응답 형식이 변경되더라도 KakaoApiResponse 클래스만 수정하면 되기 때문에 유지보수하기도 편해집니다!

2024-07-28 09:24 UTC, hyyyh0x commented
메시지를 보냈을 때 버튼이 나오지 않는데 이유를 모르겠습니다...

피드백 주신 부분들은 수정 완료했습니다!

2024-07-28 12:18 UTC, yoo-jaein approved these changes
버튼 나오지 않는 부분은 저도 체크해보겠습니다.
우선 리뷰 반영된 것은 확인하였고, 다음 단계 진행을 위해 머지할게요!

2024-07-28 12:18 UTC, merged