전남대 BE_나제법 5주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #295
Opened 2024-07-26 08:43 UTC by nove1080

Kakao 소셜 로그인을 사용하도록 코드를 변경하여 `MemberApiControllerTest`를 주석처리하였습니다. 
매번 리뷰를 남겨주셔서 감사합니다!

2024-07-27 08:55 UTC, Hongdonggeon requested changes
안녕하세요 제법님
미션 구현하시느라 수고 많으셨습니다!
기존 회원 기능 다시 살리는 것 이외에는 따로 코멘트 드릴 거 없는 것 같아요!
회원 기능 및 로그인 페이지 구현해주시고 다시 요청주십쇼!

2024-07-27 08:55 UTC, Hongdonggeon commented on src/main/java/gift/authentication/filter/AuthenticationFilter.java
> +    private final List<String> ignorePaths = List.of("/api/login/oauth2/kakao");
webMvcConfiguration에서 경로를 제외시키는게 좋지 않을까요?

2024-07-28 02:26 UTC, nove1080 commented on src/main/java/gift/authentication/filter/AuthenticationFilter.java
> +    private final List<String> ignorePaths = List.of("/api/login/oauth2/kakao");
```java
@Bean
public FilterRegistrationBean authenticationFilter() {
    FilterRegistrationBean filterRegistrationBean = new FilterRegistrationBean();
    filterRegistrationBean.setFilter(new AuthenticationFilter(jwtResolver));
    filterRegistrationBean.addUrlPatterns("/api/*");  //제외 대상 경로를 빼고 모두 등록한다(?)
    filterRegistrationBean.setOrder(2);
    return filterRegistrationBean;
}
```

설정 파일에서 위와 같이 `addUrlPatterns`를 사용하여 제외할 경로를 빼고 모두 등록하는 것은 오히려 어떤 경로가 적용이 안되는 건지 파악하기 더 어려울 것 같아서 필터를 적용하지 않을 경로만 명시하고 싶어서 `shouldNotFilter` 를 오버라이딩 하여 구현하였습니다.


```java
@Override
protected boolean shouldNotFilter(HttpServletRequest request) throws ServletException {
    return ignorePaths.contains(request.getRequestURI());
}
```

인터셉터의 경우에는

```java
@Configuration
public class WebConfig implements WebMvcConfigurer {

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        
        registry.addInterceptor(new CustomInterceptor())
                .order(1)
                .addPathPatterns("/**")
                .excludePathPatterns("/","/members/add","/login","/logout","/css/**","/*.ico","/error"); //제외 대상 경로 등록이 편함(?)
    }

}
```
`excludePathPatterns`를 사용하여 적용하지 않을 경로를 명시해주는 것이 가능한데 필터의 경우에는 `특정 경로만 제외시키기` 를 만들어내기 까다로운 것 같아서 지금의 코드를 작성하였습니다 다른 좋은 방법이 있을까요? 동건님은 어떻게 생각하시나요?

2024-07-28 05:46 UTC, Hongdonggeon commented on src/main/java/gift/authentication/filter/AuthenticationFilter.java
> +    private final List<String> ignorePaths = List.of("/api/login/oauth2/kakao");
filter도 interceptor처럼 excludePathPatterns 같은 메서드를 지원하는거로 헷갈렸네요.. 제법님의 방식 좋은 것 같아요

2024-07-28 06:20 UTC, Hongdonggeon commented
- member 테이블 설계
좋은 고민인 것 같아요. 저라면, 소셜 로그인 멤버와 자체 회원 멤버 데이터들은 한 테이블에서 관리하고 password 테이블을 분리시킬 것 같아요
그렇다면 password를 가지고 있는 user에 대해서만 관리할 수있을 것 같네요!
또한 이건 참고차 말씀드리는데요! 현재 password raw 값을 암호화하지 않고 있는데, 실무에서는 이런 인증에 관련된 값들은 암호화를 해주어야해요. 암호화하는데 필요한 값들에 대해서도 password 테이블에서 함께 관리하면 좋을 것 같네요


- 토큰 저장
이것도 좋은 고민이고요. 현재 jwt 토큰을 탈취하면 social token을 알아낼 수 있는 상황이잖아요
일단 지금 떠오르는 생각으로는 토큰값을 암호화해서 암호화된 값을 페이로드로 전달하고 서버에서 암호화된 값을 복호화해서 사용하는 방법이 떠오르고요(다른 방법도 생각해볼게요)
그리고 토큰의 만료기간을 짧게 설정하고, 리프레쉬 토큰을 이용하는 방법도 생각해보면 좋을 것같고요
현재 local storage에서 저장하고 있는데 로컬 스토리지보다 다른 저장소에서 보관하는게 더 보안적으로 좋을 곳이 있을지에 대해서도 고민해보면 좋을 것 같아요

2024-07-28 06:21 UTC, Hongdonggeon approved these changes
안녕하세요 제법님
리뷰 반영하시느라 수고많으셨습니다
질문에 대한 코멘트들은 남겨놓았어요!
주말에 수고많으셨습니다!

아 jwt private key가 지금 git 에 올라와있는 것 같은데 이것도 확인한번해주세요!

2024-07-28 06:21 UTC, merged