강원대 BE_안승환 5주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #315
Opened 2024-07-26 08:56 UTC by Awhn

과제 제출을 위해 부득이하게 이전 커밋을 포함하여 제출합니다. 1단계가 병합된 이후 수정하겠습니다.
카카오 로그인 처리와 주문하기 기능을 구현하였습니다.

2024-07-28 06:50 UTC, jaymarystella requested changes
안녕하세요 2단계 구현고생많으셨습니다.
몇가지 코멘트 남겼는데 확인부탁드립니다.

2024-07-28 06:50 UTC, jaymarystella commented on src/main/java/gift/service/KakaoLoginService.java
> +                });
중복로직들을 분리해볼 수 있을까요?

2024-07-28 06:50 UTC, jaymarystella commented on src/main/java/gift/service/MemberService.java
> +        }
save시 발생할 수 있는 예외가 모두 email이 유효하지 않음이 보장되는것이 맞을까요?

2024-07-28 06:50 UTC, jaymarystella commented on src/main/java/gift/service/OptionService.java
> +                .orElseThrow(() -> new NoSuchElementException("Options not found for option id: " + optionId));
모든 options를 가져오면서 상품id를 가져오는방법 말고 다른 방법도 있을까요?

2024-07-28 06:50 UTC, jaymarystella commented on src/main/java/gift/service/OrderService.java
> +        deleteWishlist(token, orderDTO.optionId());
order는 save되고 wishlist는 삭제가 실패하면 어떻게 될까요?

2024-07-28 06:50 UTC, jaymarystella commented on src/main/java/gift/service/OptionService.java
> +    public int findProductIdByOptionId(int optionId) {
테스트코드가 없네요 빠진부분들도 전체적으로 확인부탁드려요

2024-07-28 19:53 UTC, Awhn commented on src/main/java/gift/service/KakaoLoginService.java
> +                });
넵, requestBuilder를 활용하여 중복 로직을 제거하였습니다.

2024-07-28 19:53 UTC, Awhn commented on src/main/java/gift/service/OptionService.java
> +                .orElseThrow(() -> new NoSuchElementException("Options not found for option id: " + optionId));
검색하지 않고, repository에서 직접 상품 id를 찾을 수 있도록 하였습니다.

2024-07-28 19:55 UTC, Awhn commented on src/main/java/gift/service/OrderService.java
> +        deleteWishlist(token, orderDTO.optionId());
기대한 로직과 다르게 작동하지만, 사용자나 개발자가 이를 알 수 없어 수정이 필요할 거 같습니다. Transactional 어노테이션을 붙여 일관성을 유지하였습니다.

2024-07-28 19:55 UTC, Awhn commented on src/main/java/gift/service/OptionService.java
> +    public int findProductIdByOptionId(int optionId) {
넵, 누락된 테스트를 추가하였습니다.

2024-07-28 19:56 UTC, Awhn commented
2단계에서 주신 피드백을 반영하고, 추가적으로 3단계 api 문서 작성도 swagger로 구현하였습니다.

2024-07-29 13:49 UTC, jaymarystella requested changes
단계를 구분해서 제출해주세요 이거는 규칙이라 이렇게 내시면 안될거같습니다...

2024-07-29 14:16 UTC, Awhn commented
넵 3단계 수행한 내용 취소하였습니다.

2024-07-30 14:45 UTC, jaymarystella approved these changes
고생하셨습니다 다음단계 올려주세요

2024-07-30 14:45 UTC, merged