경북대 BE_박준석_ 5주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #318
Opened 2024-07-26 08:58 UTC by Lucerna00

과제 마감 시간을 맞추기 위해 간단히 기능 구현만 하고 제출합니다.
1단계 피드백을 반영하며 계속해서 개발하겠습니다.

2024-07-27 13:07 UTC, gongdongho12 requested changes
5주차 과제도 벌써 2단계네요!
리뷰 내용 한번 확인해주시구
카카오 로그인 테스트 추가해주시면 좋을 것 같습니다

고생 많으셨습니다!

앗 Conflct 건도 확인해주세요!

2024-07-27 13:07 UTC, gongdongho12 commented on src/main/java/gift/controller/LoginController.java
> +}
아래 기능은 LoginController 라고 하기 보다는 KakaoLoginController로 명명하면 좋을 것 같은데요
그리고 path를 둘다 /kakao로 시작하는게 맞지 않을까요?

2024-07-27 13:07 UTC, gongdongho12 commented on src/main/java/gift/service/MemberService.java
> +    }
이렇게 사용자에게 제공하면 json 구조에
```
{
 "token:", "token"
}
```
이렇게 들어가지 않을까요?
그리고 추후 Swagger 같은 곳에서 객체 구조 추론이 들어가는데 Map의 경우엔 정확하게 반영이 안되서 별도로 DTO를 만들어두는게 좋을 것 같습니다

2024-07-28 11:14 UTC, Lucerna00 commented
주문 시, 위시 리스트에서 해당 상품을 삭제하고 '나에게 보내기'로 메시지가 전송되도록 하였습니다.
추가로 말씀해 주신 피드백도 반영하였습니다!

2024-07-28 11:35 UTC, gongdongho12 approved these changes
빠르게 반영해주셨군요 👍🏼
시간이 얼마 남지 않았지만 3단계도 화이팅입니다!

2024-07-28 11:35 UTC, merged