강원대 BE_김병수 5주차 과제 (step2)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #333
Opened 2024-07-26 19:23 UTC by GamJaDo

# 어려웠던 점
- 이번주차 과제들은 대부분 어려웠습니다.
- 특히 step2는 외부 api를 2개(카카오 메시지, 카카오 사용자 정보)를 사용하여 미션을 구현해야 했으며 특히 미션 중 "해당 상품이 위시 리스트에 있는 경우 위시 리스트에서 삭제한다." 이부분이 제일 어려웠습니다. 기존의 자체 로그인을 하였을 때 Wishlist 기능을 사용하는것은 쉬웠지만, 카카오로그인을 하고 Wishlist 기능을 사용할 수 없었습니다. 카카오 로그인을 하고 db에 저장을 하지 않아 email 정보도 찾을 수 없었기에 우선 카카오로그인을 하고 사용자 이메일을 가져오기 위한 [사용자 정보 api](https://kapi.kakao.com/v2/user/me) 사용하기와 자체로그인 토큰과 카카오로그인 토큰을 구분해서 accessToken을 파서하는 것에 시간이 매우 오래걸렸습니다. (7/25 ~ 7/27)

2024-07-27 15:22 UTC, jaymarystella requested changes
안녕하세요 2단계 구현 고생많으셨습니다.
몇가지 코멘트 남겼는데 확인 부탁드립니다.

2024-07-27 15:22 UTC, jaymarystella commented on src/main/java/gift/service/KakaoAuthService.java
> +            User newUser = new User(email, "default_password123");
이 값은 하드코딩 되어야하는 값일까요? 다른 사용자들이 타인의 이메일을 가지고 로그인을 할 수도있어보입니다.

2024-07-27 15:22 UTC, jaymarystella commented on src/main/java/gift/service/UserService.java
> +    private User findOrRegisterUser(String email) {
리턴값이 사용이 되지 않는것 같습니다.

2024-07-27 15:22 UTC, jaymarystella commented on src/main/java/gift/service/OrderService.java
> +    }
중간에 하나가 실패하면 어떻게 될까요?

2024-07-27 15:22 UTC, jaymarystella commented on src/main/java/gift/service/OrderService.java
> +    }
메서드의 길이를 줄여볼 수 있을까요? (+각 도메인들에게 책임을 부여할 수 있는 부분들이 있을까요?)

2024-07-27 15:22 UTC, jaymarystella commented on src/main/java/gift/service/UserService.java
> +    }
UserService가 분기를 책임져야할 역할이 맞을까요? 
(+다른 인증들이 추가가 된다면 UserService에서 모든 분기를 가져가야할지도 고민해보셔요.)

2024-07-27 15:22 UTC, jaymarystella commented on src/main/java/gift/service/OrderService.java
> +public class OrderService {
핵심 클래스인것으로 보이는데 테스트코드가 없네요 테스트를 추가해보시면 좋을것같습니다.

2024-07-27 15:22 UTC, jaymarystella commented on src/main/java/gift/service/OrderService.java
> +public class OrderService {
다른 클래스들도 테스트코드가 없는 부분들도 한번씩 확인해보셔요

2024-07-28 15:16 UTC, GamJaDo commented on src/main/java/gift/service/KakaoAuthService.java
> +            User newUser = new User(email, "default_password123");
하드코딩 하지 않고 알파벳, 숫자로 합쳐진 15자 랜덤 문자열로 password를 생성하도록 변경하였습니다.

2024-07-28 15:17 UTC, GamJaDo commented on src/main/java/gift/service/UserService.java
> +    private User findOrRegisterUser(String email) {
불필요한 코드를 삭제하였습니다.

2024-07-28 15:19 UTC, GamJaDo commented on src/main/java/gift/service/OrderService.java
> +    }
중간에 실패하지 않도록 RetryTemplate을 사용 하였습니다.

메서드의 길이를 줄였습니다.
Category(validateIdMatch), User(validatePassword), Wishlist(validateUserPermission) 이렇게 이전하였습니다.

2024-07-28 15:23 UTC, GamJaDo commented on src/main/java/gift/service/UserService.java
> +    }
- UserService에서 토큰들을 구분하는 분기를 삭제하였습니다. 대신 UserService라는 클래스명에 맡게 메서드들을 추가하였습니다.
- 분기는 TokenService에 추가하였습니다.
- 지금은 토큰이 2가지 이지만 다른 인증들이 추가되면 구분해야할 토큰들이 더 많아 짐에 따라 어떻게 구분을 할지 고민을 정말 많이 하였습니다. "TokenService"를 읽어보시면 아시겠지만 각 토큰 마다 getTokenSuffix을 호출하여 각 토큰이 무엇인지 구분하는 방법으로 하였습니다.

2024-07-28 15:23 UTC, GamJaDo commented on src/main/java/gift/service/OrderService.java
> +public class OrderService {
Service 클래스들의 테스트들을 추가하였습니다.

2024-07-29 13:29 UTC, jaymarystella commented on src/main/java/gift/service/OrderService.java
> +    }
트랜잭션에 대해서도 찾아보시면 좋을것같습니다

2024-07-29 13:37 UTC, jaymarystella approved these changes
리뷰 반영하느라 고생많으셨고 다음단계 진행해주세요

2024-07-29 13:37 UTC, merged