경북대 BE_김은선 5주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #344
Opened 2024-07-27 12:46 UTC by eunsoni

안녕하세요 멘토님,

리뷰요청 드립니다

slack으로 연락드린 대로 이번 주에 구현이 늦어져서.. 1단계 머지 전에 과제 제출을 위해 2단계를 먼저 pr올리게 되었어요

아직 카카오 api 추가가 필요해서 곧 업데이트 해놓겠습니다!

2단계 진행 사항
* 상품 페이지에 주문 버튼, 수량 선택 select 태그, 메세시 받을 모달창 추가
* 상품 구매 시 상품 전체 수량에서 주문 수량만큼 감소
* 상품 구매 시 위시리스트에 상품이 등록되어있었다면 위시리스트에서 삭제
* 상품 주문 버튼 클릭 시 주문메세지를 모달창으로 받아 컨트롤러로 전송
* 위시리스트 엔터티에서 oprionName 삭제

+ 상품 구매 기능을 구현하고 나니 위시리스트에 상품을 담기 위해서는 옵션 이름은 선택해야하지만 옵션 수량은 선택하지 않아도 정상 작동하는 상황이었습니다. 그래서 사용자가 위시리스트에 상품을 담기 위해 입력해야하는 정보의 종류를 헷갈릴 수 있다는 생각이 들었습니다. 그리고 위시리스트 페이지나 다른 기능들에서도 위시리스트에 담긴 상품의 옵션에 대한 정보는 사용되고 있지 않아서 옵션에 대한 내용은 위시리스트에서 삭제하였습니다.
(위시리스트 엔터티, 컨트롤러, 서비스, 클라이언트 수정 완료)

2024-07-27 13:21 UTC, gongdongho12 requested changes
영인님 안녕하세요

되도록이면 api response로 Map 객체를 최소화하면 좋을 것 같습니다
-> 추후 swagger를 사용하게 되면 객체의 속성에 따라 값이 추론되어지는데, map 객체는 실제로 어떤 값이 들어갈지 모르는 Object와 같으니까요!

[1단계 PR 리뷰](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-order/pull/339)에 드린 내용이 아직 반영 되기 전인데요
2단계 리뷰와 같이 확인해서 반영주시면 좋을 것 같습니다

2024-07-27 13:21 UTC, gongdongho12 commented on src/test/java/gift/KakaoControllerTest.java
> +}
카카오 로그인 테스트 👍🏼 
실제 로그인 이후에 DB에 계정이 반영되는 부분까지 엮어서 테스트 되면 좋을 것 같아요!

2024-07-27 13:21 UTC, gongdongho12 commented on src/main/java/gift/service/WishlistService.java
> +        wishlistRepository.save(new Wishlist(member, product));
이부분은 어떻게 처리하기 나름인데, wishlist가 장바구니 라고 한다면 실제 아이템까지 적용 되는게 좋지 않을까요?
사실 내가 찜한 상품이 옵션마다 품절여부가 다를 건데 지금처럼 옵션이 빠져버리면 내가 원하는 옵션의 재고를 정확하게 체크하기 어려울 것 같아서요

2024-07-28 08:18 UTC, eunsoni commented on src/main/java/gift/service/WishlistService.java
> +        wishlistRepository.save(new Wishlist(member, product));
위시리스트는 가볍게 '좋아요'정도로 관심상품을 담는 용도로 생각했습니다.
사용자 입장에서는 옵션 선택없이 위시리스트에 담는(주로 좋아요 버튼 또는 하트 버튼) 것이 익숙해서 경고문을 계속 띄우게 될 것 같습니다(1. 옵션을 선택하라, 2. 수량을 선택하라)
이후에 장바구니를 추가 구현하는 편이 나을 것 같은데 멘토님의 생각은 어떠신가요?

2024-07-28 08:23 UTC, gongdongho12 commented on src/main/java/gift/service/WishlistService.java
> +        wishlistRepository.save(new Wishlist(member, product));
@eunsoni 찜하기 기능만을 이야기하는 것이라면 옵션이 제외되는 부분 확인했습니다!
저희가 실제 카카오톡 쇼핑하기를 카피해서 작업하는 부분이기에 말씀주신 부분처럼 동일하게 가면 좋을 것 같아요
<img width="1394" alt="image" src="https://github.com/user-attachments/assets/f61f4e3c-0186-42e4-82ac-4765f850c0fe">

2024-07-29 12:47 UTC, eunsoni commented on src/test/java/gift/KakaoControllerTest.java
> +}
넵!! 수정해두었습니다

2024-07-29 13:17 UTC, eunsoni commented
1단계, 2단계 피드백 반영하고 리뷰 요청 드립니다😊

2024-07-29 13:46 UTC, gongdongho12 approved these changes
3단계 진행해주시면 좋을 것 같습니다!

2024-07-29 13:46 UTC, merged