전남대 BE_모아림 5주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #347
Opened 2024-07-27 14:38 UTC by ariimo

안녕하세요 멘토님!

이것저것 추가하다 보니 Order Service가 너무 무거워진 것 같다는 생각이 듭니다. 
sendKaKaoMessage()나 getUserInfoWithToken()을 KaKaoService로 이동하는 게 더 알맞을까요??

2024-07-28 11:51 UTC, dc-choi requested changes
안녕하세요 아림님!

점점 실력이 늘어가시는거 같습니다! 자세한 내용은 하단에 남겨두었습니다~!

> 이것저것 추가하다 보니 Order Service가 너무 무거워진 것 같다는 생각이 듭니다. sendKaKaoMessage()나 getUserInfoWithToken()을 KaKaoService로 이동하는 게 더 알맞을까요??

다른 서비스로 옮기는건 그만큼 트랜잭션 전파에 대해서 더 신경써야해서 오히려 지금 상황이 더 나아보입니다.

아마 Order라는 역할에 맞지 않아 이런 고민을 하신 것으로 보이네요. 이런 고민을 해결하기 위해서는 몇가지 고려해야하는 부분이 있다고 생각합니다.

1. 도메인 모델 패턴을 적용하면서 도메인 로직에 관련된 부분을 분리해봅니다.
2. 도메인 모델 패턴을 적용하게 된다면 메시지를 보내는 책임을 지닌 객체는 어디에 두어야 하는가?

이정도에 대한 고민이 필요해보이네요.

2024-07-28 11:51 UTC, dc-choi commented on src/main/java/gift/domain/Order.java
> +    private LocalDateTime orderDateTime;
이 부분에는 `@Column(nullable = false)`이 안 붙은 이유가 뭔가요?

2024-07-28 11:51 UTC, dc-choi commented on src/main/java/gift/domain/Order.java
> +    private String message;
이 부분도 마찬가지로 `@Column(nullable = false)`이 안 붙은 이유가 뭔가요?

2024-07-28 11:51 UTC, dc-choi commented on src/main/java/gift/controller/OrderController.java
> +        String token) {
token을 body로 받아오는 이유가 있으신가요?

2024-07-28 12:32 UTC, ariimo commented on src/main/java/gift/domain/Order.java
> +    private LocalDateTime orderDateTime;
orderDateTime같은 경우 Order을 생성할 때 자동으로 넣어주니 nullable이 필요하지 않다고 판단했습니다. DB상에서도 한번 더 방지하는 게 나을까요??

2024-07-28 12:38 UTC, ariimo commented on src/main/java/gift/domain/Order.java
> +    private String message;
message값은 필수 입력 사항이 아니어도 되겠다고 판단했습니다. 수정하겠습니다!

2024-07-28 12:50 UTC, ariimo commented on src/main/java/gift/controller/OrderController.java
> +        String token) {
앋! 수정해야겠다 생각 했었는데, 그대로 제출하게 되었던 부분입니다..ㅠㅠ 죄송합니다. 
@RequestHeader("Authorization")를 추가하여 수정하였습니다!

2024-07-29 03:07 UTC, dc-choi approved these changes
아림님! 고생하셨습니다!

바로 step3로 넘어가시면 될 거 같습니다!

2024-07-29 03:07 UTC, merged