충남대 BE 박상우 5주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #349
Opened 2024-07-27 16:16 UTC by pswaao88

미리 생성했습니다.

2024-07-28 03:34 UTC, Hyeon9mak requested changes
안녕하세요 상우님! 3단계 잘 진행해주셨어요.
간단한 질문 코멘트 몇 가지 남겼으니 확인해주세요~

2024-07-28 03:34 UTC, Hyeon9mak commented on src/main/java/gift/Controller/CategoryController.java
> +    )
상세하게 잘 기입해주셨네요 👍

2024-07-28 03:34 UTC, Hyeon9mak commented on src/main/java/gift/Controller/LoginController.java
> +    @Parameter(name = "code", description = "카카오 로그인을 통해 얻은 인가코드")
swagger 설명을 기입하면서 충분한 설명이 되엇으므로, `// 인가 코드 받아와 토큰 추출`  부분을 제거해도 충분하겠네요!

2024-07-28 03:34 UTC, Hyeon9mak commented on src/main/java/gift/Model/Member.java
> +    @Schema(description = "멤버의 accessToken", defaultValue = "해당되는 accessToken")
비즈니스 로직을 풀어내는 domain 영역까지 presentation 코드가 침투하는 것에 대해 어떻게 생각하시나요? 🥲

2024-07-28 03:34 UTC, Hyeon9mak commented on src/main/java/gift/Service/MessageService.java
> +            .toEntity(String.class);
발송 중 실패하면 어떤 식으로 에러가 처리되나요?

2024-07-28 03:34 UTC, Hyeon9mak commented on src/main/java/gift/Config/SwaggerConfig.java
> +}
👍 👍 여러가지 api 명세 프레임워크가 있을텐데, swagger 를 채택한 이유가 궁금해요!

2024-07-28 05:07 UTC, pswaao88 commented on src/main/java/gift/Controller/LoginController.java
> +    @Parameter(name = "code", description = "카카오 로그인을 통해 얻은 인가코드")
제거 했습니다!

2024-07-28 05:19 UTC, pswaao88 commented on src/main/java/gift/Config/SwaggerConfig.java
> +}
첫번째로는 api 프레임워크중에 swagger를 가장 많이 쓰는 것 같아서 채택을 하였습니다.
두번째로는 어노테이션을 이용해서 간편하게 작성할 수 있어서 사용했습니다.
세번째로는 작업한 내용을 쉽게 http://127.0.0.1:8080/swagger-ui.html 통해서 눈으로 볼 수 있어서 채택하였습니다!

2024-07-28 05:49 UTC, pswaao88 commented on src/main/java/gift/Service/MessageService.java
> +            .toEntity(String.class);
찾아본 결과 3가지의 예외가 발생하는 걸 알게되었습니다.
첫번째로는 클라이언트의 오류인 4xx코드가 발생하면 HttpClientErrorException를 던집니다.
두번째로는 서버 오류인 5xx코드가 발생하면 HttpServerErrorException를 던집니다.
마지막으로 네트워크 오류등으로 리소스에 접근할 수 없다면 ResourceAccessException를 던집니다.
이에 대해서 try-catch문으로 예외처리를 진행하면 될까요?

2024-07-28 05:57 UTC, pswaao88 commented on src/main/java/gift/Model/Member.java
> +    @Schema(description = "멤버의 accessToken", defaultValue = "해당되는 accessToken")
찾아본 결과 도메인 영역은 비지니스 로직과의 관련되어있고
프레젠테이션 코드는 @NOTBLANK, @Schema와 같이 사용자의 인터페이스와 관련이 되어있다는 것을 알게 되었습니다.
객체 지향적인 관점으로 보았을 때 두코드를 도메인영역과 도메인영역의 DTO를 만들어서 유지보수 및 역할을 구체화를 시키는 편이 좋다고 생각이 들었습니다!

2024-07-29 09:46 UTC, Hyeon9mak approved these changes
안녕하세요 상우님~ 5주차 3단계 고생 하셨어요 😄 
마지막 주차 미션에서 만나요~

2024-07-29 09:46 UTC, Hyeon9mak commented on src/main/java/gift/Model/Member.java
> +    @Schema(description = "멤버의 accessToken", defaultValue = "해당되는 accessToken")
일단 분리를 하는 것이 좋아보입니다!

DTO 는 data transfer object 로 데이터를 이동시키는 것에 집중하는 객체인데,
도메인 영역의 DTO 는 정확히 어떤 의미일까요?

2024-07-29 09:46 UTC, Hyeon9mak commented on src/main/java/gift/Service/MessageService.java
> +            .toEntity(String.class);
상우님께서는 어떻게 하는게 좋다고 생각이 드실까요?
오류 코드 그대로 사용자에게 노출되는 것이 좋을지, 조금이라도 가공이 된 메세지를 전달할지 고민해보시면 좋을거 같아요 😄

2024-07-29 09:46 UTC, Hyeon9mak commented on src/main/java/gift/Config/SwaggerConfig.java
> +}
근거가 있는 선택 좋습니다~ 다만

> api 프레임워크중에 swagger를 가장 많이 쓰는 것 같아서 채택

`같아서` 보다는 근거 자료, 레퍼런스 등을 찾아보면 좋겠네요.
가령 [spring rest docs 문서에서 swagger 를 가장 먼저 거론하고 있다](https://spring.io/projects/spring-restdocs#overview) 던지요~

2024-07-29 09:46 UTC, merged

2024-07-29 15:19 UTC, pswaao88 commented on src/main/java/gift/Model/Member.java
> +    @Schema(description = "멤버의 accessToken", defaultValue = "해당되는 accessToken")
각 엔티티에 해당하는 필드들을 옮기기 위해서 해당하는 DTO를 말하는 것이었습니다!
해당 엔티티들에 해당하는 필드를 가진 DTO를 만들어서 적용을 해보도록 하겠습니다!

2024-07-29 15:21 UTC, pswaao88 commented on src/main/java/gift/Service/MessageService.java
> +            .toEntity(String.class);
저 같은 경우에는 아직 서비스를 구현하고 배포하는 것을 연습하는 단계라고 생각이 되어서 오류 코드를 그대로 사용자에게 노출을 시키는 것이 좋다고 생각합니다!

2024-07-29 15:25 UTC, pswaao88 commented on src/main/java/gift/Config/SwaggerConfig.java
> +}
단순하게 많은 자료들이 swagger를 쓰고 있다고 인지만 했지 근거 자료나 레퍼런스 등을 찾아볼 생각을 하지 못했습니다. 어떤 것을 쓰려고 할 때 내가 이걸 왜 쓰려고 했는지에 대한 근거와 많은 자료들을 통해서 정리를 하는 방법도 좋다고 생각이 들었습니다 감사합니다!