충남대 BE_이택 5주차 과제 step3
kakao-tech-campus-2nd-step2/spring-gift-order pull request #351
Opened 2024-07-27 17:18 UTC by LeeTaek2T

2024-07-28 06:17 UTC, ksy90101 requested changes
2단계 끝나면 리뷰할게요.

2024-07-29 05:28 UTC, ksy90101 requested changes
허들로 이야기 한거 수정해주세요.

2024-07-29 05:28 UTC, ksy90101 commented on src/main/java/gift/DTO/Orders.java
> +  private List<Option> options;
허들로 이야기 했듯이 ManyToMany가 더 어울리는거 같아요.

2024-07-31 07:20 UTC, LeeTaek2T commented
현재 api명세서에 따라 구현을 하였습니다.
허들로 이야기 했던 ManyToMany, entity승격에 대해서는 추후 꼭 구현해보겠습니다!

2024-07-31 08:05 UTC, ksy90101 approved these changes
고생하셨어요~
6주차에서 뵐게요!

2024-07-31 08:05 UTC, merged