경북대 BE_김동현 5주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #353
Opened 2024-07-28 02:17 UTC by donghyuun

PR 요청드립니다!

2024-07-28 11:54 UTC, MangKyu requested changes
안녕하세요! 3단계 과제도 잘 구현해주셨는데요, 조금 고치면 좋을 것 같은 부분들이 보여서요! 남겨드린 코멘트 한번 확인 부탁드리겠습니다ㅎㅎ
추가적으로 질문 주신 부분들에 대해서도 답변드리겠습니다!

### ApiResponses의 활용
저는 실무에서 tag와  operation 정도만 활용하며 직관적으로 파악 가능한 부분은 생략합니다! 그렇지 않으면 swagger 애노테이션에 의해 불필요하게 controller가 뚱뚱해져서 가독성이 떨어지는 것 같아요 ㅎㅎ 
컨트롤러에 붙이는 애노테이션들이 복잡해지는 경우에는 컨트롤러와 swagger를 위한 interface를 분리하여 작성하시는 분들도 계시더라구요! 저는 이렇게까지는 안하는데 상세하게 작성이 필요하다면 나쁘지는 않은 패턴이라고 생각합니다!


### aop 활용
async를 활용하는 부분은 좋은 것 같은데요! 현재 order 메서드에서 2가지 private 메서드를 호출해주시고 계신데요, 각각 모두 트랜잭션 그리고 비동기 처리가 되지 않을꺼에요 해당 이유는 위에 적어드린 대로 AOP 내부 호출 때문입니다! 당장 이해가 어려운 부분일 수 있지만 꼭 알아야 하는 부분이라서, 당장은 키워드만 기억해주셔도 되지 않을까 싶네요ㅎㅎ

2024-07-28 11:54 UTC, MangKyu commented on build.gradle
> +    implementation 'org.springframework.retry:spring-retry'
swagger 및 retry 활용 👍

2024-07-28 11:54 UTC, MangKyu commented on src/main/java/gift/domain/cartItem/CartItemRestController.java
> +@Tag(name = "CartItem", description = "CartItem API")
해당 문서의 주요 고객은 FE이다보니 저는 한글로 작성해요ㅎㅎ (취향차이라 반영 안해주셔도 됩니다: 🙇 )

2024-07-28 11:54 UTC, MangKyu commented on src/main/java/gift/domain/cartItem/CartItemRestController.java
> +        @Parameter(description = "상품 ID") @PathVariable("productId") Long productId,
swagger의 단점 중 하나가 컨트롤러가 복잡해진다는 부분인데요~
보고 직관적으로 유추 가능한 부분들은 저는 생략합니당ㅎㅎ

2024-07-28 11:54 UTC, MangKyu commented on src/main/java/gift/domain/cartItem/CartItemRestController.java
> +    @Operation(summary = "장바구니 상품 수량 변경")
swagger를 활용한 문서화 👍
swagger 외에 [rest-docs](https://spring.io/projects/spring-restdocs)라는 라이브러리도 있는데요~ 이를 활용하면 테스트 코드 기반의 문서를 제공해줍니다ㅎㅎ 추후에 공부해보시면 좋을 것 같네요!

2024-07-28 11:54 UTC, MangKyu commented on src/main/java/gift/domain/option/OptionService.java
> +                productRepository.delete(option.getProduct()); // Cascade 로 옵션도 삭제됨
꼼꼼한 리뷰 반영 💯

2024-07-28 11:54 UTC, MangKyu commented on src/main/java/gift/domain/order/OrderService.java
> +    public void orderProduct(OrderRequestDTO orderRequestDTO, UserInfo userInfo) {
order에서 orderProduct를 호출하고 있는데요~ 현재 코드는 AOP 내부 호출 케이스(private 메서드 호출)라 트랜잭션이 먹히지 않겠군요! 요 부분 현재 공부하기에는 난이도가 있는 분이라 `AOP 내부 호출` 키워드만 기억해두시고 추후에 공부해보시면 좋을 것 같네요:)

2024-07-28 11:54 UTC, MangKyu commented on src/main/java/gift/domain/order/TemplateObject.java
> +        String web_url,
자바 컨벤션에 맞게 변수명 작성하는 것이 좋을 것 같네요! 그러면 카카오 스펙과 맞지 않아 에러가 발생할텐데, 추가적인 해결이 필요할꺼에요!
```suggestion
        String webUrl,
        String mobileWebUrl
```

2024-07-28 11:54 UTC, MangKyu commented on src/main/java/gift/global/config/RestTemplateConfig.java
> +            .setConnectTimeout(Duration.ofSeconds(5)) // 연결
꼼꼼하게 반영해주셨네요 👍

2024-07-28 11:54 UTC, MangKyu commented on src/main/java/gift/global/config/RestTemplateConfig.java
> +            retryTemplate.setRetryPolicy(new SimpleRetryPolicy(3)); // 최대 3번 재시도
400은 클라이언트 에러인데요!
A 서버가 B 서버를 잘못된 스펙으로 요청하여 400 애러가 발생했는데도, 불필요하게 재호출 될 수도 있겠네요! 그래도 시도하신 부분은 좋은 것 같습니다ㅎㅎ

2024-07-28 11:54 UTC, MangKyu commented on src/main/java/gift/global/config/RestTemplateConfig.java
> +                throw new RestTemplateException();
이렇게 하면 예외 메시지가 끊길 것 같은데요, `RestTemplateException`에 부모 메시지도 얹어주면 좋을 것 같아요! RestTemplateException 클래스도 변경이 필요하겠군요!
```suggestion
                throw new RestTemplateException(throwable);
```

2024-07-28 11:54 UTC, MangKyu commented on src/main/java/gift/global/config/SwaggerConfig.java
> +public class SwaggerConfig {
swagger를 활용한 문서화 👍
swagger 외에 [rest-docs](https://spring.io/projects/spring-restdocs)라는 라이브러리도 있는데요~ 이를 활용하면 테스트 코드 기반의 문서를 제공해줍니다ㅎㅎ 추후에 공부해보시면 좋을 것 같네요!

2024-07-28 11:54 UTC, MangKyu commented on src/main/java/gift/global/handler/GlobalExceptionHandler.java
> +    @ExceptionHandler(RestTemplateException.class)
꼼꼼한 예외처리까지 좋습니다! 그런데 해당 예외가 4XX 인지 5XX인지에 따라 적절하게 핸들링 되고 있는지도 고민해보면 좋을 것 같네요ㅎㅎ

2024-07-29 05:14 UTC, donghyuun commented on src/main/java/gift/domain/cartItem/CartItemRestController.java
> +@Tag(name = "CartItem", description = "CartItem API")
한글이 FE 와 소통에 더 좋을 것 같습니다. 의견 감사합니다ㅎㅎ

2024-07-29 05:15 UTC, donghyuun commented on src/main/java/gift/domain/cartItem/CartItemRestController.java
> +        @Parameter(description = "상품 ID") @PathVariable("productId") Long productId,
의견 공유 감사합니다!!

2024-07-29 05:15 UTC, donghyuun commented on src/main/java/gift/domain/cartItem/CartItemRestController.java
> +    @Operation(summary = "장바구니 상품 수량 변경")
현재 진행하는 다른 프로젝트가 swagger 를 사용할 예정이라 공부할 겸 사용해보았습니다.
rest-docs 도 추후 공부해보겠습니다!

2024-07-29 05:37 UTC, donghyuun commented on src/main/java/gift/domain/order/TemplateObject.java
> +        String web_url,
objectMapper에서 json 문자열로 변환 시 따로 카멜 케이스를 스네이크 케이스로 바꿔주지 않아서 변수명을 직접 스네이크 케이스로 했었습니다.
objectMapper 가 카멜 케이스를 스네이크 케이스로 바꿔주도록 하는 속성값을 사용하는 것으로 변경했습니다!

2024-07-29 06:36 UTC, donghyuun commented on src/main/java/gift/global/handler/GlobalExceptionHandler.java
> +    @ExceptionHandler(RestTemplateException.class)
4xx, 5xx 에러를 분리하여 핸들링 하도록 수정했습니다!

2024-07-29 06:37 UTC, donghyuun commented on src/main/java/gift/global/config/SwaggerConfig.java
> +public class SwaggerConfig {
공부해보겠습니다 ㅎㅎ 말씀 감사합니다!

2024-07-29 06:38 UTC, donghyuun commented on src/main/java/gift/global/config/RestTemplateConfig.java
> +                throw new RestTemplateException();
부모 메시지도 얹도록 수정하였습니다!
![image](https://github.com/user-attachments/assets/6da7a827-b272-44f4-b0ca-e71a6e103af1)
![image](https://github.com/user-attachments/assets/df801140-40b7-4467-a654-1dff7c08bde1)

2024-07-29 06:40 UTC, donghyuun commented on src/main/java/gift/global/config/RestTemplateConfig.java
> +            retryTemplate.setRetryPolicy(new SimpleRetryPolicy(3)); // 최대 3번 재시도
4xx 에러에 대해서는 재시도를 하지 않도록 수정했습니다.
코드를 작성하면서 연관 동작들도 함께 생각해야겠습니다..

2024-07-29 08:20 UTC, MangKyu approved these changes
5주차 과제도 고생많으셨습니다! 다음 스텝 진행을 위해 머지하도록 하겠습니다ㅎㅎ 🙇

2024-07-29 08:20 UTC, merged