전남대 BE_서영우 5주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #378
Opened 2024-07-28 11:25 UTC by westzeroright

2024-07-29 15:48 UTC, pkeugine requested changes
안녕하세요 영우님,
간단한 리뷰 남겨봤으니 한 번 확인해주시면 감사하겠습니다.
step 2 를 머지하니 conflict 가 발생해서 이 부분 해결해주세요!

2024-07-29 15:48 UTC, pkeugine commented on src/main/java/gift/product/ProductController.java
> +
여기 불필요한 공백이 포함되었네요!
그리고 import 문에서 wildcard 는 저는 지양하는 편인데요, wildcard 를 사용했을 때의 장단점을 한 번 생각해봐도 괜찮을 것 같아요.
(만약 이전 리뷰에 이와 비슷한 내용이 있었다면 복습 느낌으로 해보죠!)

2024-07-29 15:48 UTC, pkeugine commented on src/main/java/gift/config/SwaggerConfig.java
> +public class SwaggerConfig {
swagger 를 사용하게 된 계기가 궁금해요.
사용해보니 어떤 점이 좋았나요?

2024-07-30 13:09 UTC, westzeroright commented on src/main/java/gift/config/SwaggerConfig.java
> +public class SwaggerConfig {
운영코드에 영향을 미치지 않은 spring rest docs도 매력적으로 다가왔지만
저는 이번에 처음 사용해봐서 UI로 화면을 볼 수 있고 적용하기 쉬운 swagger를 사용해 보았습니다

2024-07-30 13:20 UTC, westzeroright commented on src/main/java/gift/product/ProductController.java
> +
공백 진짜 잘 찾으시네요.. 포맷을 한 번 알아봐야겠어요..! command+option+L하면 이상하더라구요..

wildcard를 사용했을 때 장점은 여러 개의 import문을 생략할 수 있다는 점이 있을 것 같습니다!
다만 단점으로 어떤 것을 import하였는지 구체적으로 알 수 없고 사용하지 않은 라이브러리도 불러올 수 있을 것 같습니다.

2024-07-30 13:55 UTC, pkeugine approved these changes
5주차도 고생하셨어요 영우님,
마지막 미션도 시작하셨는데 조금만 더 힘내보아요!
저번주 미션은 이만 머지할게요 :)

2024-07-30 13:55 UTC, merged