경북대 BE_정수현 5주차 과제 (0단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #38
Opened 2024-07-22 05:50 UTC by suhyeon7497

refactoring 할 부분 있으면 알려주시면 감사하겠습니다!

2024-07-22 14:53 UTC, sang5c requested changes
4주차 리뷰요청을 눌러주세요 :)  
4주차가 완료되면 5주차 리뷰요청을 다시 눌러주세요~

2024-07-23 16:07 UTC, suhyeon7497 commented
product.getOptions를 만들어 데이터 중심 개발을 해결하였습니다!

2024-07-24 05:50 UTC, suhyeon7497 commented
양방향 편의 메소드를 통해 validate가 자동으로 이루어지게 만들었습니다!

2024-07-24 16:34 UTC, sang5c approved these changes
파이팅입니다~!

2024-07-24 16:34 UTC, sang5c commented on src/main/java/gift/option/model/Option.java
> +        Option.Validator.validateDuplicated(product.getOptions());
option에서 product.getOptions()를 제어하면 순환참조 구조가 됩니다.  
추가로, getter를 사용하는 구조에 머물고 있습니다. options를 가진 곳은 product인데 값을 꺼내서 밖에서 비교하고 제어하고 있네요.  
5주차 과제에 집중하시되, 고민해보시고 어려우면 질문해주세요~

2024-07-24 16:35 UTC, merged

2024-07-25 12:41 UTC, suhyeon7497 commented on src/main/java/gift/option/model/Option.java
> +        Option.Validator.validateDuplicated(product.getOptions());
Product안에서 validate를 하도록 변경하였습니다!