전남대 BE_박민규 5주차 제출 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #394
Opened 2024-07-28 14:12 UTC by ps9319

일단 오늘까지 제출이라 step3도 제출합니다...
카카오 api 사용이 너무 어려워서 step1 , step2, step3를 한번에 제출한 것 같아 죄송합니다.

swagger도 처음 써보았는데 직접 작성하는 것보다 훨씬 편리했습니다. 그런데 RestController가 아니라 Controller 어노테이션이 달린 컨트롤러는 swagger를 적용할 수 없는 것이 아쉬웠습니다.

2024-07-29 06:14 UTC, dc-choi requested changes
안녕하세요 민규님.

> swagger도 처음 써보았는데 직접 작성하는 것보다 훨씬 편리했습니다. 그런데 RestController가 아니라 Controller 어노테이션이 달린 컨트롤러는 swagger를 적용할 수 없는 것이 아쉬웠습니다.

`@ResponseBody`가 없어서 명세가 어려워 보입니다. `@Controller`에서도 `@ResponseBody`로 JSON을 반환해준다는 명시를 해준다면 가능해보이기도 합니다.

OAuth2를 사용하는 로직의 경우 따로 `@SecuritySchemes`를 사용해서 명세를 진행하기도 합니다.

2024-07-29 06:15 UTC, dc-choi commented
아 그리고 실패 케이스에 대한 명세도 부탁드려요! 그리고 충돌이 발생하네요... ㅎㅎ 확인 부탁드립니다!

2024-07-29 09:59 UTC, ps9319 commented
> `@ResponseBody`가 없어서 명세가 어려워 보입니다. `@Controller`에서도 `@ResponseBody`로 JSON을 반환해준다는 명시를 해준다면 가능해보이기도 합니다.

아하!!!! 그렇게 하면 되는군요!! 바로 적용했습니다.
저 그런데 LoginUser 어노테이션이 있어서 이게 메서드 매개변수로 잡히는지 requestBody에 User가 들어가서 @Parameter(hidden = true)를 추가해줬는데, 모든 LoginUser 어노테이션에 붙여야 하니깐 불편했습니다. 혹시 어떻게 다르게 전역적으로 관리해줄 수 있는 방법이 있나요?
 
> OAuth2를 사용하는 로직의 경우 따로 `@SecuritySchemes`를 사용해서 명세를 진행하기도 합니다.

넵!! 적용해보았습니다. 감사합니다.

2024-07-29 11:46 UTC, dc-choi requested changes
안녕하세요 민규님.

> 저 그런데 LoginUser 어노테이션이 있어서 이게 메서드 매개변수로 잡히는지 requestBody에 User가 들어가서 @parameter(hidden = true)를 추가해줬는데, 모든 LoginUser 어노테이션에 붙여야 하니깐 불편했습니다. 혹시 어떻게 다르게 전역적으로 관리해줄 수 있는 방법이 있나요?

`@parameter(hidden = true)`를 `@LoginUser`에 적용해보는건 어떻게 생각하시나요? 그렇게 하면 전역적으로 관리가 될 것으로 보입니다.

2024-07-29 15:58 UTC, ps9319 commented
> `@parameter(hidden = true)`를 `@LoginUser`에 적용해보는건 어떻게 생각하시나요? 그렇게 하면 전역적으로 관리가 될 것으로 보입니다.

아아아!!!! 그런 좋은 방법이 있군요!!!
커스텀 어노테이션이라 가능한 거였네요!!
감사합니다!! 수정했습니다.

2024-07-30 00:21 UTC, dc-choi approved these changes
너무 훌륭하게 잘 해주셨습니다!

이번주도 파이팅입니다! 수고하셨습니다!

2024-07-30 00:21 UTC, merged