전남대_BE 박진화 (step3)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #399
Opened 2024-07-28 15:33 UTC by Jinhwa-Park

API 문서 작성했습니다.

2024-07-30 15:33 UTC, pkeugine requested changes
안녕하세요 진화님,
아직 api 문서에 모든 내용이 다 포함되어 있지 않아서
request changes 남겨요.
문서 추가하면서 conflict 도 해결해주시면 될 것 같아요.
조금만 더 파이팅입니다.

2024-07-30 15:33 UTC, pkeugine commented on README.md
> +# API 사용 가이드
만들어주신 api 에 대한 내용이 다 추가되었을까요?
선물하기와 같은 내용이 아직은 문서에 없는 것 같아서요.
다음 미션도 시작했고, 정신 없겠지만, 만드신 api 잘 확인해주시고 누락된 부분 잘 채워넣어주시면 감사하겠습니다.

2024-07-30 17:31 UTC, Jinhwa-Park commented
README로 작성했었다가 오늘 api 통일하면서 허점이 좀 많아보였습니다. 그래서 swagger 추가했습니다!

2024-07-31 11:31 UTC, pkeugine approved these changes
해당 미션은 이만 머지하도록 하겠습니다.
마지막 주까지 파이팅입니다!

2024-07-31 11:31 UTC, merged