강원대 BE_박지희 5주차 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #412
Opened 2024-07-29 03:27 UTC by peacefullyquietly

2024-07-29 13:59 UTC, jaymarystella requested changes
안녕하세요 몇가지 피드백 남겼는데 확인해주시고 테스트코드도 누락된부분들 전체적으로 찾아서 확인부탁드립니다

2024-07-29 13:59 UTC, jaymarystella commented on src/main/java/gift/controller/OrderController.java
> +    private JwtUtil jwtUtil;
주입을 받아야할 클래스가 맞을까요? 정적인 역할만을 담당하는 클래스처럼 보입니다

2024-07-29 13:59 UTC, jaymarystella commented on src/main/java/gift/service/JwtUtil.java
> +    public String generateToken(String email, Long userId, String kakaoToken) {
테스트코드가 없는데 추가부탁드립니다

2024-07-29 13:59 UTC, jaymarystella commented on src/main/java/gift/service/KakaoUserService.java
> +    }
메서드 길이를 줄일 수 있는 방법을 고민해주세요

2024-07-29 13:59 UTC, jaymarystella commented on src/main/java/gift/service/MemberService.java
> +    public MemberEntity registerOrLoginKakaoUser(String accessToken) {
> 현재 카카오로 로그인 시, 해당 정보를 기반으로 새로 회원 가입을 진행하고 있습니다. 그러나 이미 이메일과 패스워드 방식으로 가입된 유저가 있는 경우, 중복 회원 가입이 발생할 수 있습니다. 이런 경우 중복 회원 가입을 방지하고 기존 계정을 활용하려면 어떻게 해야 하는지, 또는 현재 사용하고 있는 방법을 그대로 사용해도 되는지 궁금합니다.

"기능 요구 사항에 기재되지 않은 내용은 스스로 판단하여 구현한다." 라는 요구사항이 있습니다. 어떻게 판단하실지 생각해보시고 기준을 남겨주세요

2024-07-29 13:59 UTC, jaymarystella commented on src/main/java/gift/service/OrderService.java
> +        }
도메인 로직으로 이관할 수 있을까요?

2024-07-30 05:53 UTC, peacefullyquietly commented on src/main/java/gift/service/MemberService.java
> +    public MemberEntity registerOrLoginKakaoUser(String accessToken) {
기존의 이메일 및 비밀번호 회원 가입 로직 외에 "카카오로 시작하기" 기능과 유사하게  카카오 계정으로 로그인 시, 자동 회원 가입을 구현했습니다. 구현하고자 한대로 적절하게 구현이 되었는지, 그리고 동일한 유저가 두 개의 계정을 가지는 상황이 올바른지 궁금합니다.

2024-07-30 05:58 UTC, peacefullyquietly commented on src/main/java/gift/controller/OrderController.java
> +    private JwtUtil jwtUtil;
의존성을 주입하지 않을 시 객체가 null 상태로 남아 메서드 호출 시 NPE가 발생하게 되어 주입하였습니다

2024-07-31 10:37 UTC, jaymarystella commented on src/main/java/gift/controller/OrderController.java
> +    private JwtUtil jwtUtil;
전부 정적인 메서드로 으로 만들어주셔도 된다면 그렇게 해주시는것도 방법입니다

2024-07-31 10:40 UTC, jaymarystella commented on src/main/java/gift/service/MemberService.java
> +    public MemberEntity registerOrLoginKakaoUser(String accessToken) {
구현하기 나름이겠지만 여러 로그인을 지원하는곳에서 따로 관리되는경우도 존재했던거같아요. 개인적으로 하나로 관리되는것이 더 나을거같긴한데요 로그인수단은 여러개지만 동일계정으로 활용할수있게요

2024-07-31 10:40 UTC, jaymarystella approved these changes
2단계 고생많으셨습니다. 다음단계에서 뵐게요

2024-07-31 10:41 UTC, merged