경북대 BE_김민주 5주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #425
Opened 2024-07-29 14:33 UTC by minju26

- swagger 을 이용해서 api 문서화 해보았습니다!
- 이전 단계 피드백 반영중ㅇ..

2024-07-30 15:20 UTC, gongdongho12 requested changes
5주차 과제 마지막까지 고생하셨습니다

> RestClient와 관련하여,
메서드에서 매번 호출하는 것은 수정했습니다!
defaultHeader 등 커스텀 하는 방법을 알려 주셨는데.. 검색과 공식문서를 보아도 아직 감이 잘 안잡힙니다🥹
Authorization 헤더를 default로 설정하는 경우, 현재 accessToken을 매개변수로 받아오고 있는데
이런 경우엔 아래와 같이 처리를 해야하는지 궁금합니다.
```
// 생성
private RestClient clientWithAuthHeader(String accessToken) {
    return RestClient.builder().defaultHeader("Authorization", "Bearer " + accessToken).build();
}

//사용
RestClient client = clientWithAuthHeader(accessToken);
```
-> 이 방식이 맞습니다

2024-07-30 15:20 UTC, gongdongho12 commented on src/main/java/gift/config/SwaggerConfig.java
> +        );
JWT 반영 👍🏼

2024-07-30 15:20 UTC, gongdongho12 commented on src/main/java/gift/domain/Member.java
> +        this.kakaoRefreshToken = kakaoRefreshToken;
이 값이 없더라도 사용이 가능해야 하는게 좋지 않을까요?
생성자를 `Member(String email, String password, LoginType loginType)`와 `Member(String email, String password, LoginType loginType, String kakaoAccessToken, String kakaoRefreshToken)` 두가지로 가보면 어떨까요? 없으면 null로 처리하구요!

2024-07-30 15:20 UTC, gongdongho12 commented on src/main/java/gift/service/KaKaoService.java
> +        ResponseEntity<String> response = client.post()
client에 토큰을 넣어서 결국 세팅을 해야하는데 저런 부분을 하나로 세팅할 수 있으니까요!

2024-07-30 15:20 UTC, gongdongho12 commented on src/main/java/gift/service/KaKaoService.java
> +public class KaKaoService {
이 로직에 대한테스트가 없는 것 같아요!

2024-07-30 15:27 UTC, minju26 commented on src/main/java/gift/domain/Member.java
> +        this.kakaoRefreshToken = kakaoRefreshToken;
현재는 같은 생성자를 사용하면서 `new Member(email, password, EMAIL, null, null)` 이렇게 사용하고 있는데,
아무래도 null을 이런식으로 넣어주는 것 보다 생성자를 구분해서 사용하는게 더 깔끔할 것 같네요..! 생성자를 따로 두는 것으로 변경해보도록 하겠습니다!

2024-07-30 15:39 UTC, gongdongho12 commented on src/main/java/gift/domain/Member.java
> +        this.kakaoRefreshToken = kakaoRefreshToken;
생성자 안에서 생성자를 호출할 수 있는데 그부분도 같이 적용되면 좋을 것 같네여

2024-07-30 15:43 UTC, minju26 commented on src/main/java/gift/domain/Member.java
> +        this.kakaoRefreshToken = kakaoRefreshToken;
아하! 이렇게 수정하니까 더 보기가 깔끔하네요

2024-07-30 16:37 UTC, minju26 commented on src/main/java/gift/service/KaKaoService.java
> +public class KaKaoService {
음.. 외부 api 사용하는 부분 테스트를 어떤 식으로 해야 할지 고민이 많았습니다 🥲
이것저것 해보다가 알 수 없는 오류가 많아서 일단 기능 개발에 집중했는데, 다시 한번 해보도록 하겠습니다..!

2024-07-31 12:32 UTC, minju26 commented
@gongdongho12 
`KakaoService` 테스트를 우여곡절 끝에 .. 작성하긴 했는데 이렇게 하는게 맞는지 모르겠네요🥹
멘토님 **피드백**과 **외부 api + RestClient 관련한 테스트 레퍼런스** 아시는 것이 있다면 부탁드립니다!!

2024-07-31 12:40 UTC, gongdongho12 commented on src/main/java/gift/service/KaKaoService.java
> +public class KaKaoService {
@minju26 목 서버 구성해서 테스트인데 👍🏼 잘 구현해주셨네요
참고할만한 문서는 https://velog.io/@jmjmjmz732002/%EC%99%B8%EB%B6%80-API-%EC%84%9C%EB%B2%84%EB%8A%94-mocking%ED%95%98%EC%97%AC-%ED%85%8C%EC%8A%A4%ED%8A%B8%ED%95%B4%EC%95%BC-%ED%95%9C%EB%8B%A4 한번 보시면 좋을 것 같습니다!

2024-07-31 12:41 UTC, minju26 commented on src/main/java/gift/service/KaKaoService.java
> +public class KaKaoService {
넵 갑사합니다!

2024-07-31 12:42 UTC, gongdongho12 approved these changes
5주차 과제 테스트까지 잘 마무리해주셨네요!
이후에는 Test용 프로파일이나 Production 프로파일 등까지 구분되서 정리되면 좋을 것 같아요

고생하셨습니다 💯

2024-07-31 12:42 UTC, gongdongho12 commented on src/test/java/gift/service/KaKaoServiceTest.java
> +    }
이런 json 같은 경우는 문자열로 정리하면 사실 오타를 내기 쉬워서 jsonObject 객체를 사용하는 방법도 있습니다!

2024-07-31 12:43 UTC, merged

2024-07-31 12:44 UTC, minju26 commented on src/test/java/gift/service/KaKaoServiceTest.java
> +    }
아하 안그래도 신경쓰였는데 그런 방법이 있군요! 다음 pr에서 수정해보도록 하겠습니다