경북대 BE_김은선 5주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #435
Opened 2024-07-30 12:29 UTC by eunsoni

안녕하세요 멘토님,

리뷰요청드립니다:)

2단계에서 빼먹은 피드백 '컨트롤러 반환 객체 map 최소화'를 반영해서 response dto와 pagination info 클래스를 추가하였습니다

3단계 진행 사항
1. swagger ui에서 api문서를 자동으로 생성하기 위해서 컨트롤러를 수정하였습니다.
2. 애플리케이션 실행 후 'http://localhost:8000/swagger-ui/index.html' 이 링크에 접속하여 api 명세를 swagger ui로 확인할 수 있었습니다.
3. 또한 swagger editor를 사용해 JSON을 YAML 파일로 변환해서 api 명세를 문서로도 확인할 수 있었습니다.
4. 위시리스트 삭제 api에 오류 수정하였습니다.(정상 작동 확인함)

2024-07-30 15:35 UTC, gongdongho12 requested changes
5주차 과제 마무리까지 고생하셨습니다

리뷰 드린 내용 한번 확인 부탁드려요!

2024-07-30 15:35 UTC, gongdongho12 commented on src/main/java/gift/config/OpenAPIConfig.java
> +    }
이렇게만 세팅하면 시큐리티 테스트는 불가능할 거에요
SecurityContexts를 추가하는 방법에 대해서 한번 찾아보시면 좋을 것 같습니다

2024-07-30 15:35 UTC, gongdongho12 commented on src/main/java/gift/controller/HomeController.java
> +        paginationInfo.setHasPrevious(productPage.hasPrevious());
controller인데 이런 처리 로직까지 넣어두기 보다는 내부에서 손쉽게 처리할 수 있도록 구성하는게 좋지 않을까요?
ex) new PaginationInfo(productPage)
이런 식으로요!

아래도 동일합니다!

2024-07-30 15:35 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Void> orderItem(@RequestParam("email") String email, @RequestParam("optionId") Long optionId, @RequestParam("quantity") int quantity, @PathVariable Long productId, @RequestP
메시지를 API로 보낼게 아니라, 주문하는API가 들어오면 그 상품에 맞게 메시지를 생성하는 방향이 API를 설계하는 방향에서 맞지 않을까요?

2024-07-30 15:35 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Void> orderItem(@RequestParam("email") String email, @RequestParam("optionId") Long optionId, @RequestParam("quantity") int quantity, @PathVariable Long productId, @RequestP
그리고 다른 부분은 전부 페이지 처리인데 이 부분만 API 처리라
뷰용 컨트롤러와 API용 컨트롤러를 구분할 필요가 있을 것 같습니다!

2024-07-30 15:35 UTC, gongdongho12 commented on src/main/java/gift/controller/WishlistController.java
>          return ResponseEntity.ok().build();
삭제는 noContent이고 추가는 ok로 제공하고 있는데요
결국 삭제든 추가든 둘다 새로고침 하는 방식이 아닐까요?
각각 구분에 대한 근거가 궁금합니다

2024-07-30 15:35 UTC, gongdongho12 commented on src/main/resources/templates/wishlist.html
> +                'Authorization': `Bearer ${token}`
헤더를 이렇게 넣는 케이스가 많을 것 같은데요, 결국 이 로직도 중복해서 사용할 건데 별도로 메서드로 뺴두는 방향이 좋지 않을까요?

2024-07-30 15:35 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
>  @Controller
간단하게 @Controller는 템플릿 엔진 @RestController는 실제 호출용 API 정도로 분간해보시면 좋을 것 같습니다

2024-07-30 20:19 UTC, eunsoni commented on src/main/java/gift/config/OpenAPIConfig.java
> +    }
혹시 시큐리티가 spring security 말씀하시는 걸까요?
저번에 강사님께서 우리 미션은 spring security 없이도 간단하게 구현가능하다고 하시면서 spring security 없이 구현하는 것을 추천해주셨습니다

2024-07-31 01:15 UTC, gongdongho12 commented on src/main/java/gift/config/OpenAPIConfig.java
> +    }
그게 아니라서 한번 찾아보시면 안될까요?

2024-07-31 06:10 UTC, eunsoni commented on src/main/java/gift/config/OpenAPIConfig.java
> +    }
아하 그렇군요 수정해두겠습니다!

2024-07-31 06:10 UTC, eunsoni commented on src/main/java/gift/controller/HomeController.java
> +        paginationInfo.setHasPrevious(productPage.hasPrevious());
넵 수정했습니다!

2024-07-31 06:24 UTC, eunsoni commented on src/main/java/gift/controller/WishlistController.java
>          return ResponseEntity.ok().build();
삭제에도 변경해놓았습니다!
삭제는 위시리스트 페이지에서 요청하고 새로고침되기 때문에 삭제 여부를 확인할 수 있어서 noContent로 작성을 했습니다. 그런데 생각해보니까 ok로 api 응답을 확인하는 편이 좋을 것 같습니다!

2024-07-31 07:32 UTC, eunsoni commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Void> orderItem(@RequestParam("email") String email, @RequestParam("optionId") Long optionId, @RequestParam("quantity") int quantity, @PathVariable Long productId, @RequestP
음 제가 이해가 잘 안된 것 같아욥
메세지를 상품에 맞게(예를들어 상품이름을 포함) 만든 후에도 API로 보내지 않고 다른 방법을 사용하는 것을 말씀하시는 걸까요?
만약 그렇다면 이 메세지를 컨트롤러에서 받아서 카카오톡 메세지를 보내는kakaoService.sendKakaoMessage(accessToken, message);
에 메세지를 전달할 수 없을 것 같아서 고민입니다

2024-07-31 13:07 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Void> orderItem(@RequestParam("email") String email, @RequestParam("optionId") Long optionId, @RequestParam("quantity") int quantity, @PathVariable Long productId, @RequestP
@Controller인데 POST API를 처리하고 있자나요
API는 @RestController로 처리하는게 맞는데 그게 아니여서요!
ResponseEntity.ok() 이니까요

2024-07-31 13:07 UTC, gongdongho12 commented on src/main/java/gift/controller/WishlistController.java
>          return ResponseEntity.ok().build();
넵 이런 부분도 컨벤션인데 공통으로 가져가서 추후 작업도 일치하는 습관이 좋은 것 같습니다

2024-07-31 13:41 UTC, gongdongho12 approved these changes
리뷰 내용은 6주차에 반영해 주세요!
머지하겠습니다
고생하셨습니다 😄

2024-07-31 13:41 UTC, merged

2024-08-01 06:14 UTC, eunsoni commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Void> orderItem(@RequestParam("email") String email, @RequestParam("optionId") Long optionId, @RequestParam("quantity") int quantity, @PathVariable Long productId, @RequestP
RestController controller 구분해놓겠습니다!

2024-08-01 06:15 UTC, eunsoni commented on src/main/java/gift/controller/ProductController.java
>  @Controller
넵 처리해둘게요!!

2024-08-01 06:15 UTC, eunsoni commented on src/main/resources/templates/wishlist.html
> +                'Authorization': `Bearer ${token}`
넵 분리해두겠습니다!