충남대 BE_이은경 5주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #50
Opened 2024-07-22 06:54 UTC by pkyung

## 과제 진행 사항
### 카카오 로그인
- [x] 카카오 로그인을 통해 인가 코드를 받는다.
- [x] 액세스 토큰을 추출한다. 
- [x] scope 없을 경우 403 에러 반환한다.

2024-07-22 13:46 UTC, ksy90101 requested changes
고생하셨습니다!!

2024-07-22 13:46 UTC, ksy90101 commented on src/main/java/gift/controller/OAuthController.java
> +    public ResponseEntity<String> getAccessToken(@RequestParam("code") String code) {
토큰은 얻은 다음에, 회원가입 및 로그인이 되어야 할거 같은데 그 로직이 없는거 같아요!?

2024-07-22 13:47 UTC, ksy90101 commented on src/main/java/gift/controller/OAuthController.java
> +        LinkedMultiValueMap<String, String> body = new LinkedMultiValueMap<>();
추상회된 Map interface로 타입을 쓰는게 더 어울리지 않을까요?

2024-07-23 05:10 UTC, pkyung commented on src/main/java/gift/controller/OAuthController.java
> +    public ResponseEntity<String> getAccessToken(@RequestParam("code") String code) {
회원가입과 로그인 과정을 넣도록 하겠습니다.

2024-07-23 05:50 UTC, pkyung commented on src/main/java/gift/controller/OAuthController.java
> +        LinkedMultiValueMap<String, String> body = new LinkedMultiValueMap<>();
네 hashmap으로 수정하겠습니다.

2024-07-23 06:18 UTC, pkyung commented on src/main/java/gift/controller/OAuthController.java
> +        LinkedMultiValueMap<String, String> body = new LinkedMultiValueMap<>();
multiValueMap으로 수정하겠습니다.

2024-07-24 12:08 UTC, ksy90101 approved these changes
어려운 요구 잘 충족해주셔서 감사합니다~
고생많으셨어요!
마무리할게요~

2024-07-24 12:08 UTC, ksy90101 commented on src/main/java/gift/component/KakaoApiComponent.java
> +        String url = "https://kauth.kakao.com/oauth/token";
이건 상수가 어울리지 않을까...
변하지 않는 값일테니깐요.

2024-07-24 12:08 UTC, ksy90101 commented on src/main/java/gift/component/KakaoApiComponent.java
> +    public String getAccessToken(String code) {
해당 메서드가 너무 많은일을 하고 있는거 같아요.
역할ㄹ을 메서드로 분리해보면 어떨가 생각이 듭니다.

분리하는 관점이 어려우면 DM주시면 허들로 이야기 한번 드릴게요~

2024-07-24 12:08 UTC, merged