부산대 BE_원윤서 5주차 과제(Step1)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #53
Opened 2024-07-22 07:29 UTC by yoonsu0325

step1 구현했습니다!

2024-07-22 15:29 UTC, yoo-jaein requested changes
step1 고생하셨습니다~
리뷰 코멘트 확인해주세요!

2024-07-22 15:29 UTC, deactivated-user commented on .gitignore
> +application-secret.properties
👍

2024-07-22 15:29 UTC, deactivated-user commented on src/main/java/gift/kakaoLogin/KakaoLoginService.java
> +}
카카오 api 클라이언트에 대한 테스트 코드도 있으면 좋을 것 같아요.

2024-07-22 15:29 UTC, deactivated-user commented on src/main/java/gift/kakaoLogin/KakaoLoginService.java
> +        if(response.getStatusCode() == HttpStatus.UNAUTHORIZED){
에러 로그도 출력해볼까요?

2024-07-22 15:29 UTC, deactivated-user commented on src/main/java/gift/kakaoLogin/KakaoLoginService.java
> +    private LinkedMultiValueMap<String, String> createBody(String code) {
👍

2024-07-22 15:29 UTC, deactivated-user commented on src/main/java/gift/GlobalExceptionHandler.java
> +            System.out.println(ex.getMessage());
System.out.println 대신 로깅 프레임워크(SLF4J, Logback..)를 사용하는 것이 좋습니다!

2024-07-22 15:29 UTC, deactivated-user commented on src/main/java/gift/kakaoLogin/KakaoLoginService.java
> +        ResponseEntity<Map> response = client.post()
현재 클라이언트에 타임아웃 설정이 명시적으로 되어있지 않네요.
타임아웃을 설정하지 않으면 서버 응답이 없을 때 애플리케이션이 무한히 기다려야 합니다.
그렇게 되면 앱 리소스(스레드, 메모리..)를 계속 점유하게 되어서 시스템 성능 저하가 발생합니다.

2024-07-22 15:29 UTC, deactivated-user commented on src/main/java/gift/GlobalExceptionHandler.java
> +    @ExceptionHandler(RuntimeException.class)
RuntimeException을 전역적으로 처리하는 것은 너무 광범위한 것 같아요. 더 구체적인 예외 타입을 사용하는 것이 좋습니다.

2024-07-22 15:29 UTC, deactivated-user commented on src/main/java/gift/GlobalExceptionHandler.java
> +        if(ex.getMessage().startsWith("kakao")){
카카오 관련 예외를 문자열 비교("kakao")로 구분하는 것은 잘못 처리해버릴 위험성이 있습니다. 
별도의 커스텀 예외 클래스를 만드는 것이 더 안전합니다!

2024-07-22 15:29 UTC, deactivated-user commented on src/main/java/gift/GlobalExceptionHandler.java
> +            int status = Integer.parseInt(ex.getMessage().split(" ")[1]);
.split(" ")[1]로 상태 코드를 파싱하는 방식은 메시지 형식이 변경되면 에러가 발생할 수 있습니다.
ex.getStatus()를 사용해주세요!

2024-07-22 15:29 UTC, yoo-jaein commented on src/main/java/gift/kakaoLogin/KakaoLoginService.java
> +        ResponseEntity<Map> response = client.post()
응답을 Map으로 받는 것보다 DTO를 만들어 사용하는 것이 타입 안전성을 높일 수 있습니다!

2024-07-22 15:29 UTC, yoo-jaein commented on src/main/java/gift/kakaoLogin/KakaoLoginController.java
> +        System.out.println(code);
여기도 별도의 로깅 프레임워크를 사용해주세요!

2024-07-22 15:29 UTC, yoo-jaein commented on src/main/java/gift/kakaoLogin/KakaoLoginService.java
> +    private final RestClient client = RestClient.create();
RestClient를 빈으로 등록해서 재사용하면 좋겠습니다!
외부 api는 보통 여러 개를 연동하는데 빈으로 등록해두면 애플리케이션 전체에서 동일한 설정으로 api 클라이언트를 만들 수 있고 중복 코드도 줄일 수 있습니다.
```java
@Configuration
public class RestClientConfig {

    @Bean
    public RestClient.Builder restClientBuilder() {
        return RestClient.builder()
            . // Connect timeout, read timeout 설정...
            .defaultHeaders(headers -> {
                headers.setContentType(MediaType.APPLICATION_FORM_URLENCODED);
            });
    }

    @Bean
    public RestClient kakaoRestClient(RestClient.Builder restClientBuilder) {
        return restClientBuilder
            .baseUrl(...)
            .build();
    }
}
```
- Connection timeout vs Read timeout: https://alden-kang.tistory.com/20 참고
```java
@Service
public class KakaoLoginService {

    @Value("${kakao.client-id}")
    private String REST_API_KEY;
    
    @Value("${kakao.redirect-url}")
    private String REDIRECT_URI;
    
    private final RestClient kakaoRestClient;

    public KakaoLoginService(RestClient kakaoRestClient) {
        this.kakaoRestClient = kakaoRestClient;
    }
...
```

2024-07-23 06:12 UTC, yoonsu0325 commented on src/main/java/gift/kakaoLogin/KakaoLoginService.java
> +}
카카오에 로그인하는 과정을 테스트로 어떻게 구현해야 할 지를 잘 모르겠습니다... 인가코드를 사용해서 액세스 토큰을 받아오는 부분은 테스트 코드를 짤 수 있는데 그 인가코드를 받아오는 과정은 어떻게 구현해야 할지 모르겠어요 😭

2024-07-23 07:19 UTC, yoo-jaein commented on src/main/java/gift/kakaoLogin/KakaoLoginService.java
> +}
MockRestServiceServer (또는 ```@RestClientTest```)를 사용하면 RestClient의 동작을 모킹할 수 있습니다!
- https://www.baeldung.com/restclienttest-in-spring-boot 참고

성공 케이스 하나, 실패 케이스 하나를 테스트해보면 될 것 같아요.
- 성공 케이스: 올바른 코드를 제공했을 때 예상된 액세스 토큰을 반환하는지 확인
- 실패 케이스: 잘못된 코드를 제공했을 때 예외를 던지는지 확인

2024-07-23 11:24 UTC, yoo-jaein requested changes
리뷰 반영된 것 확인했습니다!
추가 코멘트 확인 부탁드리겠습니다 :)

2024-07-23 11:24 UTC, yoo-jaein commented on build.gradle
> +    implementation 'org.projectlombok:lombok'
앗.. 롬복 사용은 금지되어 있습니다 ㅠㅠ
(생성자, getter, setter를 직접 생성함으로써 무지성으로 생성하지 않는지 지속적으로 체크하기 위함)

2024-07-23 11:24 UTC, yoo-jaein commented on src/main/java/gift/kakaoLogin/RestClientConfig.java
> +public class RestClientConfig {
👍

2024-07-23 11:24 UTC, yoo-jaein commented on src/main/java/gift/kakaoLogin/RestClientConfig.java
> +                .withReadTimeout(Duration.ofMinutes(2)).withConnectTimeout(Duration.ofMinutes(2));
설정 코드를 잘 작성해주셨습니다!
다만 타임아웃 값이 너무 긴 듯 하여.. 추가 설명을 드릴게요.

먼저 타임아웃 값은 정해진 것이 아니라 여러 요소를 고려해야 합니다.
- https://dev.to/bearer/the-importance-of-request-timeouts-l3n 참고

(Read timeout 기준)
웹 서비스같이 사용자 요청에 빠르게 응답해야 한다거나, 즉각적인 응답이 중요한 작업에서는 3~10초 내로 짧게 잡고
백그라운드에서 돌아가도 되는 작업(예: 배치 작업)에서는 비교적 길게 30초까지도 잡습니다.

혹은 해당 api의 평균 성공 응답 시간, 평균 에러 응답 시간을 재보고 수치를 조정하기도 합니다.

그리고 일반적으로 Connection timeout이 Read timeout보다 짧게 설정됩니다.

Connection timeout은 클라이언트-서버 사이 tcp 핸드셰이크의 timeout이고,
Read timeout은 클라이언트-서버 사이 데이터 교환이 이루어지는 전체 사이클과 관련된 timeout이기 때문입니다.

2024-07-23 11:25 UTC, yoonsu0325 commented on build.gradle
> +    implementation 'org.projectlombok:lombok'
다른데에는 사용하지는 않았고 @Slf4j 때문에 추가했습니다!

2024-07-23 11:51 UTC, yoo-jaein commented on build.gradle
> +    implementation 'org.projectlombok:lombok'
번거로우시겠지만 온전한 코드를 작성해주시고 의존성은 제거 부탁드립니다 ㅠㅠ
채점 가이드에 있어서요..

2024-07-23 12:04 UTC, yoonsu0325 commented on build.gradle
> +    implementation 'org.projectlombok:lombok'
아 롬복이 있어야 slf4j를 쓸 수 있는줄 알았어요.. 삭제했습니다!

2024-07-23 12:17 UTC, yoonsu0325 commented on src/main/java/gift/kakaoLogin/KakaoLoginService.java
> +}
링크에 있는 방법대로 테스트를 만들어 봤는데 의존성 주입이 잘 안되는지 계속 에러가 발생해서... 일단은 따로 url접속해서 받아온 인가코드를 사용해서 테스트를 했습니다!

2024-07-23 14:28 UTC, yoo-jaein approved these changes
리뷰 꼼꼼히 반영해주셨네요!
고생 많으셨습니다.
step1 머지하겠습니다 :)

2024-07-23 14:28 UTC, yoo-jaein commented on src/test/resources/application.properties
> +logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE\
\ 오타같아요!

2024-07-23 14:32 UTC, merged