부산대 BE_박정우 5주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-order pull request #61
Opened 2024-07-22 09:04 UTC by doubleclip118

2024-07-22 14:06 UTC, yoo-jaein requested changes
step1 고생하셨습니다~
리뷰 코멘트 확인해주세요!

2024-07-22 14:06 UTC, deactivated-user commented on src/main/java/gift/utils/ExternalApiService.java
> +import org.springframework.web.util.UriComponentsBuilder;
사용하지 않는 Import 문 정리가 필요합니다!

2024-07-22 14:06 UTC, deactivated-user commented on src/main/resources/application.properties
> +kakao.rest-api-key=49038dda6e55e02ca2783585d5d816a7
api key 정보는 이렇게 깃허브에 올라가면 안됩니다. 삭제 후 재발급해주세요!
(특히나 유료 api key가 깃허브에 유출될 경우 해커에 의해 과금 폭탄을 맞을 수 있습니다.)
재발급하신 key 정보를 별도의 파일로 관리하고, 해당 파일을 gitignore에 포함시키는 방식으로 구현하시면 될 것 같습니다.

2024-07-22 14:06 UTC, deactivated-user commented on src/main/java/gift/utils/config/KakaoProperties.java
> +public class KakaoProperties {
properties 👍

2024-07-22 14:06 UTC, deactivated-user commented on src/main/java/gift/utils/ExternalApiService.java
> +public class ExternalApiService {
현재 클라이언트에 타임아웃 설정이 명시적으로 되어있지 않네요.
타임아웃을 설정하지 않으면 서버 응답이 없을 때 애플리케이션이 무한히 기다려야 합니다.
그렇게 되면 앱 리소스(스레드, 메모리..)를 계속 점유하게 되어서 시스템 성능 저하가 발생합니다.

2024-07-22 14:06 UTC, deactivated-user commented on src/main/java/gift/utils/ExternalApiService.java
> +    public ResponseEntity<Map<String,Object>> postKakaoToken(String code) {
Map<String, Object> 보다 구체적인 DTO를 반환하는 것이 더 좋을 것 같습니다!

2024-07-22 14:06 UTC, deactivated-user commented on src/main/java/gift/utils/ExternalApiService.java
> +        String fullUrl = baseUrl + endpoint;
UriComponentsBuilder를 사용해서 url을 구성하면 더 안전하게 코드를 작성할 수 있습니다!
- https://2carrot84.github.io/development/uri-component-builder/ 참고

```java
String fullUrl = UriComponentsBuilder.fromHttpUrl(baseUrl)
    .path( .... )
```

2024-07-22 14:06 UTC, deactivated-user commented on src/main/java/gift/utils/ExternalApiService.java
> +        } catch (Exception e) {
일반적인 Exception을 catch 하는 것은 너무 범위가 넓은 것 같아요.

2024-07-22 14:06 UTC, yoo-jaein commented on src/main/java/gift/utils/ExternalApiService.java
> +public class ExternalApiService {
추가로 RestTemplate을 빈으로 등록하면 좋을 것 같습니다!
외부 api는 보통 여러 개를 연동하는데 빈으로 등록해두면 애플리케이션 전체에서 동일한 설정으로 api 클라이언트를 만들 수 있고 중복 코드도 줄일 수 있습니다.

```java
@Configuration
public class RestTemplateConfig {

    @Bean
    public RestTemplate restTemplate(RestTemplateBuilder builder) {
        return builder
            .setConnectTimeout(Duration.ofSeconds(...))
            .setReadTimeout(Duration.ofSeconds(...))
            .build();
    }
}
```
- Connection timeout vs Read timeout: https://alden-kang.tistory.com/20 참고
```java
@Service
public class ExternalApiService {
    private final RestTemplate restTemplate;
    private final KakaoProperties kakaoProperties;
    private final String baseUrl = "https://kauth.kakao.com/oauth";

    public ExternalApiService(RestTemplate restTemplate, KakaoProperties kakaoProperties) {
        this.restTemplate = restTemplate;
        this.kakaoProperties = kakaoProperties;
    }
...
```

2024-07-22 14:06 UTC, yoo-jaein commented on src/main/java/gift/utils/ExternalApiService.java
> +            requestBody.add("redirect_uri", kakaoProperties.getRedirectUri());
requestBody 부분은 try 블록 밖에 위치하는 것이 적합한 것 같습니다.
- try ( api 콜 ) catch ( api 응답에 대한 예외 처리 )

2024-07-22 14:06 UTC, yoo-jaein commented on src/main/java/gift/utils/ExternalApiService.java
> +            errorResponse.put("details", e.getMessage());
에러 로그도 출력해볼까요?

2024-07-22 14:06 UTC, yoo-jaein commented on src/main/java/gift/utils/ExternalApiService.java
> +}
카카오 api 클라이언트에 대한 테스트 코드도 있으면 좋을 것 같아요.

2024-07-23 05:23 UTC, doubleclip118 commented on src/main/resources/application.properties
> +kakao.rest-api-key=49038dda6e55e02ca2783585d5d816a7
헉 감사합니다 재발급 받았습니다!

2024-07-23 06:02 UTC, doubleclip118 commented on src/main/java/gift/utils/ExternalApiService.java
> +public class ExternalApiService {
티스토리 글에서
Read Timeout은 Connection Timeout에 비해 좀 더 짧게 가져가게 됩니다 라고 되어있고 뒤는 프로세싱 시간을 read timeout은 고려해야한다라고 되어있는데 일반적인 서비스에서 몇초정도를 기준으로 잡는지가 궁금합니다!

2024-07-23 10:50 UTC, yoo-jaein commented on src/main/java/gift/utils/ExternalApiService.java
> +public class ExternalApiService {
타임아웃 값은 정해진 것이 아니라 여러 요소를 고려해야 합니다.
- https://dev.to/bearer/the-importance-of-request-timeouts-l3n 참고

웹 서비스같이 사용자 요청에 빠르게 응답해야 한다거나, 즉각적인 응답이 중요한 작업에서는 3~10초 내로 짧게 잡고
백그라운드에서 돌아가도 되는 작업(예: 배치 작업)에서는 비교적 길게 30초까지도 잡습니다.

혹은 해당 api의 평균 성공 응답 시간, 평균 에러 응답 시간을 재보고 수치를 조정하기도 합니다.

2024-07-23 10:56 UTC, yoo-jaein commented on src/main/java/gift/utils/ExternalApiService.java
> +public class ExternalApiService {
그리고 일반적으로 Connection timeout이 Read timeout보다 짧게 설정됩니다.

Connection timeout은 클라이언트-서버 사이 tcp 핸드셰이크의 timeout이고, 
Read timeout은 클라이언트-서버 사이 데이터 교환이 이루어지는 전체 사이클과 관련된 timeout입니다.

2024-07-23 11:04 UTC, yoo-jaein approved these changes
리뷰 꼼꼼하게 반영해주셨네요! 
step1 머지하겠습니다 :)

간단한 코멘트 달았으니 확인 부탁드려요!

2024-07-23 11:04 UTC, deactivated-user commented on .gitignore
> +/src/main/resources/application.properties
👍

2024-07-23 11:04 UTC, yoo-jaein commented on src/main/java/gift/utils/ExternalApiService.java
> +            MultiValueMap<String, String> requestBody = new LinkedMultiValueMap<>();
requestBody를 생성하는 부분을 별도의 private 메서드로 추출하면 코드가 가벼워질 것 같아요!

2024-07-23 11:04 UTC, yoo-jaein commented on src/main/java/gift/utils/config/RestTemplateConfig.java
> +    @Bean
👍

2024-07-23 11:04 UTC, merged